"""Global caption (``L_glo``) generator via Gemma 4 multimodal (US-036-a v2, T1).

This module produces the **global image-text caption** ``L_glo`` per PASTIS-R
patch for the faithful FarSLIP redesign (Li et al. 2025, eq. 1-2: InfoNCE
image-text alignment). The caption is generated by the **local Gemma 4 31B
multimodal** model served by Ollama on the H100 VM.

Validated method (CRITICAL, do not change):
    - HTTP ``POST http://127.0.0.1:11434/api/chat`` (NOT ``/api/generate``, NOT
      the CLI) with payload::

          {"model": "gemma4:31b-it-q8_0",
           "messages": [{"role": "user", "content": <prompt>,
                         "images": [<base64_png>]}],
           "think": false, "stream": false,
           "options": {"temperature": 0.4, "num_predict": 400}}

      ``"think": false`` is OBLIGATORY: without it the model reasons forever and
      times out; with it a multimodal caption takes ~3.1 s.
    - Image: peak-NDVI composite, contrast-enhanced per channel via the 2-98
      percentile, mapped to RGB (B04, B03, B02 -> R, G, B) and rendered as an
      **896 px** PNG (128 px does NOT work, too small for Gemma's vision
      projector). The 4-band TRAINING tensor stays unmodified at [0, 1]; the
      enhancement/RGB/896 view is ONLY the image Gemma sees.

Anti data-leakage contract (paper-faithful, no circular leak):
    The prompt feeds the present PASTIS classes (from the semantic mask), the
    spatial composition (north/center/south), the parcel count / area, the
    geographic context (MGRS tile + composite date) and the TYPICAL phenology of
    each crop (US-033 class knowledge). It is FORBIDDEN to inject numeric
    NDVI/index values computed from the input patch (circular leak), AlphaEarth,
    or the label as the answer ("the class is X"): the caption must DESCRIBE the
    scene, never reveal the dominant label as a classification answer.

Pure logic (prompt builder + enhancement) is testable without network; the HTTP
client is mockeable. Project conventions: ``numpy`` only at the data boundary;
logging via ``structlog``; type hints everywhere; English docstrings.
"""

from __future__ import annotations

import base64
import io
import json
import time
import urllib.error
import urllib.request

import numpy as np
import structlog

logger = structlog.get_logger(__name__)

#: Validated Ollama chat endpoint and model. ``/api/chat`` (NOT ``/api/generate``).
_OLLAMA_CHAT_PATH: str = "/api/chat"
_DEFAULT_BASE_URL: str = "http://127.0.0.1:11434"
_DEFAULT_MODEL: str = "gemma4:31b-it-q8_0"

#: Sampling options validated on the H100 VM (~3.1 s/caption with think=false).
_DEFAULT_TEMPERATURE: float = 0.4
_DEFAULT_NUM_PREDICT: int = 400

#: Composite band order returned by ``peak_ndvi_composite`` (B02, B03, B04, B08).
#: For the RGB image Gemma sees, R=B04(idx2), G=B03(idx1), B=B02(idx0).
_IDX_B02: int = 0
_IDX_B03: int = 1
_IDX_B04: int = 2

#: Side of the PNG Gemma sees. 896 px validated; 128 px does NOT work.
_DEFAULT_SIDE: int = 896

#: Percentile clip for the per-channel contrast enhancement (2-98).
_PCT_LOW: float = 2.0
_PCT_HIGH: float = 98.0

#: Prompt version stamped into the captions parquet (bump on prompt changes).
PROMPT_VERSION: str = "v2"


def _percentile_stretch(channel: np.ndarray) -> np.ndarray:
    """Stretches a single channel to [0, 1] via the 2-98 percentile clip.

    Robust contrast enhancement: pixels below the 2nd percentile map to 0 and
    above the 98th map to 1, with a linear ramp in between. A degenerate channel
    (``p98 == p2``) maps to all zeros (no contrast to recover).

    Args:
        channel: float32 ``(H, W)`` channel in [0, 1].

    Returns:
        float32 ``(H, W)`` enhanced channel in [0, 1].
    """
    p_low = float(np.percentile(channel, _PCT_LOW))
    p_high = float(np.percentile(channel, _PCT_HIGH))
    span = p_high - p_low
    if span <= 1e-12:
        return np.zeros_like(channel, dtype=np.float32)
    stretched = (channel - p_low) / span
    return np.clip(stretched, 0.0, 1.0).astype(np.float32)


def composite_to_png896(composite4: np.ndarray, side: int = _DEFAULT_SIDE) -> bytes:
    """Renders a 4-band composite to an enhanced RGB PNG of ``side`` px.

    Maps the peak-NDVI composite ``(4, H, W)`` (bands B02, B03, B04, B08 in
    [0, 1]) to an RGB image with R=B04, G=B03, B=B02, applies the per-channel
    2-98 percentile stretch (ONLY for the image Gemma sees; the training tensor
    is untouched) and resizes to ``side x side`` with bilinear interpolation.

    Args:
        composite4: float32 ``(4, H, W)`` composite in [0, 1] from
            :func:`ml.farslip.pastis_pair_dataset.peak_ndvi_composite`.
        side: target square side in px (default 896, validated for Gemma).

    Returns:
        PNG bytes of the ``side x side`` RGB image.

    Raises:
        ValueError: if ``composite4`` is not a 4-band ``(4, H, W)`` array.
    """
    if composite4.ndim != 3 or composite4.shape[0] < 3:
        raise ValueError(f"composite4 must be (>=3, H, W), received shape {composite4.shape}.")
    comp = composite4.astype(np.float32)
    # RGB order: R=B04 (idx2), G=B03 (idx1), B=B02 (idx0).
    rgb = np.stack(
        [
            _percentile_stretch(comp[_IDX_B04]),
            _percentile_stretch(comp[_IDX_B03]),
            _percentile_stretch(comp[_IDX_B02]),
        ],
        axis=-1,
    )  # (H, W, 3) in [0, 1]
    rgb_u8 = (np.clip(rgb, 0.0, 1.0) * 255.0).round().astype(np.uint8)

    from PIL import Image

    image = Image.fromarray(rgb_u8, mode="RGB")
    if image.size != (side, side):
        image = image.resize((side, side), Image.Resampling.BILINEAR)
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


def composite_to_png896_b64(composite4: np.ndarray, side: int = _DEFAULT_SIDE) -> str:
    """Convenience wrapper: enhanced RGB PNG ``side`` px as a base64 string.

    Args:
        composite4: float32 ``(4, H, W)`` composite in [0, 1].
        side: target square side in px (default 896).

    Returns:
        Base64-encoded PNG string (ASCII), ready for the Ollama ``images`` field.
    """
    return base64.b64encode(composite_to_png896(composite4, side=side)).decode("ascii")


def _spatial_composition(semantic: np.ndarray, active_class_ids: tuple[int, ...]) -> str:
    """Summarizes the north/center/south spatial composition of the mask.

    Splits the mask into three horizontal bands (top=north, middle=center,
    bottom=south) and, for each band, reports the dominant ACTIVE crop class
    name (ignoring background/void and non-active classes). The result is a short
    Spanish phrase consumed by the prompt. NO numeric NDVI/index leaks: it only
    states which crop occupies each band.

    Args:
        semantic: ``(H, W)`` PASTIS semantic mask (class_id per pixel).
        active_class_ids: active PASTIS class_ids (1..18 subset).

    Returns:
        Spanish phrase, e.g. ``"norte: pradera; centro: maiz; sur: vinedo"``.
    """
    from ml.ingest.pastis_loader import PASTIS_CLASS_MAP

    height = semantic.shape[0]
    third = max(height // 3, 1)
    bands = {
        "norte": semantic[:third],
        "centro": semantic[third : 2 * third],
        "sur": semantic[2 * third :],
    }
    active_set = set(active_class_ids)
    parts: list[str] = []
    for label, band in bands.items():
        if band.size == 0:
            continue
        hist = np.bincount(band.ravel().astype(np.int64), minlength=20)
        best_cid = 0
        best_count = 0
        for cid in active_set:
            count = int(hist[cid])
            if count > best_count:
                best_count = count
                best_cid = cid
        if best_cid == 0:
            parts.append(f"{label}: sin cultivo declarado")
        else:
            name = PASTIS_CLASS_MAP.get(best_cid, f"clase {best_cid}")
            parts.append(f"{label}: {name}")
    return "; ".join(parts)


def build_caption_prompt(
    present_class_names: list[str],
    spatial_composition: str,
    n_parcels: int,
    total_area_px: int,
    tile_mgrs: str,
    composite_date: str,
    typical_phenology: dict[str, str],
) -> str:
    """Builds the Spanish prompt that asks Gemma to DESCRIBE the scene.

    Assembles the present classes, the north/center/south spatial composition,
    the parcel count / area, the MGRS tile + composite date and the TYPICAL
    phenology of each present crop (US-033 class knowledge). The prompt FORBIDS
    numeric NDVI/index values of the patch (circular leak), AlphaEarth, and the
    label as a classification answer ("la clase es X" / "the class is X"): it
    asks for a descriptive caption, not a label.

    Args:
        present_class_names: human-readable PASTIS class names present in the patch.
        spatial_composition: north/center/south summary phrase.
        n_parcels: number of agronomic parcels (instances) in the patch.
        total_area_px: total cropped area in pixels (sum of valid parcels).
        tile_mgrs: Sentinel-2 MGRS tile (e.g. ``T31TFM``).
        composite_date: ``YYYYMMDD`` date of the peak-NDVI composite timestep.
        typical_phenology: ``{class_name: typical phenology description}`` (US-033).

    Returns:
        Spanish prompt string for the Ollama ``content`` field.
    """
    classes_str = ", ".join(present_class_names) if present_class_names else "no determinadas"
    phenology_lines: list[str] = []
    for name in present_class_names:
        desc = typical_phenology.get(name)
        if desc:
            phenology_lines.append(f"- {name}: {desc}")
    phenology_block = (
        "\n".join(phenology_lines)
        if phenology_lines
        else "- (sin descripcion fenologica tipica disponible)"
    )

    return (
        "Eres un agronomo experto en teledeteccion. Observa la imagen satelital "
        "Sentinel-2 (composicion en color real, pico de la temporada de "
        "crecimiento) de una parcela agricola en Francia y redacta una "
        "descripcion objetiva de la escena en espanol, en 3 a 5 frases.\n\n"
        "Contexto verificado de la escena (usalo para describir, no lo repitas "
        "literalmente):\n"
        f"- Cultivos presentes segun el catastro agricola: {classes_str}.\n"
        f"- Composicion espacial (de norte a sur): {spatial_composition}.\n"
        f"- Numero de parcelas agronomicas distintas: {n_parcels}.\n"
        f"- Superficie cultivada total aproximada: {total_area_px} pixeles.\n"
        f"- Localizacion (tesela Sentinel-2 MGRS): {tile_mgrs}.\n"
        f"- Fecha del composite (pico de vegetacion): {composite_date}.\n"
        "- Fenologia tipica de cada cultivo presente (conocimiento general de "
        "la clase, no medido en esta imagen):\n"
        f"{phenology_block}\n\n"
        "Instrucciones de redaccion:\n"
        "- Describe la textura, el patron de parcelas, la fragmentacion y el "
        "vigor visual aparente de la vegetacion en la imagen.\n"
        "- Integra la fenologia tipica de los cultivos y el momento del ano para "
        "explicar el aspecto esperado de la escena.\n"
        "- NO escribas valores numericos de NDVI ni de ningun indice espectral.\n"
        "- NO menciones AlphaEarth ni embeddings satelitales.\n"
        "- NO declares la clasificacion como respuesta (no escribas 'la clase es' "
        "ni 'el cultivo dominante es'); describe la escena, no la etiquetes.\n"
        "Responde unicamente con la descripcion."
    )


class GemmaCaptionClient:
    """HTTP client for the local Gemma 4 multimodal model served by Ollama.

    Calls ``POST {base_url}/api/chat`` with ``think=false`` and an inline base64
    image (validated method, see module docstring). Retries on transient HTTP /
    URL errors with a short backoff and returns the caption text plus the
    generation wall-time. The class holds no model state: it is a thin,
    mockeable transport wrapper.

    Args:
        base_url: Ollama base URL (default ``http://127.0.0.1:11434``).
        model: Ollama model tag (default ``gemma4:31b-it-q8_0``).
        timeout_s: per-request timeout in seconds (default 60).
        max_retries: number of retries after the first attempt (default 2).
        temperature: sampling temperature (default 0.4, validated).
        num_predict: max tokens to generate (default 400, validated).
    """

    def __init__(
        self,
        base_url: str = _DEFAULT_BASE_URL,
        model: str = _DEFAULT_MODEL,
        timeout_s: float = 60.0,
        max_retries: int = 2,
        temperature: float = _DEFAULT_TEMPERATURE,
        num_predict: int = _DEFAULT_NUM_PREDICT,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout_s = float(timeout_s)
        self.max_retries = int(max_retries)
        self.temperature = float(temperature)
        self.num_predict = int(num_predict)

    def _build_payload(self, prompt: str, image_png_b64: str) -> dict[str, object]:
        """Builds the validated ``/api/chat`` request body.

        Args:
            prompt: caption prompt text.
            image_png_b64: base64-encoded PNG (the 896 px enhanced RGB view).

        Returns:
            Request body dict. ``think`` is False and ``stream`` is False
            (validated: without ``think=false`` the model times out).
        """
        return {
            "model": self.model,
            "messages": [
                {
                    "role": "user",
                    "content": prompt,
                    "images": [image_png_b64],
                }
            ],
            "think": False,
            "stream": False,
            "options": {
                "temperature": self.temperature,
                "num_predict": self.num_predict,
            },
        }

    def _post(self, payload: dict[str, object]) -> dict[str, object]:
        """POSTs the payload to ``/api/chat`` and parses the JSON response.

        Args:
            payload: request body from :meth:`_build_payload`.

        Returns:
            Parsed JSON response dict.

        Raises:
            urllib.error.URLError: on transport failure (caught by the retry loop).
        """
        url = f"{self.base_url}{_OLLAMA_CHAT_PATH}"
        data = json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(  # noqa: S310 - fixed localhost Ollama URL
            url,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=self.timeout_s) as resp:  # noqa: S310
            raw = resp.read().decode("utf-8")
        parsed = json.loads(raw)
        if not isinstance(parsed, dict):
            raise ValueError("Ollama /api/chat returned a non-object JSON body.")
        return parsed

    @staticmethod
    def _parse_caption(response: dict[str, object]) -> str:
        """Extracts and cleans the caption text from an Ollama chat response.

        Args:
            response: parsed ``/api/chat`` JSON (``message.content`` field).

        Returns:
            The caption text, whitespace-trimmed.

        Raises:
            ValueError: if the response carries no ``message.content`` text.
        """
        message = response.get("message")
        if not isinstance(message, dict):
            raise ValueError("Ollama response missing 'message' object.")
        content = message.get("content")
        if not isinstance(content, str) or not content.strip():
            raise ValueError("Ollama response missing non-empty 'message.content'.")
        return content.strip()

    def caption(self, prompt: str, image_png_b64: str) -> tuple[str, float]:
        """Generates a caption for one image via ``/api/chat`` (think=false).

        Args:
            prompt: caption prompt text from :func:`build_caption_prompt`.
            image_png_b64: base64 PNG of the 896 px enhanced RGB composite.

        Returns:
            ``(caption, gen_seconds)`` where ``gen_seconds`` is the wall-clock
            generation time.

        Raises:
            RuntimeError: if every attempt (1 + ``max_retries``) fails.
        """
        payload = self._build_payload(prompt, image_png_b64)
        last_error: Exception | None = None
        for attempt in range(self.max_retries + 1):
            start = time.perf_counter()
            try:
                response = self._post(payload)
                caption = self._parse_caption(response)
                elapsed = time.perf_counter() - start
                logger.info(
                    "gemma_caption_ok",
                    attempt=attempt,
                    gen_seconds=round(elapsed, 3),
                    n_chars=len(caption),
                )
                return caption, elapsed
            except (urllib.error.URLError, ValueError, TimeoutError) as exc:
                last_error = exc
                logger.warning(
                    "gemma_caption_retry",
                    attempt=attempt,
                    max_retries=self.max_retries,
                    error=str(exc),
                )
                if attempt < self.max_retries:
                    time.sleep(0.5 * (attempt + 1))
        raise RuntimeError(
            f"Gemma caption failed after {self.max_retries + 1} attempts: {last_error}"
        )


def generate_caption(
    composite4: np.ndarray,
    *,
    present_class_names: list[str],
    spatial_composition: str,
    n_parcels: int,
    total_area_px: int,
    tile_mgrs: str,
    composite_date: str,
    typical_phenology: dict[str, str],
    client: GemmaCaptionClient,
    side: int = _DEFAULT_SIDE,
) -> tuple[str, float]:
    """End-to-end single-patch caption: composite -> PNG -> prompt -> Gemma.

    Builds the 896 px enhanced RGB PNG, assembles the anti-leakage prompt and
    calls the Gemma client. The 4-band training tensor is NOT modified (the PNG
    is a derived view only).

    Args:
        composite4: float32 ``(4, H, W)`` peak-NDVI composite in [0, 1].
        present_class_names: PASTIS class names present in the patch.
        spatial_composition: north/center/south summary phrase.
        n_parcels: number of agronomic parcels.
        total_area_px: total cropped area in pixels.
        tile_mgrs: Sentinel-2 MGRS tile.
        composite_date: ``YYYYMMDD`` composite date.
        typical_phenology: ``{class_name: typical phenology}`` (US-033).
        client: an instance of :class:`GemmaCaptionClient` (mockeable).
        side: PNG side in px (default 896).

    Returns:
        ``(caption, gen_seconds)``.
    """
    image_b64 = composite_to_png896_b64(composite4, side=side)
    prompt = build_caption_prompt(
        present_class_names=present_class_names,
        spatial_composition=spatial_composition,
        n_parcels=n_parcels,
        total_area_px=total_area_px,
        tile_mgrs=tile_mgrs,
        composite_date=composite_date,
        typical_phenology=typical_phenology,
    )
    return client.caption(prompt, image_b64)
