"""Phenology semantic branch via description + text-encoder (US-022b-D).

Implements the Wen et al. (2025) "Phenology description is all you
need!" method §3.2-3.3: given a parcel's temporal NDVI curve, it produces
a structured textual description with an LLM and encodes it with a
text-encoder into a dense vector that is concatenated to the baseline's
tabular vector.

The generator uses **Gemini 3.5 Flash** (ADR-006 D4, decision approved by
the team) via Vertex AI / LiteLLM (no new ``google-genai`` SDK). The
default text-encoder is ``sentence-transformers`` (already in deps); the
FarSLIP CLIP text-encoder remains a documented alternative (not
implemented here — owned by US-017).

Canonical decisions (plan ``docs/us-planning/us-022b.md`` §6.3):

- **D-ARQ-3**: the semantic branch is a **model component**, not a trivial
  FE column. Its own module + cache + tests.
- **D-ARQ-5**: Gemini is invoked via ``litellm`` (already in deps) which
  routes to Vertex AI. No new ``google-genai`` SDK.
- **R7 mitigated**: ``temperature=0`` + cache per ``parcel_id`` + stratified
  subset mandatory. The test suite mocks Gemini in CI (zero network
  calls).
- **Module output**: ``pl.DataFrame`` with ``parcel_id`` + N
  ``pheno_text_NNN`` columns; the block enters ``fusion.py`` via LEFT JOIN.

3-block prompt (Wen Fig. 2):
  1. **General**: problem description and expected format.
  2. **Time-Series Curve**: the NDVI values and days of the year.
  3. **Restrictive Instruction**: structured output, no extra text.
"""

from __future__ import annotations

import hashlib
import json
import os
import time
import warnings
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import polars as pl
import structlog

logger = structlog.get_logger(__name__)

__all__ = [
    "PhenologyDescription",
    "build_phenology_text_block",
    "default_cache_dir",
    "encode_descriptions",
    "generate_phenology_description",
    "set_llm_client",
]

#: Environment variables that count as "valid credentials" to
#: invoke Gemini 3.5 Flash (public API or Vertex AI).
_CREDENTIAL_ENV_VARS: tuple[str, ...] = (
    "GEMINI_API_KEY",
    "GOOGLE_API_KEY",
    "GOOGLE_GENAI_USE_VERTEXAI",
    "GOOGLE_CLOUD_PROJECT",
)

#: Estimated cost per phenology description generated with Gemini 3.5 Flash
#: (~500 input tokens + ~100 output tokens with public pricing May 2026).
#: Used only for informative budget tracking, not exact.
COST_PER_DESCRIPTION_USD: float = 0.0001

#: Client-side HTTP timeout (ms) for the google-genai call. Without it a stuck
#: socket hangs a worker thread (and the completion-gated flush) forever; on
#: timeout the SDK raises and the retry loop treats it as transient.
_HTTP_TIMEOUT_MS: int = 60_000

#: Number of dimensions of the dense vector produced by
#: ``sentence-transformers/all-MiniLM-L6-v2`` (default model).
#: The constant exists so that ``fusion.py`` validates the contract.
DEFAULT_TEXT_ENCODER: str = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_TEXT_EMBED_DIM: int = 384

#: Complete 3-block prompt in the style of Wen et al. 2025 Fig. 2.
PROMPT_TEMPLATE: str = """[BLOQUE 1 - GENERAL]
Eres un agronomo experto en teledeteccion. Tu tarea es describir la
fenologia de una parcela agricola a partir de su curva NDVI anual derivada
de Sentinel-2. La descripcion sirve para alinearse, via un text-encoder
contrastivo, con una representacion visual del cultivo.

[BLOQUE 2 - SERIE TEMPORAL]
Curva NDVI muestreada en {n_points} puntos del anio:
{curve_serialization}

Pico NDVI: {peak_value:.3f} en el dia {peak_doy} del anio.
Inicio de crecimiento (SOG, umbral 0.3): dia {sog_doy}.
Senescencia (NDVI < 0.3 tras pico): dia {senescence_doy}.
Pista de cultivo (puede estar vacia): {crop_type_hint}.

[BLOQUE 3 - INSTRUCCION RESTRICTIVA]
Devuelve UNICAMENTE un parrafo de 3-4 frases en espanol descriptivo,
sin saltos de linea, sin viñetas, sin encabezados. Menciona: temporada
agronomica probable, comportamiento del crecimiento (rapido/lento/doble
pico/uniforme), nivel de pico (bajo/medio/alto), y duracion estimada de
la madurez (corta/media/larga). NO inventes valores numericos fuera de
los datos dados. NO repitas los numeros literales del bloque 2.
"""


# ---------------------------------------------------------------------------
# Dataclass + cache.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PhenologyDescription:
    """Phenology description of a parcel + its embedding.

    Attributes:
        parcel_id: Parcel identifier (accepts int or string).
        description: Text generated by the LLM (no control characters).
        embedding: Dense text-encoder vector (shape ``(D,)``).
        crop_type_hint: Crop hint supplied to the prompt (may be
            ``None``).
    """

    parcel_id: int | str
    description: str
    embedding: list[float]
    crop_type_hint: str | None


def default_cache_dir() -> Path:
    """Default directory for the descriptions cache (DVC-friendly).

    Returns:
        ``data/cache/phenology_descriptions/`` (creates the directory if it
        does not exist; ``.gitignore`` excludes it except the manifest).
    """
    repo_root = Path(__file__).resolve().parents[2]
    cache = repo_root / "data" / "cache" / "phenology_descriptions"
    cache.mkdir(parents=True, exist_ok=True)
    return cache


# ---------------------------------------------------------------------------
# LLM client (mockable in tests).
# ---------------------------------------------------------------------------


#: LLM client signature: ``(prompt, *, model, temperature) -> str``.
LlmClient = Callable[..., str]


_LLM_CLIENT: LlmClient | None = None


def set_llm_client(client: LlmClient | None) -> None:
    """Inject a custom LLM client (primary use: mocked tests).

    Args:
        client: Callable ``(prompt: str, *, model: str, temperature: float)
            -> str``. Pass ``None`` to restore the LiteLLM/Vertex AI default.
    """
    global _LLM_CLIENT
    _LLM_CLIENT = client


def _default_litellm_client(prompt: str, *, model: str, temperature: float) -> str:
    """Gemini 3.5 Flash client via LiteLLM (provider-agnostic fallback).

    Lazy import: only needed at runtime and only if there is no client
    injected via ``set_llm_client``. In CI/tests there is ALWAYS a mock.
    """
    try:
        import litellm
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "litellm is not installed. Run `poetry install --with ml`. "
            "Alternatively inject a client with `set_llm_client(...)`."
        ) from exc

    response = litellm.completion(  # type: ignore[attr-defined]
        model=model if "/" in model else f"vertex_ai/{model}",
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
        max_tokens=512,
    )
    # LiteLLM normalizes the response to OpenAI format.
    content = response["choices"][0]["message"]["content"]
    return str(content).strip()


def _model_supports_thinking_level(model: str) -> bool:
    """Whether ``model`` accepts the ``thinking_level`` config field.

    Only Gemini 3.x models support it; 2.x models (and others) return
    ``400 Thinking level is not supported for this model``. Matches the
    major version after the ``gemini-`` prefix (e.g. ``gemini-3.5-flash`` ->
    True, ``gemini-2.5-flash-lite`` -> False).

    Args:
        model: Model identifier.

    Returns:
        ``True`` for ``gemini-3.x`` models, ``False`` otherwise.
    """
    name = model.lower().removeprefix("models/")
    if not name.startswith("gemini-"):
        return False
    version = name[len("gemini-") :]
    major = version.split(".", 1)[0].split("-", 1)[0]
    return major.isdigit() and int(major) >= 3


def _has_credentials() -> bool:
    """Check whether Gemini credentials are configured in the environment.

    Detects any of the following auth options (order not relevant):

    - ``GEMINI_API_KEY``: public Google AI Studio API.
    - ``GOOGLE_API_KEY``: historical alias of the public API.
    - ``GOOGLE_GENAI_USE_VERTEXAI=true``: Vertex AI mode with the
      environment SA (Cloud Run, Vertex Workbench, etc.).
    - ``GOOGLE_CLOUD_PROJECT``: defined GCP project (sufficient when
      combined with ADC / implicit SA).

    Returns:
        ``True`` if at least one credential is present with a non-empty
        value. ``False`` if all are absent or empty.
    """
    for var in _CREDENTIAL_ENV_VARS:
        value = os.environ.get(var, "").strip()
        if value and value.lower() not in {"false", "0"}:
            return True
    return False


def _default_google_genai_client(prompt: str, *, model: str, temperature: float) -> str:
    """Native Gemini 3.5 Flash client via the google-genai SDK.

    More efficient than LiteLLM for this case: it supports ``thinking_level``
    (default ``"minimal"`` for low latency on short descriptions) and
    allows structured output with ``response_json_schema``. For now we
    return plain text for compatibility with the ``LlmClient`` contract;
    structured output is left ready for
    ``build_phenology_text_block_structured`` (next iteration).

    Auth:
      - Vertex AI (preferred): export ``GOOGLE_GENAI_USE_VERTEXAI=true`` +
        ``GOOGLE_CLOUD_PROJECT=...`` + ``GOOGLE_CLOUD_LOCATION=us-central1``.
        Uses the environment SA (Cloud Run, Vertex AI Workbench, etc.).
      - Public Gemini API: export ``GEMINI_API_KEY=...`` (or ``GOOGLE_API_KEY``).

    Lazy import of the SDK; tests use ``set_llm_client`` with a mock.

    Args:
        prompt: Text of the 3-block prompt (Wen et al. 2025 Fig. 2).
        model: Model identifier, default ``"gemini-3.5-flash"``.
        temperature: Determinism. ``0.0`` for a stable per-parcel cache.

    Returns:
        Plain text of the generated phenology description.
    """
    try:
        from google import genai  # type: ignore[import-not-found]
        from google.genai import types  # type: ignore[import-not-found]
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "google-genai is not installed. Run `poetry add google-genai`. "
            "Alternatively use the LiteLLM client (fallback) or inject a "
            "mock with `set_llm_client(...)`."
        ) from exc

    # `Client()` auto-detects Vertex AI vs public API from env vars. A
    # client-side HTTP timeout (60s) is MANDATORY for long batches: without it a
    # single stuck socket hangs the worker thread indefinitely (and, with a
    # completion-gated flush, the whole job) -- observed on the 69k run when the
    # API got flaky. On timeout the call raises and the retry loop below kicks in.
    client = genai.Client(http_options=types.HttpOptions(timeout=_HTTP_TIMEOUT_MS))
    # `thinking_level` is a Gemini 3.x feature: 3.x accepts "minimal" to cut
    # latency on short descriptions, but 2.x models (e.g. gemini-2.5-flash-lite)
    # reject it with `400 Thinking level is not supported for this model`. Apply
    # it only for 3.x; the numeric `thinking_budget` was deprecated per the 3.5
    # docs, so 2.x runs with the default thinking config.
    thinking_config = (
        types.ThinkingConfig(thinking_level="minimal")
        if _model_supports_thinking_level(model)
        else None
    )
    config = types.GenerateContentConfig(
        temperature=temperature,
        max_output_tokens=512,
        thinking_config=thinking_config,
    )

    # Retry with capped exponential backoff for 429 / 503 / timeout. Six
    # attempts (~2+4+8+16+30+30s) before propagating: a single 69k-parcel batch
    # would otherwise die on a SUSTAINED 503 spike (observed at peak hours) when
    # only 3 short retries were allowed. The cap keeps the backoff from exploding.
    max_attempts = 6
    base_delay = 2.0
    max_delay = 30.0
    last_exc: Exception | None = None
    for attempt in range(max_attempts):
        try:
            response = client.models.generate_content(
                model=model,
                contents=prompt,
                config=config,
            )
            return str(response.text or "").strip()
        except Exception as exc:  # pragma: no cover - depends on the API.
            message = str(exc)
            is_transient = (
                "429" in message
                or "503" in message
                or "rate limit" in message.lower()
                or "unavailable" in message.lower()
                or "timeout" in message.lower()
                or "timed out" in message.lower()
            )
            last_exc = exc
            if not is_transient or attempt == max_attempts - 1:
                raise
            delay = min(base_delay * (2**attempt), max_delay)
            logger.warning(
                "phenology_description_gemini_retry",
                attempt=attempt + 1,
                max_attempts=max_attempts,
                delay_s=delay,
                error=message[:200],
            )
            time.sleep(delay)
    # Only reachable if the loop exits due to exhaustion without raise (should not happen).
    raise RuntimeError(  # pragma: no cover
        f"Gemini exhausted all {max_attempts} retries."
    ) from last_exc


def _get_client() -> LlmClient:
    """Return the active client according to the order:

    1. Client injected via ``set_llm_client`` (tests always use it).
    2. Native ``google-genai`` client if the env var ``AGROSAT_LLM_PROVIDER``
       is ``"google-genai"`` or if ``google-genai`` is installed and no
       other is forced.
    3. LiteLLM fallback (provider-agnostic).
    """
    import os

    if _LLM_CLIENT is not None:
        return _LLM_CLIENT

    provider = os.environ.get("AGROSAT_LLM_PROVIDER", "").strip().lower()
    if provider == "google-genai":
        return _default_google_genai_client
    if provider == "litellm":
        return _default_litellm_client

    # Auto: prefer google-genai if available (faster); LiteLLM
    # as a transparent fallback.
    try:
        import google.genai  # noqa: F401

        return _default_google_genai_client
    except ImportError:
        return _default_litellm_client


# ---------------------------------------------------------------------------
# API publica.
# ---------------------------------------------------------------------------


def generate_phenology_description(
    ndvi_curve: np.ndarray,
    doy: np.ndarray | None = None,
    *,
    parcel_id: int | str | None = None,
    crop_type_hint: str | None = None,
    model: str = "gemini-3.5-flash",
    temperature: float = 0.0,
    cache_dir: Path | None = None,
) -> str:
    """Generate the textual phenology description of a parcel.

    Implements the 3-block prompt from Wen et al. (2025) Fig. 2:
    General + Time-Series Curve + Restrictive Instruction.

    Args:
        ndvi_curve: NDVI vector ``(T,)`` (interpolated daily curve or
            regular sampling). Accepts NaN; replaces them with the local
            mean before serializing.
        doy: Day-of-year vector ``(T,)`` (1..366). If ``None`` an
            equally spaced grid ``linspace(1, 365, T)`` is assumed.
        parcel_id: Used to name the cache file. If ``None`` the
            description is not cached (ad-hoc use).
        crop_type_hint: Optional hint ("trigo", "maiz", "viñedo", ...)
            that enters block 2 of the prompt.
        model: Model identifier (default ``"gemini-3.5-flash"``).
            LiteLLM routes to Vertex AI; other OpenAI-compatible values
            also work.
        temperature: Sampling temperature. **Default 0.0 mandatory**
            (determinism + R7 cost mitigation).
        cache_dir: Cache directory. If ``None`` uses
            :func:`default_cache_dir`. The cache keys by a hash of
            ``(parcel_id, ndvi_curve.tobytes(), prompt_template_version)``.

    Returns:
        Textual description (3-4 sentences) without line breaks.

    Raises:
        ValueError: if ``ndvi_curve`` is empty or has a non-1D shape, or
            if ``temperature`` is not 0.0 (R7: enforced to mitigate cost).
    """
    if ndvi_curve.ndim != 1:
        raise ValueError(f"`ndvi_curve` must be 1D; received shape {ndvi_curve.shape}.")
    if ndvi_curve.size == 0:
        raise ValueError("`ndvi_curve` cannot be empty.")
    if temperature != 0.0:
        raise ValueError("`temperature` must be 0.0 (R7 — determinism + Gemini cost).")

    if doy is None:
        doy = np.linspace(1.0, 365.0, ndvi_curve.size, dtype=np.float64)
    elif doy.shape != ndvi_curve.shape:
        raise ValueError(
            f"`doy` shape {doy.shape} does not match `ndvi_curve` shape {ndvi_curve.shape}."
        )

    # Impute NaN with the mean of the finite values (does not break the prompt).
    clean_curve = ndvi_curve.copy()
    if np.isnan(clean_curve).any():
        finite_mean = float(np.nanmean(clean_curve)) if np.any(~np.isnan(clean_curve)) else 0.0
        clean_curve = np.where(np.isnan(clean_curve), finite_mean, clean_curve)

    cache_dir_resolved = cache_dir if cache_dir is not None else default_cache_dir()
    cache_key = _hash_curve(parcel_id, clean_curve, model)
    cache_file = cache_dir_resolved / f"{cache_key}.json"
    if cache_file.exists():
        try:
            payload = json.loads(cache_file.read_text(encoding="utf-8"))
            description = str(payload["description"]).replace("\n", " ").strip()
            logger.info("phenology_description_cache_hit", parcel_id=parcel_id)
            return description
        except (OSError, KeyError, json.JSONDecodeError) as exc:
            logger.warning(
                "phenology_description_cache_unreadable",
                cache_file=str(cache_file),
                error=str(exc),
            )

    prompt = _build_prompt(clean_curve, doy, crop_type_hint=crop_type_hint)
    client = _get_client()
    raw = client(prompt, model=model, temperature=temperature)
    description = " ".join(raw.split())

    payload = {
        "parcel_id": parcel_id,
        "model": model,
        "temperature": temperature,
        "description": description,
        "crop_type_hint": crop_type_hint,
    }
    try:
        cache_file.parent.mkdir(parents=True, exist_ok=True)
        cache_file.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
    except OSError as exc:  # pragma: no cover
        logger.warning(
            "phenology_description_cache_write_failed",
            cache_file=str(cache_file),
            error=str(exc),
        )
    return description


def encode_descriptions(
    descriptions: Sequence[str],
    *,
    encoder: str = "sentence-transformers",
    model_name: str = DEFAULT_TEXT_ENCODER,
) -> np.ndarray:
    """Encode the descriptions into dense vectors.

    Args:
        descriptions: Sequence of texts to encode.
        encoder: ``"sentence-transformers"`` (default; already in deps) or
            ``"farslip-clip"`` (documented alternative; consumes the
            text-encoder of :class:`FarSLIPExtractor`, **not implemented
            here** — owned by US-017).
        model_name: sentence-transformers model identifier.

    Returns:
        ``(N, D)`` ``np.float32`` matrix. D = ``DEFAULT_TEXT_EMBED_DIM`` for
        the default model.

    Raises:
        NotImplementedError: if ``encoder == "farslip-clip"`` (TODO
        Paper Track / Phase 2 US-022-b).
        ValueError: if ``encoder`` is not one of the supported values.
    """
    if encoder == "farslip-clip":
        raise NotImplementedError(
            "encoder='farslip-clip' not yet implemented; "
            "remains a TODO for the Paper Track. Use 'sentence-transformers'."
        )
    if encoder != "sentence-transformers":
        raise ValueError(
            f"`encoder` must be 'sentence-transformers' or 'farslip-clip'; received {encoder!r}."
        )
    if not descriptions:
        return np.zeros((0, DEFAULT_TEXT_EMBED_DIM), dtype=np.float32)

    try:
        from sentence_transformers import SentenceTransformer
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "sentence-transformers is not installed. Run `poetry install --with ml`."
        ) from exc
    model = SentenceTransformer(model_name)
    embeddings = model.encode(
        list(descriptions),
        convert_to_numpy=True,
        normalize_embeddings=True,
        show_progress_bar=False,
    )
    return np.asarray(embeddings, dtype=np.float32)


def build_phenology_text_block(
    parcel_ndvi_frame: pl.DataFrame,
    *,
    ndvi_col_prefix: str = "NDVI_t_",
    parcel_id_col: str = "parcel_id",
    year_col: str = "year",
    crop_hint_col: str | None = None,
    model: str = "gemini-3.5-flash",
    encoder: str = "sentence-transformers",
    cache_dir: Path | None = None,
    max_parcels: int | None = None,
    seed: int = 42,
    skip_llm: bool = False,
    progress_every: int = 100,
) -> pl.DataFrame:
    """Build the ``pheno_text_*`` block ready for LEFT JOIN in ``fusion.py``.

    For each row of ``parcel_ndvi_frame``:
      1. Reconstructs the NDVI curve from ``{ndvi_col_prefix}{i:02d}`` columns
         (or FFT columns if the former do not exist — fallback symmetric
         to that of :class:`TemporalDataset`).
      2. Calls :func:`generate_phenology_description` (mockable in tests
         via :func:`set_llm_client`).
      3. Encodes all descriptions with :func:`encode_descriptions`.

    Args:
        parcel_ndvi_frame: DataFrame with at least ``parcel_id``, ``year`` and
            NDVI curve / FFT coefficients.
        ndvi_col_prefix: Prefix of the T-discrete columns (default
            ``"NDVI_t_"``).
        parcel_id_col: Name of the identifier column.
        year_col: Name of the year column.
        crop_hint_col: Optional column with the crop hint
            (string-like). If ``None`` it is omitted.
        model: LLM model (default ``"gemini-3.5-flash"``).
        encoder: Text-encoder (``"sentence-transformers"`` or
            ``"farslip-clip"``).
        cache_dir: Cache directory (default
            :func:`default_cache_dir`).
        max_parcels: Stratified subsample (D-5 of US-022b-D). ``None``
            = all rows (beware Gemini cost).
        seed: Subsample seed.
        skip_llm: If ``True`` skips the LLM call and generates zero
            embeddings — useful **only in tests**. For use in notebooks /
            pipelines the module raises ``DeprecationWarning`` and requires
            real credentials. The resulting block with ``skip_llm=True``
            has the correct shape but null content (zeros).
        progress_every: Frequency (every N processed parcels) at which a
            structured log is emitted with ``n_done``, ``n_total``,
            ``elapsed_s``, ``eta_s`` and ``est_cost_usd``. Default 100.

    Returns:
        ``pl.DataFrame`` with ``parcel_id``, ``year`` and
        ``pheno_text_000..pheno_text_{D-1}``.

    Raises:
        RuntimeError: if ``skip_llm=False``, there is no client injected via
            :func:`set_llm_client` and there are no Gemini credentials in
            the environment (``GEMINI_API_KEY`` / ``GOOGLE_API_KEY`` /
            ``GOOGLE_GENAI_USE_VERTEXAI``).
    """
    # Hard barrier: forbids running the LLM without credentials or a mocked
    # client. The `no silent mocks or skips` rule applies since
    # US-023-preview v2 (deliverable notebooks).
    if not skip_llm and _LLM_CLIENT is None and not _has_credentials():
        raise RuntimeError(
            "Gemini is not configured. Set GEMINI_API_KEY (or "
            "GOOGLE_API_KEY / GOOGLE_GENAI_USE_VERTEXAI=true + "
            "GOOGLE_CLOUD_PROJECT) in .env.local, or use skip_llm=True "
            "only for testing."
        )
    if skip_llm:
        warnings.warn(
            "build_phenology_text_block(skip_llm=True) genera embeddings "
            "de ceros. Usalo solo en tests: notebooks entregables deben "
            "ejecutar Gemini real.",
            DeprecationWarning,
            stacklevel=2,
        )

    df = parcel_ndvi_frame
    if max_parcels is not None and max_parcels > 0 and df.height > max_parcels:
        df = df.sample(n=max_parcels, seed=seed, with_replacement=False)
        logger.info("pheno_text_block_subsampled", n=df.height)

    parcel_ids = df.get_column(parcel_id_col).to_list()
    years = df.get_column(year_col).to_list() if year_col in df.columns else [None] * df.height
    crop_hints: list[str | None] = (
        df.get_column(crop_hint_col).to_list()
        if crop_hint_col is not None and crop_hint_col in df.columns
        else [None] * df.height
    )

    curves = _extract_ndvi_curves(df, prefix=ndvi_col_prefix)
    descriptions: list[str] = []
    if skip_llm:
        # Generate deterministic placeholder descriptions so the
        # encoder produces reproducible embeddings in CI without network.
        descriptions = [f"placeholder_pheno_{pid}" for pid in parcel_ids]
    else:
        n_total = len(parcel_ids)
        est_total_cost = n_total * COST_PER_DESCRIPTION_USD
        logger.info(
            "phenology_text_block_start",
            n_total=n_total,
            model=model,
            est_total_cost_usd=round(est_total_cost, 4),
        )
        t_start = time.monotonic()
        for idx, (pid, curve, hint) in enumerate(
            zip(parcel_ids, curves, crop_hints, strict=True), start=1
        ):
            descriptions.append(
                generate_phenology_description(
                    curve,
                    parcel_id=pid,
                    crop_type_hint=hint,
                    model=model,
                    temperature=0.0,
                    cache_dir=cache_dir,
                )
            )
            if idx % max(progress_every, 1) == 0 or idx == n_total:
                elapsed_s = time.monotonic() - t_start
                rate = idx / elapsed_s if elapsed_s > 0 else 0.0
                eta_s = (n_total - idx) / rate if rate > 0 else 0.0
                logger.info(
                    "phenology_text_block_progress",
                    n_done=idx,
                    n_total=n_total,
                    elapsed_s=round(elapsed_s, 2),
                    eta_s=round(eta_s, 2),
                    est_cost_usd=round(idx * COST_PER_DESCRIPTION_USD, 4),
                )

    if skip_llm:
        # In skip_llm we return zeros to avoid downloading the
        # sentence-transformers model (test without network or heavy dependencies).
        embeddings = np.zeros((len(descriptions), DEFAULT_TEXT_EMBED_DIM), dtype=np.float32)
    else:
        embeddings = encode_descriptions(descriptions, encoder=encoder)

    text_cols = [f"pheno_text_{i:03d}" for i in range(embeddings.shape[1])]
    block = {
        parcel_id_col: parcel_ids,
        year_col: years,
    }
    for j, col_name in enumerate(text_cols):
        block[col_name] = embeddings[:, j].tolist()
    schema: dict[str, pl.DataType] = {
        parcel_id_col: df.schema[parcel_id_col],
        year_col: df.schema.get(year_col, pl.Int16()),
    }
    for col_name in text_cols:
        schema[col_name] = pl.Float32()
    return pl.DataFrame(block, schema=schema)


# ---------------------------------------------------------------------------
# Helpers privados.
# ---------------------------------------------------------------------------


def _build_prompt(
    ndvi_curve: np.ndarray,
    doy: np.ndarray,
    *,
    crop_type_hint: str | None,
) -> str:
    """Build the complete Wen Fig. 2 prompt (3 blocks)."""
    # Prompt subsampling: if the curve is very long, we present up to
    # 24 uniformly spaced points (enough to capture the
    # seasonality and keeps the token count reasonable).
    max_points = 24
    if ndvi_curve.size > max_points:
        idx = np.linspace(0, ndvi_curve.size - 1, max_points, dtype=np.int64)
        curve_sub = ndvi_curve[idx]
        doy_sub = doy[idx]
    else:
        curve_sub = ndvi_curve
        doy_sub = doy

    serialization = ", ".join(
        f"(doy {int(d)}: {v:.3f})" for d, v in zip(doy_sub, curve_sub, strict=True)
    )
    peak_idx = int(np.argmax(ndvi_curve))
    peak_value = float(ndvi_curve[peak_idx])
    peak_doy = int(doy[peak_idx])
    sog_threshold = 0.3
    sog_indices = np.where(ndvi_curve >= sog_threshold)[0]
    sog_doy = int(doy[sog_indices[0]]) if sog_indices.size else -1
    post_peak_below = np.where(
        (np.arange(ndvi_curve.size) > peak_idx) & (ndvi_curve < sog_threshold)
    )[0]
    senescence_doy = int(doy[post_peak_below[0]]) if post_peak_below.size else -1

    return PROMPT_TEMPLATE.format(
        n_points=curve_sub.size,
        curve_serialization=serialization,
        peak_value=peak_value,
        peak_doy=peak_doy,
        sog_doy=sog_doy,
        senescence_doy=senescence_doy,
        crop_type_hint=crop_type_hint if crop_type_hint is not None else "(sin pista)",
    )


def _hash_curve(parcel_id: object, curve: np.ndarray, model: str) -> str:
    """Deterministic hash of the combination (parcel_id, curve, model, prompt_v1)."""
    h = hashlib.sha256()
    h.update(repr(parcel_id).encode("utf-8"))
    h.update(curve.astype(np.float32).tobytes())
    h.update(model.encode("utf-8"))
    h.update(b"prompt_v1")
    return h.hexdigest()[:16]


def _extract_ndvi_curves(df: pl.DataFrame, *, prefix: str) -> list[np.ndarray]:
    """Extract one curve per row from ``{prefix}{i:02d}`` columns.

    If those columns are not found, reconstructs from FFT (same helper as
    :class:`ml.train.phenology_models.TemporalDataset`).
    """
    candidate_cols = sorted(c for c in df.columns if c.startswith(prefix))
    if candidate_cols:
        matrix = df.select(candidate_cols).fill_null(0.0).to_numpy().astype(np.float32)
        return [matrix[i] for i in range(matrix.shape[0])]

    # Fallback: FFT reconstruction.
    from ml.train.phenology_models import _reconstruct_curve as _rc

    matrix = _rc(df, index_name="NDVI", sequence_length=72)
    return [matrix[i] for i in range(matrix.shape[0])]
