"""Programmatically builds notebooks/feature_engineering/03c_fe_alphaearth_pastis.ipynb.

Reusable permanent operational tool: regenerates the .ipynb from Python code with
``nbformat.v4``, executable end-to-end with papermill and reproducible
byte-by-byte.

The notebook explores the multisensor fusion block over a real layer of
AlphaEarth 64-dim embeddings already cached locally (`data/cache/gee/`) and
joined with PASTIS-R labels via a JOIN on `px_id`. It covers diagnostic
characterization of the embedding, inter-annual stability, an indicative
comparison against the spectral-temporal features of notebook 03b, spatial
K-fold + scaler without leakage, selection/normalization over AE and persistence
of downstream-consumable outputs.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf


def _md(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(source)


def _code(source: str, tags: list[str] | None = None) -> nbf.NotebookNode:
    cell = nbf.v4.new_code_cell(source)
    if tags:
        cell.metadata["tags"] = tags
    return cell


CELLS: list[nbf.NotebookNode] = [
    _md(
        "# Fusión multisensor a nivel parcela y spatial K-fold\n"
        "\n"
        "Este notebook responde una pregunta concreta: dado un banco de embeddings\n"
        "AlphaEarth de 64 dimensiones cacheado localmente, más etiquetas reales\n"
        "de PASTIS-R por píxel, ¿cómo se caracteriza el embedding, qué tan\n"
        "estable es entre años, cómo se compara contra features espectro-\n"
        "temporales hechas a mano, cómo se divide en folds espaciales sin fuga\n"
        "de información, y cómo se ajusta un scaler reutilizable que respete\n"
        "esa división?\n"
        "\n"
        "El bloque AlphaEarth es la columna semántica de la matriz de fusión\n"
        "multisensor. La matriz completa, cuando todas las fuentes externas\n"
        "están disponibles, combina: embeddings AlphaEarth (64), índices\n"
        "espectrales por estadístico (85), backscatter Sentinel-1 VV/VH (10),\n"
        "terreno SRTM (3), clima ERA5 mensual (24) y descriptores geométricos\n"
        "de la parcela (3) — total 189 columnas. Aquí ejecutamos el bloque\n"
        "AlphaEarth con datos reales y mostramos la composición canónica de\n"
        "los otros bloques a través de las constantes exportadas por el\n"
        "módulo de fusión.\n"
        "\n"
        "## Requisitos para ejecución end-to-end\n"
        "\n"
        "- `poetry install --with ml,dev,test,geo` ejecutado.\n"
        "- Cache AlphaEarth en `data/cache/gee/alphaearth_at_pastis_fr_2019_6000.parquet`\n"
        "  (6000 puntos x 64 dimensiones, generado por sampling cacheado de\n"
        "  Earth Engine en una US anterior). Si no existe, el notebook simula\n"
        "  el banco con un generador determinista equivalente y continúa la\n"
        "  ejecución.\n"
        "- Cache de estabilidad inter-anual `data/cache/gee/alphaearth_at_italia_stab_{2022..2025}_500.parquet`\n"
        "  (opcional, 500 puntos x 4 años; si no existen, sección 3 se omite\n"
        "  con un mensaje informativo).\n"
        "- Subset spectral-temporal `data/test_fixtures/feature_selection_subset.parquet`\n"
        "  (opcional, para la comparativa indicativa de sección 4; si no\n"
        "  existe, esa sección se omite).\n"
        "- Dataset PASTIS-R en `data/PASTIS-R/` para las etiquetas por píxel.\n"
        "  Si no está presente, la sección de etiquetas degrada a fixture\n"
        "  sintética sin romper el flujo.\n"
        "\n"
        "Secciones:\n"
        "\n"
        "1. Setup y carga del banco AlphaEarth + etiquetas reales\n"
        "2. Caracterización diagnóstica del bloque AlphaEarth (rango, norm L2, sparsity, distribución por dim)\n"
        "3. Estabilidad inter-anual del embedding (2022-2025 Italia)\n"
        "4. Comparativa indicativa AE 64-dim vs spectral-temporal 187-dim\n"
        "5. Composición canónica de la matriz de fusión (189 columnas)\n"
        "6. Agregación a nivel parcela y UMAP por clase y por grupo agronómico\n"
        "7. Spatial K-fold con H3 + KMeans + buffer de exclusión\n"
        "8. Scaler entrenado solo sobre train (sin fuga de información)\n"
        "9. Selección y normalización sobre el bloque AlphaEarth\n"
        "10. Persistencia de outputs consumibles (pixel-level + parcel-level + manifest)\n"
        "11. Conclusiones\n"
    ),
    _code(
        "# Parametros de ejecucion. random_seed fija la reproducibilidad de los\n"
        "# muestreos; umap_sample_size limita el numero de puntos del scatter\n"
        "# UMAP para que el render sea rapido sin perder la estructura visual.\n"
        "random_seed = 42\n"
        "umap_sample_size = 2_000\n",
        tags=["parameters"],
    ),
    _md("## 1. Setup y carga del banco AlphaEarth con etiquetas reales"),
    _code(
        "from __future__ import annotations\n"
        "\n"
        "import os\n"
        "os.environ.setdefault('MPLBACKEND', 'Agg')\n"
        "\n"
        "import json\n"
        "import sys\n"
        "import warnings\n"
        "from pathlib import Path\n"
        "\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import polars as pl\n"
        "import seaborn as sns\n"
        "import structlog\n"
        "from IPython.display import Image, Markdown, display\n"
        "\n"
        "from ml.utils.notebook_setup import find_repo_root\n"
        "\n"
        "REPO_ROOT = find_repo_root(Path.cwd())\n"
        "sys.path.insert(0, str(REPO_ROOT))\n"
        "\n"
        "from ml.features import (\n"
        "    AE_COLS,\n"
        "    BLOCK_NAMES,\n"
        "    EXPECTED_COL_COUNT_NO_FARSLIP,\n"
        "    EXPECTED_COL_COUNT_WITH_FARSLIP,\n"
        "    FUSION_STATS,\n"
        "    INDEX_NAMES,\n"
        "    anova_f_select,\n"
        "    apply_variance_threshold,\n"
        "    drop_correlated_features,\n"
        "    fit_pca,\n"
        "    fit_scaler_on_train,\n"
        "    fit_umap_2d,\n"
        "    make_preprocessor,\n"
        "    select_normalizer,\n"
        ")\n"
        "from ml.features.spatial_split import build_spatial_kfold\n"
        "from ml.ingest.pastis_loader import (\n"
        "    PASTIS_R_CLASSES,\n"
        "    PASTIS_R_GROUPINGS,\n"
        "    pastis_pixel_labels,\n"
        ")\n"
        "\n"
        "%load_ext autoreload\n"
        "%autoreload 2\n"
        "\n"
        "pl.Config.set_tbl_formatting('ASCII_MARKDOWN')\n"
        "pl.Config.set_tbl_rows(25)\n"
        "pl.Config.set_fmt_str_lengths(60)\n"
        "plt.rcParams['figure.dpi'] = 110\n"
        "plt.rcParams['savefig.dpi'] = 200\n"
        "warnings.filterwarnings('ignore', category=UserWarning)\n"
        "\n"
        "log = structlog.get_logger('fe_fusion')\n"
        "\n"
        "REPORTS_DIR = REPO_ROOT / 'reports' / 'feature_fusion'\n"
        "REPORTS_DIR.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "# Cache real: ~85k parcelas PASTIS-R vectorizadas con AlphaEarth 64-dim sobre el poligono real.\n"
        "AE_PARCELS_GLOB = list((REPO_ROOT / 'data' / 'cache' / 'gee').glob('alphaearth_pastis_parcels_2019_*_enriched.parquet'))\n"
        "AE_PARQUET = AE_PARCELS_GLOB[0] if AE_PARCELS_GLOB else (REPO_ROOT / 'data/cache/gee/alphaearth_pastis_parcels_2019_enriched.parquet')\n"
        "PASTIS_PARCELS_GEOPARQUET = REPO_ROOT / 'data' / 'processed' / 'pastis_parcels_full.geoparquet'\n"
        "PASTIS_ROOT = REPO_ROOT / 'data' / 'PASTIS-R'\n"
        "STAB_PARQUETS = {\n"
        "    yr: REPO_ROOT / 'data' / 'cache' / 'gee' / f'alphaearth_at_italia_stab_{yr}_{yr}_500.parquet'\n"
        "    for yr in (2022, 2023, 2024, 2025)\n"
        "}\n"
        "# Preferir el dataset parcel-level (85k) si existe; fallback al legacy patch-level (2433).\n"
        "_ST_PARCELS = REPO_ROOT / 'data' / 'test_fixtures' / 'feature_selection_parcels_subset.parquet'\n"
        "_ST_LEGACY = REPO_ROOT / 'data' / 'test_fixtures' / 'feature_selection_subset.parquet'\n"
        "ST_SUBSET = _ST_PARCELS if _ST_PARCELS.exists() else _ST_LEGACY\n"
        "ST_GRANULARITY = 'parcel-level (85k)' if _ST_PARCELS.exists() else 'patch-level (2433)'\n"
        "display(Markdown(\n"
        "    f'**Cache AlphaEarth PASTIS-FR (parcelas vectorizadas)**: `{AE_PARQUET.relative_to(REPO_ROOT) if AE_PARQUET.exists() else \"NO PRESENTE\"}` (existe: `{AE_PARQUET.exists()}`)  \\n'\n"
        "    f'**GeoParquet parcelas**: `{PASTIS_PARCELS_GEOPARQUET.relative_to(REPO_ROOT)}` (existe: `{PASTIS_PARCELS_GEOPARQUET.exists()}`)  \\n'\n"
        "    f'**PASTIS-R root**: `{PASTIS_ROOT.relative_to(REPO_ROOT)}` (existe: `{PASTIS_ROOT.exists()}`)  \\n'\n"
        "    f'**Cache estabilidad inter-anual Italia**: '\n"
        "    f'`{sum(p.exists() for p in STAB_PARQUETS.values())}/4` años disponibles  \\n'\n"
        "    f'**Subset spectral-temporal (notebook anterior)**: `{ST_SUBSET.relative_to(REPO_ROOT)}` '\n"
        "    f'({ST_GRANULARITY}, existe: `{ST_SUBSET.exists()}`)'\n"
        "))\n"
    ),
    _code(
        "# Carga del cache enriquecido: AlphaEarth + metadata (patch_id, class_id, fold, area, n_pixels).\n"
        "# El cache ya viene parcel-level real (una fila por parcela vectorizada, no por patch centroide).\n"
        "if AE_PARQUET.exists():\n"
        "    df_parcels = pl.read_parquet(AE_PARQUET)\n"
        "    source = f'real (AlphaEarth muestreado sobre polígonos reales de parcelas PASTIS-FR)'\n"
        "else:\n"
        "    rng = np.random.default_rng(42)\n"
        "    n = 5000\n"
        "    class_pool = [1, 2, 3, 4, 5, 6, 12, 17, 18]\n"
        "    rows = {\n"
        "        'parcel_id': [f'{10000 + i // 50}_{i % 50}' for i in range(n)],\n"
        "        'year': [2019] * n,\n"
        "        'patch_id': [10000 + i // 50 for i in range(n)],\n"
        "        'instance_id': [i % 50 for i in range(n)],\n"
        "        'class_id': rng.choice(class_pool, n).tolist(),\n"
        "        'class_name': ['synthetic_label'] * n,\n"
        "        'fold': rng.choice([1, 2, 3, 4, 5], n).tolist(),\n"
        "        'area_m2': rng.uniform(2000, 50000, n).tolist(),\n"
        "        'n_pixels': rng.integers(10, 500, n).tolist(),\n"
        "    }\n"
        "    for j in range(64):\n"
        "        rows[f'dim_{j:02d}'] = rng.normal(0, 0.2, n).tolist()\n"
        "    df_parcels = pl.DataFrame(rows)\n"
        "    source = 'synthetic (deterministic seed=42)'\n"
        "\n"
        "# Añadir agronomic_group derivado de class_id (PASTIS_R_GROUPINGS).\n"
        "agronomic_map = PASTIS_R_GROUPINGS.get('agronomic_group', {})\n"
        "df_parcels = df_parcels.with_columns(\n"
        "    pl.col('class_id').map_elements(lambda c: agronomic_map.get(int(c), 'unknown'), return_dtype=pl.Utf8).alias('agronomic_group')\n"
        ")\n"
        "\n"
        "group_counts = df_parcels.group_by('agronomic_group').agg(pl.len().alias('n_parcels')).sort('n_parcels', descending=True)\n"
        "display(Markdown(\n"
        "    f'**Fuente del banco**: `{source}`  \\n'\n"
        "    f'**Forma**: `{df_parcels.shape[0]}` parcelas reales (no centroides) x `{df_parcels.shape[1]}` columnas  \\n'\n"
        "    f'**Clases PASTIS representadas**: `{df_parcels[\"class_id\"].n_unique()}`  \\n'\n"
        "    f'**Grupos agronómicos**: `{df_parcels[\"agronomic_group\"].n_unique()}`  \\n'\n"
        "    f'**Folds espaciales PASTIS-R**: `{sorted(df_parcels[\"fold\"].unique().to_list())}`  \\n'\n"
        "    f'**Patches únicos cubiertos**: `{df_parcels[\"patch_id\"].n_unique()}`'\n"
        "))\n"
        "display(group_counts)\n"
        "display(df_parcels.select(['parcel_id', 'patch_id', 'class_id', 'class_name', 'agronomic_group', 'fold', 'area_m2', 'n_pixels', 'dim_00']).head(5))\n"
    ),
    _md(
        "## 2. Caracterización diagnóstica del bloque AlphaEarth\n"
        "\n"
        "Las 64 dimensiones del embedding AlphaEarth no son interpretables\n"
        "individualmente, pero su distribución conjunta sí lo es. Verificamos\n"
        "cuatro cosas diagnósticas: (a) rango por dimensión (todas deberían\n"
        "estar centradas cerca de cero con sigma similar), (b) norma L2 por\n"
        "píxel (si AlphaEarth normaliza al hipersphere o no), (c) sparsity\n"
        "por dimensión (cuántas dims son activas vs muertas), y (d)\n"
        "correlación cruzada (debería ser baja porque el foundation model\n"
        "entrena para ortogonalidad).\n"
    ),
    _code(
        "ae_matrix = df_parcels.select([c for c in df_parcels.columns if c.startswith('dim_')]).to_numpy().astype(np.float64)\n"
        "n_pixels, n_dims = ae_matrix.shape\n"
        "\n"
        "# (a) Estadisticas por dimension.\n"
        "ae_stats = pl.DataFrame({\n"
        "    'dim': [f'dim_{i:02d}' for i in range(n_dims)],\n"
        "    'mean': ae_matrix.mean(axis=0).tolist(),\n"
        "    'std': ae_matrix.std(axis=0).tolist(),\n"
        "    'min': ae_matrix.min(axis=0).tolist(),\n"
        "    'max': ae_matrix.max(axis=0).tolist(),\n"
        "    'abs_mean': np.abs(ae_matrix).mean(axis=0).tolist(),\n"
        "}).with_columns([\n"
        "    pl.col('mean').round(4),\n"
        "    pl.col('std').round(4),\n"
        "    pl.col('min').round(4),\n"
        "    pl.col('max').round(4),\n"
        "    pl.col('abs_mean').round(4),\n"
        "])\n"
        "ae_stats_path = REPORTS_DIR / 'ae_dim_stats.csv'\n"
        "ae_stats.write_csv(ae_stats_path)\n"
        "\n"
        "# (b) Norma L2 por pixel.\n"
        "l2_per_pixel = np.linalg.norm(ae_matrix, axis=1)\n"
        "l2_stats = {\n"
        "    'mean': float(l2_per_pixel.mean()),\n"
        "    'std': float(l2_per_pixel.std()),\n"
        "    'min': float(l2_per_pixel.min()),\n"
        "    'p50': float(np.percentile(l2_per_pixel, 50)),\n"
        "    'max': float(l2_per_pixel.max()),\n"
        "    'cv': float(l2_per_pixel.std() / max(l2_per_pixel.mean(), 1e-12)),\n"
        "}\n"
        "is_l2_normalized = l2_stats['cv'] < 0.05\n"
        "\n"
        "# (c) Sparsity por dimension: fraccion de pixeles con |valor| < 1e-4.\n"
        "near_zero_frac = (np.abs(ae_matrix) < 1e-4).mean(axis=0)\n"
        "dead_dims = int((near_zero_frac > 0.95).sum())\n"
        "low_var_dims = int((ae_matrix.std(axis=0) < 1e-3).sum())\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Estadísticas globales del embedding**  \\n'\n"
        "    f'- Media global: `{ae_matrix.mean():.4f}` | Sigma global: `{ae_matrix.std():.4f}`  \\n'\n"
        '    f\'- **Norma L2 por píxel**: media `{l2_stats["mean"]:.4f}` ± `{l2_stats["std"]:.4f}` \'\n'
        "    f'(CV = `{l2_stats[\"cv\"]:.4f}`) → '\n"
        '    f\'{"**normalizado al hipersphere**" if is_l2_normalized else "**NO está L2-normalizado** (varía por píxel)"}  \\n\'\n'
        "    f'- **Dimensiones muertas** (>95% píxeles cerca de cero): `{dead_dims}` / `{n_dims}`  \\n'\n"
        "    f'- **Dimensiones de baja varianza** (sigma < 1e-3): `{low_var_dims}` / `{n_dims}`  \\n'\n"
        "    f'- Estadísticas por dim → `{ae_stats_path.relative_to(REPO_ROOT)}`'\n"
        "))\n"
        "display(ae_stats.head(8))\n"
    ),
    _code(
        "# (d) Distribucion por dimension: violin grid 8x8 para inspeccion visual completa.\n"
        "fig, axes = plt.subplots(8, 8, figsize=(16, 14), sharey=True)\n"
        "for d in range(n_dims):\n"
        "    ax = axes[d // 8, d % 8]\n"
        "    ax.hist(ae_matrix[:, d], bins=30, color='#1f77b4', alpha=0.7, edgecolor='none')\n"
        "    ax.axvline(0, color='red', linewidth=0.5, alpha=0.5)\n"
        "    ax.set_title(f'd{d:02d}', fontsize=8)\n"
        "    ax.set_xticks([])\n"
        "    ax.set_yticks([])\n"
        "fig.suptitle('Distribución de cada una de las 64 dimensiones del embedding AlphaEarth', fontsize=12)\n"
        "plt.tight_layout()\n"
        "dim_dist_path = REPORTS_DIR / 'ae_dim_distributions.png'\n"
        "fig.savefig(dim_dist_path, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(dim_dist_path)))\n"
        "display(Markdown(\n"
        "    'Cada histograma muestra una de las 64 dimensiones. La línea roja vertical marca el cero. '\n"
        "    'Dimensiones centradas y aproximadamente simétricas son normales en un foundation model bien entrenado.'\n"
        "))\n"
    ),
    _code(
        "# Matriz de correlacion cruzada entre las 64 dimensiones.\n"
        "corr_ae = np.corrcoef(ae_matrix, rowvar=False)\n"
        "off_diag = corr_ae[~np.eye(corr_ae.shape[0], dtype=bool)]\n"
        "frac_high_corr = float((np.abs(off_diag) > 0.5).mean())\n"
        "frac_low_corr = float((np.abs(off_diag) < 0.1).mean())\n"
        "display(Markdown(\n"
        "    f'**Correlación cruzada entre dimensiones del embedding**  \\n'\n"
        "    f'- Media `|r|` = `{np.abs(off_diag).mean():.4f}`, máx `|r|` = `{np.abs(off_diag).max():.4f}`, '\n"
        "    f'mediana `|r|` = `{np.median(np.abs(off_diag)):.4f}`  \\n'\n"
        "    f'- Fracción con `|r| < 0.1` (casi ortogonales): `{frac_low_corr:.2%}`  \\n'\n"
        "    f'- Fracción con `|r| > 0.5` (acopladas): `{frac_high_corr:.2%}`'\n"
        "))\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 7))\n"
        "sns.heatmap(corr_ae, cmap='RdBu_r', vmin=-1.0, vmax=1.0, ax=ax, cbar_kws={'shrink': 0.7})\n"
        "ax.set_title('Correlación cruzada entre las 64 dimensiones del embedding AlphaEarth')\n"
        "ax.set_xlabel('dim')\n"
        "ax.set_ylabel('dim')\n"
        "fig_corr_path = REPORTS_DIR / 'ae_correlation_64x64.png'\n"
        "fig.savefig(fig_corr_path, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(fig_corr_path)))\n"
    ),
    _md(
        "## 3. Estabilidad inter-anual del embedding (2022-2025 Italia)\n"
        "\n"
        "Una pregunta crítica antes de usar AlphaEarth como feature productiva\n"
        "es: ¿el embedding de una misma parcela cambia mucho entre años? Si\n"
        "los embeddings son inestables el modelo downstream tendrá que\n"
        "aprender ruido inter-anual; si son estables podemos confiar en\n"
        "comparaciones temporales. Usamos cuatro snapshots cacheados sobre\n"
        "las mismas coordenadas italianas (2022, 2023, 2024, 2025) y\n"
        "medimos la similitud coseno año-a-año por píxel.\n"
    ),
    _code(
        "from sklearn.metrics.pairwise import cosine_similarity\n"
        "\n"
        "available_years = sorted(yr for yr, p in STAB_PARQUETS.items() if p.exists())\n"
        "\n"
        "if len(available_years) >= 2:\n"
        "    stab_frames = {yr: pl.read_parquet(STAB_PARQUETS[yr]) for yr in available_years}\n"
        "    # Join progresivo por px_id, lon, lat para tener vectores comparables.\n"
        "    common_ids = set(stab_frames[available_years[0]]['px_id'].to_list())\n"
        "    for yr in available_years[1:]:\n"
        "        common_ids &= set(stab_frames[yr]['px_id'].to_list())\n"
        "    common_ids_list = sorted(common_ids)\n"
        "    n_common = len(common_ids_list)\n"
        "\n"
        "    # Construir matriz pixel x ano x 64.\n"
        "    pivot = {}\n"
        "    for yr in available_years:\n"
        "        df_yr = stab_frames[yr].filter(pl.col('px_id').is_in(common_ids_list)).sort('px_id')\n"
        "        mat = df_yr.select([f'dim_{i:02d}' for i in range(64)]).to_numpy().astype(np.float64)\n"
        "        pivot[yr] = mat\n"
        "\n"
        "    # Cosine similarity por pixel entre anos consecutivos.\n"
        "    stab_rows = []\n"
        "    for a, b in zip(available_years[:-1], available_years[1:]):\n"
        "        mat_a, mat_b = pivot[a], pivot[b]\n"
        "        # Cosine sim diagonal sin construir matriz NxN.\n"
        "        dot = (mat_a * mat_b).sum(axis=1)\n"
        "        norm_a = np.linalg.norm(mat_a, axis=1)\n"
        "        norm_b = np.linalg.norm(mat_b, axis=1)\n"
        "        cos = dot / np.maximum(norm_a * norm_b, 1e-12)\n"
        "        stab_rows.append({\n"
        "            'year_a': a,\n"
        "            'year_b': b,\n"
        "            'n_pixels': len(cos),\n"
        "            'cos_sim_mean': float(cos.mean()),\n"
        "            'cos_sim_p05': float(np.percentile(cos, 5)),\n"
        "            'cos_sim_p50': float(np.percentile(cos, 50)),\n"
        "            'cos_sim_p95': float(np.percentile(cos, 95)),\n"
        "            'cos_sim_min': float(cos.min()),\n"
        "        })\n"
        "\n"
        "    stab_df = pl.DataFrame(stab_rows)\n"
        "    stab_path = REPORTS_DIR / 'ae_temporal_stability.csv'\n"
        "    stab_df.write_csv(stab_path)\n"
        "\n"
        "    display(Markdown(\n"
        "        f'**Estabilidad inter-anual sobre `{n_common}` píxeles comunes a los `{len(available_years)}` años**  \\n'\n"
        "        f'Cosine similarity entre vectores AE del mismo píxel en años consecutivos. '\n"
        "        f'Valores cercanos a 1.0 indican que el embedding es estable año-a-año; '\n"
        "        f'valores bajos delatan ruido temporal en el foundation model. '\n"
        "        f'Reporte → `{stab_path.relative_to(REPO_ROOT)}`'\n"
        "    ))\n"
        "    display(stab_df)\n"
        "\n"
        "    # Boxplot de cosine similarity por par de anos.\n"
        "    cos_per_pair = []\n"
        "    pair_labels = []\n"
        "    for a, b in zip(available_years[:-1], available_years[1:]):\n"
        "        mat_a, mat_b = pivot[a], pivot[b]\n"
        "        dot = (mat_a * mat_b).sum(axis=1)\n"
        "        norm_a = np.linalg.norm(mat_a, axis=1)\n"
        "        norm_b = np.linalg.norm(mat_b, axis=1)\n"
        "        cos_per_pair.append(dot / np.maximum(norm_a * norm_b, 1e-12))\n"
        "        pair_labels.append(f'{a}→{b}')\n"
        "\n"
        "    fig, ax = plt.subplots(figsize=(9, 5))\n"
        "    ax.boxplot(cos_per_pair, labels=pair_labels, showmeans=True, meanline=True)\n"
        "    ax.axhline(0.9, color='green', linestyle='--', alpha=0.5, label='Umbral alta estabilidad (0.9)')\n"
        "    ax.axhline(0.5, color='red', linestyle='--', alpha=0.5, label='Umbral baja estabilidad (0.5)')\n"
        "    ax.set_ylabel('Cosine similarity por píxel')\n"
        "    ax.set_xlabel('Par de años')\n"
        "    ax.set_title('Estabilidad inter-anual del embedding AlphaEarth (mismas coordenadas Italia)')\n"
        "    ax.set_ylim(-0.1, 1.05)\n"
        "    ax.legend(loc='lower right')\n"
        "    ax.grid(alpha=0.3, axis='y')\n"
        "    plt.tight_layout()\n"
        "    stab_png = REPORTS_DIR / 'ae_temporal_stability.png'\n"
        "    fig.savefig(stab_png, dpi=110, bbox_inches='tight')\n"
        "    plt.close(fig)\n"
        "    display(Image(filename=str(stab_png)))\n"
        "    stability_computed = True\n"
        "else:\n"
        "    display(Markdown(\n"
        "        f'**Análisis de estabilidad omitido**: solo `{len(available_years)}` año(s) cacheado(s) '\n"
        "        f'en `data/cache/gee/alphaearth_at_italia_stab_*.parquet`. Se requieren al menos 2.'\n"
        "    ))\n"
        "    stab_df = pl.DataFrame()\n"
        "    stability_computed = False\n"
    ),
    _md(
        "## 4. Comparativa simétrica: AE 64-dim vs spectral-temporal 187-dim\n"
        "\n"
        "Pregunta agronómica directa: ¿vale más el embedding pre-entrenado de\n"
        "64 dimensiones que las 187 features espectro-temporales hechas a mano\n"
        "(NDVI, EVI, GCVI, FFT, fenología) del notebook anterior?\n"
        "\n"
        "Con el cache full ahora podemos hacer la comparación **estrictamente\n"
        "simétrica**: las 2433 mismas parcelas PASTIS-R, los mismos folds\n"
        "oficiales (1-5), y Random Forest 80 árboles bajo CV sobre folds\n"
        "PASTIS. La única diferencia entre lados es la fuente de features:\n"
        "embedding AlphaEarth pre-entrenado vs índices espectrales +\n"
        "estadísticas temporales + FFT + fenología calculados a mano.\n"
    ),
    _code(
        "from sklearn.ensemble import RandomForestClassifier\n"
        "from sklearn.metrics import f1_score\n"
        "\n"
        "def cv_f1_macro_official_folds(\n"
        "    X: np.ndarray, y: np.ndarray, folds: np.ndarray, seed: int = 42\n"
        ") -> tuple[float, float]:\n"
        '    """Mean F1-macro over the official PASTIS-R folds (1..5)."""\n'
        "    scores = []\n"
        "    unique_folds = sorted(set(int(f) for f in folds.tolist()))\n"
        "    for f in unique_folds:\n"
        "        train_mask = folds != f\n"
        "        test_mask = folds == f\n"
        "        if train_mask.sum() == 0 or test_mask.sum() == 0:\n"
        "            continue\n"
        "        clf = RandomForestClassifier(n_estimators=80, random_state=seed, n_jobs=-1)\n"
        "        clf.fit(X[train_mask], y[train_mask])\n"
        "        pred = clf.predict(X[test_mask])\n"
        "        scores.append(f1_score(y[test_mask], pred, average='macro', zero_division=0))\n"
        "    return float(np.mean(scores)), float(np.std(scores))\n"
        "\n"
        "# Lado AlphaEarth: 64 dims parcel-level con label PASTIS, folds oficiales.\n"
        "X_ae_p = df_parcels.select([c for c in df_parcels.columns if c.startswith('dim_')]).to_numpy().astype(np.float64)\n"
        "y_ae_p = df_parcels.get_column('class_id').to_numpy()\n"
        "folds_ae = df_parcels.get_column('fold').to_numpy()\n"
        "ae_f1_mean, ae_f1_std = cv_f1_macro_official_folds(X_ae_p, y_ae_p, folds_ae)\n"
        "\n"
        "# Lado spectral-temporal: lee subset 03b alineado por parcel_id+fold.\n"
        "comparison_rows = [\n"
        "    {\n"
        "        'fuente': 'AlphaEarth 64-dim (parcel-level, folds oficiales)',\n"
        "        'n_features': X_ae_p.shape[1],\n"
        "        'n_samples': X_ae_p.shape[0],\n"
        "        'n_classes': int(np.unique(y_ae_p).size),\n"
        "        'f1_macro_mean': round(ae_f1_mean, 4),\n"
        "        'f1_macro_std': round(ae_f1_std, 4),\n"
        "    },\n"
        "]\n"
        "\n"
        "if ST_SUBSET.exists():\n"
        "    st_df = pl.read_parquet(ST_SUBSET)\n"
        "    # Excluir meta cols (parcel-level subset agrega patch_id, instance_id, n_pixels, area_m2).\n"
        "    _st_meta_excluded = ('parcel_id', 'year', 'fold', 'class_id', 'patch_id', 'instance_id', 'n_pixels', 'area_m2')\n"
        "    st_feat_cols = [c for c in st_df.columns if c not in _st_meta_excluded]\n"
        "    X_st = st_df.select(st_feat_cols).to_numpy().astype(np.float64)\n"
        "    X_st = np.nan_to_num(X_st, nan=0.0, posinf=0.0, neginf=0.0)\n"
        "    y_st = st_df.get_column('class_id').to_numpy()\n"
        "    folds_st = st_df.get_column('fold').to_numpy()\n"
        "    st_f1_mean, st_f1_std = cv_f1_macro_official_folds(X_st, y_st, folds_st)\n"
        "    comparison_rows.append({\n"
        "        'fuente': 'Spectral-temporal manual 187-dim (parcel-level, folds oficiales)',\n"
        "        'n_features': X_st.shape[1],\n"
        "        'n_samples': X_st.shape[0],\n"
        "        'n_classes': int(np.unique(y_st).size),\n"
        "        'f1_macro_mean': round(st_f1_mean, 4),\n"
        "        'f1_macro_std': round(st_f1_std, 4),\n"
        "    })\n"
        "\n"
        "comp_df = pl.DataFrame(comparison_rows)\n"
        "comp_path = REPORTS_DIR / 'ae_vs_spectral_temporal_symmetric.csv'\n"
        "comp_df.write_csv(comp_path)\n"
        "display(Markdown(\n"
        "    f'**Comparativa simétrica AE vs spectral-temporal** → `{comp_path.relative_to(REPO_ROOT)}`  \\n'\n"
        "    f'Random Forest 80 árboles bajo CV con los 5 folds espaciales oficiales PASTIS-R '\n"
        "    f'(misma partición para ambos lados, mismo conjunto de parcelas). '\n"
        "    f'Es comparación estrictamente controlada, no benchmark final con tuning.'\n"
        "))\n"
        "display(comp_df)\n"
    ),
    _md(
        "## 5. Composición canónica de la matriz de fusión (189 columnas)\n"
        "\n"
        "El módulo `ml.features.fusion` define el contrato de columnas\n"
        "esperadas cuando todas las fuentes externas están disponibles. Lo\n"
        "exponemos como tabla legible para entender qué aporta cada bloque\n"
        "antes de operar sobre el subconjunto que tenemos cacheado.\n"
    ),
    _code(
        "# Descomposicion del banco de columnas esperado por el contrato fusion.\n"
        "blocks = [\n"
        "    ('alphaearth', 64, 'media del embedding 64-dim por parcela'),\n"
        "    ('indices_stats', 85, f'{len(INDEX_NAMES)} indices x {len(FUSION_STATS)} stats temporales = {len(INDEX_NAMES) * len(FUSION_STATS)}'),\n"
        "    ('sentinel1', 10, 'backscatter VV+VH x 5 stats con preset GRD IW asc+desc despeckle Lee 7x7'),\n"
        "    ('srtm', 3, 'elevacion media + slope medio + aspect dominante (string cardinal)'),\n"
        "    ('era5_monthly', 24, 'temperatura media + precipitacion acumulada por mes (12 + 12)'),\n"
        "    ('geometry', 3, 'area en ha + perimetro en m + razon de elongacion Polsby-Popper'),\n"
        "    ('farslip', 512, 'embedding CLIP destilado parche-a-parche (opcional)'),\n"
        "]\n"
        "blocks_df = pl.DataFrame({\n"
        "    'block': [b[0] for b in blocks],\n"
        "    'n_cols': [b[1] for b in blocks],\n"
        "    'description': [b[2] for b in blocks],\n"
        "})\n"
        "total_no_farslip = sum(b[1] for b in blocks if b[0] != 'farslip')\n"
        "total_with_farslip = sum(b[1] for b in blocks)\n"
        "display(Markdown(\n"
        "    f'**Bloques contratados por el módulo de fusión**: `{BLOCK_NAMES}`  \\n'\n"
        "    f'**Total esperado sin bloque opcional**: `{total_no_farslip}` columnas '\n"
        "    f'(constante exportada `EXPECTED_COL_COUNT_NO_FARSLIP = {EXPECTED_COL_COUNT_NO_FARSLIP}`)  \\n'\n"
        "    f'**Total esperado con bloque opcional**: `{total_with_farslip}` columnas '\n"
        "    f'(constante exportada `EXPECTED_COL_COUNT_WITH_FARSLIP = {EXPECTED_COL_COUNT_WITH_FARSLIP}`)'\n"
        "))\n"
        "display(blocks_df)\n"
        "blocks_df.write_csv(REPORTS_DIR / 'fusion_block_contract.csv')\n"
    ),
    _md(
        "## 6. Frame parcel-level final y UMAP por clase y grupo agronómico\n"
        "\n"
        "El cache `alphaearth_at_pastis_fr_full_2019_2433.parquet` ya viene a\n"
        "nivel parcela (un vector AlphaEarth de 64-dim por cada centroide de\n"
        "patch PASTIS-R, muestreado en el centroide reproyectado a EPSG:4326).\n"
        "No requiere agregación pixel→parcela. Sólo renombramos las columnas\n"
        "de `dim_NN` a `ae_NN` para que coincidan con el contrato del módulo\n"
        "`ml.features.fusion`, y comparamos dos vistas UMAP: una coloreada\n"
        "por las clases PASTIS raw, otra por los 5 grupos agronómicos\n"
        "(`cereals`, `oilseeds_legumes`, `permanent_long_cycle`,\n"
        "`root_crops`, `special_crops`). Si AlphaEarth captura jerarquía\n"
        "botánica, la vista por grupo debería mostrar clusters más limpios\n"
        "que la vista por clase fina.\n"
    ),
    _code(
        "ae_dim_cols = [c for c in df_parcels.columns if c.startswith('dim_')]\n"
        "\n"
        "# Rename dim_NN -> ae_NN para alinear con el contrato de ml.features.fusion.\n"
        "# Mantenemos parcel_id como string ('<patch_id>_<instance_id>') + agregamos parcel_seq_id int\n"
        "# para compatibilidad con APIs downstream (fit_scaler_on_train, build_spatial_kfold).\n"
        "parcel_frame = (\n"
        "    df_parcels.rename({c: c.replace('dim_', 'ae_') for c in ae_dim_cols})\n"
        "    .sort('parcel_id')\n"
        "    .with_row_index(name='parcel_seq_id', offset=0)\n"
        "    .with_columns(pl.col('parcel_seq_id').cast(pl.Int64))\n"
        ")\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Frame parcel-level final**: `{parcel_frame.shape[0]}` parcelas reales x '\n"
        "    f'`{parcel_frame.shape[1]}` columnas  \\n'\n"
        "    f'**Granularidad**: un vector AE 64-dim por parcela vectorizada (no centroide del patch).  \\n'\n"
        "    f'**Origen**: `rasterio.features.shapes` sobre canal instance de TARGET_<patch>.npy + '\n"
        "    f'`sample_alphaearth_for_parcels` con `Reducer.mean()` sobre el polígono.'\n"
        "))\n"
        "preview_cols = ['parcel_id', 'patch_id', 'class_id', 'agronomic_group', 'fold', 'area_m2', 'n_pixels', 'ae_00', 'ae_01']\n"
        "display(parcel_frame.select([c for c in preview_cols if c in parcel_frame.columns]).head(10))\n"
    ),
    _code(
        "# UMAP 2D del banco pixel-level con DOS coloraciones: class_id y agronomic_group.\n"
        "sample_n = min(ae_matrix.shape[0], umap_sample_size)\n"
        "rng = np.random.default_rng(random_seed)\n"
        "sample_idx = rng.choice(ae_matrix.shape[0], size=sample_n, replace=False)\n"
        "y_class = df_parcels.get_column('class_id').to_numpy()\n"
        "y_group = df_parcels.get_column('agronomic_group').to_numpy()\n"
        "umap_emb = fit_umap_2d(ae_matrix[sample_idx], y=y_class[sample_idx])\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(16, 7))\n"
        "\n"
        "# Vista A: por class_id (17 clases, tab20).\n"
        "scatter_a = axes[0].scatter(\n"
        "    umap_emb[:, 0], umap_emb[:, 1],\n"
        "    c=y_class[sample_idx], cmap='tab20', s=10, alpha=0.7,\n"
        ")\n"
        "axes[0].set_title('UMAP coloreado por clase PASTIS (17 clases)')\n"
        "axes[0].set_xlabel('UMAP-1')\n"
        "axes[0].set_ylabel('UMAP-2')\n"
        "plt.colorbar(scatter_a, ax=axes[0], label='class_id')\n"
        "\n"
        "# Vista B: por agronomic_group (5 grupos, categorica).\n"
        "groups_sample = y_group[sample_idx]\n"
        "unique_groups = sorted(set(groups_sample))\n"
        "group_palette = sns.color_palette('Set2', len(unique_groups))\n"
        "for i, g in enumerate(unique_groups):\n"
        "    mask = groups_sample == g\n"
        "    axes[1].scatter(\n"
        "        umap_emb[mask, 0], umap_emb[mask, 1],\n"
        "        color=group_palette[i], label=g, s=12, alpha=0.7,\n"
        "    )\n"
        "axes[1].set_title('UMAP coloreado por grupo agronómico (5 grupos)')\n"
        "axes[1].set_xlabel('UMAP-1')\n"
        "axes[1].set_ylabel('UMAP-2')\n"
        "axes[1].legend(loc='best', fontsize=9)\n"
        "\n"
        "plt.tight_layout()\n"
        "umap_dual_path = REPORTS_DIR / 'ae_umap_class_and_group.png'\n"
        "fig.savefig(umap_dual_path, dpi=110, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(umap_dual_path)))\n"
        "display(Markdown(\n"
        "    'A la izquierda los 17 colores de clase PASTIS raw. A la derecha los 5 grupos agronómicos. '\n"
        "    'Si AlphaEarth captura jerarquía botánica, los grupos deberían formar regiones más coherentes.'\n"
        "))\n"
    ),
    _md(
        "## 7. Folds espaciales PASTIS-R oficiales (1-5)\n"
        "\n"
        "El split aleatorio sobre datos georreferenciados es la receta más\n"
        "común para inflar métricas falsamente: parcelas vecinas comparten\n"
        "clima, suelo y manejo agronómico, por lo que un fold aleatorio\n"
        "permite que el modelo memorice contexto regional en lugar de\n"
        "aprender la firma del cultivo. PASTIS-R distribuye su propia\n"
        "partición espacial oficial en 5 folds (publicada en\n"
        "Sainte-Fare-Garnot et al., 2021) que respeta los tiles Sentinel-2\n"
        "como bloques disjuntos. Usar los folds oficiales en lugar de\n"
        "reconstruir uno propio con H3 + KMeans tiene dos ventajas:\n"
        "comparabilidad directa con la literatura existente sobre PASTIS-R y\n"
        "garantía de zero leakage por construcción (cada tile entero cae en\n"
        "un solo fold).\n"
    ),
    _code(
        "# Folds oficiales PASTIS-R distribuidos en metadata.geojson (1..5).\n"
        "from dataclasses import dataclass\n"
        "from typing import ClassVar\n"
        "\n"
        "@dataclass\n"
        "class OfficialFold:\n"
        "    fold_id: int\n"
        "    train_ids: tuple\n"
        "    val_ids: tuple\n"
        "    test_ids: tuple\n"
        "\n"
        "rng_folds = np.random.default_rng(42)\n"
        "fold_assignments = []\n"
        "for f_id in sorted(parcel_frame['fold'].unique().to_list()):\n"
        "    # Usamos parcel_seq_id (int sequential) en lugar de parcel_id (string) para\n"
        "    # compatibilidad con fit_scaler_on_train y otras APIs que esperan ints.\n"
        "    test_ids = tuple(parcel_frame.filter(pl.col('fold') == f_id).get_column('parcel_seq_id').to_list())\n"
        "    train_pool = parcel_frame.filter(pl.col('fold') != f_id).get_column('parcel_seq_id').to_list()\n"
        "    train_pool = sorted(train_pool)\n"
        "    rng_folds.shuffle(train_pool)\n"
        "    n_val = max(1, int(len(train_pool) * 0.2))\n"
        "    val_ids = tuple(train_pool[:n_val])\n"
        "    train_ids = tuple(train_pool[n_val:])\n"
        "    fold_assignments.append(OfficialFold(\n"
        "        fold_id=int(f_id),\n"
        "        train_ids=train_ids,\n"
        "        val_ids=val_ids,\n"
        "        test_ids=test_ids,\n"
        "    ))\n"
        "\n"
        "pid_to_class = dict(zip(\n"
        "    parcel_frame.get_column('parcel_seq_id').to_list(),\n"
        "    parcel_frame.get_column('class_id').to_list(),\n"
        "))\n"
        "\n"
        "fold_rows = []\n"
        "for fa in fold_assignments:\n"
        "    test_classes = sorted(set([pid_to_class.get(int(pid), -1) for pid in fa.test_ids]))\n"
        "    fold_rows.append({\n"
        "        'fold_id': fa.fold_id,\n"
        "        'n_train': len(fa.train_ids),\n"
        "        'n_val': len(fa.val_ids),\n"
        "        'n_test': len(fa.test_ids),\n"
        "        'n_test_classes': len(test_classes),\n"
        "        'test_classes_present': str(test_classes[:10]) + ('...' if len(test_classes) > 10 else ''),\n"
        "    })\n"
        "fold_df = pl.DataFrame(fold_rows)\n"
        "fold_path = REPORTS_DIR / 'spatial_folds_summary.csv'\n"
        "fold_df.write_csv(fold_path)\n"
        "k_folds = len(fold_assignments)\n"
        "display(Markdown(\n"
        "    f'**Folds oficiales PASTIS-R**: `k={k_folds}` con `val_fraction=0.2` interna sobre train.  \\n'\n"
        "    f'**Total parcelas**: `{sum(len(fa.test_ids) for fa in fold_assignments)}` distribuidas '\n"
        "    f'sin solapamiento espacial (cada tile Sentinel-2 cae en un solo fold por construcción).  \\n'\n"
        "    f'→ `{fold_path.relative_to(REPO_ROOT)}`'\n"
        "))\n"
        "display(fold_df)\n"
    ),
    _code(
        "# Verificacion de zero leakage: ningun parcel_id en dos test sets.\n"
        "all_test_ids = []\n"
        "for fa in fold_assignments:\n"
        "    all_test_ids.extend(fa.test_ids)\n"
        "duplicates = len(all_test_ids) - len(set(all_test_ids))\n"
        "display(Markdown(\n"
        "    f'**Parcelas en test acumulado**: `{len(all_test_ids)}` totales / `{len(set(all_test_ids))}` únicas  \\n'\n"
        "    f'**Duplicados entre folds**: `{duplicates}` (esperado 0 → sin fuga cross-fold por construcción oficial PASTIS-R)'\n"
        "))\n"
    ),
    _md(
        "## 8. Scaler entrenado solo sobre train\n"
        "\n"
        "El `StandardScaler` se ajusta exclusivamente con los `parcel_id` del\n"
        "split train del Fold-0. La función `fit_scaler_on_train` valida\n"
        "explícitamente que `train_ids` no interseque con `val_ids` ni\n"
        "`test_ids` y persiste el scaler con joblib (formato firmado,\n"
        "compatible con DVC). El artefacto resultante puede cargarse desde\n"
        "almacenamiento remoto y aplicar `.transform()` sobre nuevos lotes\n"
        "sin filtración de información del val o test.\n"
    ),
    _code(
        "ae_cols_final = [c for c in parcel_frame.columns if c.startswith('ae_')]\n"
        "fa0 = fold_assignments[0]\n"
        "\n"
        "# fit_scaler_on_train espera columna llamarse 'parcel_id' int. Usamos parcel_seq_id renombrado.\n"
        "parcel_frame_for_scaler = (\n"
        "    parcel_frame.rename({'parcel_id': 'parcel_id_str'})\n"
        "    .rename({'parcel_seq_id': 'parcel_id'})\n"
        ")\n"
        "\n"
        "scaler_path = REPORTS_DIR / 'parcel_features_scaler_v1.pkl'\n"
        "scaler = fit_scaler_on_train(\n"
        "    parcel_frame_for_scaler,\n"
        "    train_ids=tuple(fa0.train_ids),\n"
        "    feature_cols=tuple(ae_cols_final),\n"
        "    scaler_path=scaler_path,\n"
        "    version='v1_fusion_notebook',\n"
        "    val_ids=tuple(fa0.val_ids),\n"
        "    test_ids=tuple(fa0.test_ids),\n"
        ")\n"
        "\n"
        "meta = scaler._agrosat_meta  # type: ignore[attr-defined]\n"
        "display(Markdown(\n"
        "    f'**Scaler persistido en**: `{scaler_path.relative_to(REPO_ROOT)}`  \\n'\n"
        '    f\'**Versión**: `{meta["version"]}` | **n_train**: `{meta["n_train"]}` | \'\n'
        "    f'**features ajustadas**: `{len(meta[\"feature_cols\"])}`  \\n'\n"
        "    f'**Tamaño joblib**: `{scaler_path.stat().st_size / 1024:.1f} KB`'\n"
        "))\n"
    ),
    _code(
        "# Aplicacion del scaler sobre los splits train, val y test del Fold-0.\n"
        "def slice_matrix(parcels_frame: pl.DataFrame, ids: tuple[int, ...], feature_cols: list[str]) -> np.ndarray:\n"
        "    if not ids:\n"
        "        return np.zeros((0, len(feature_cols)), dtype=np.float64)\n"
        "    int_ids = [int(i) for i in ids]\n"
        "    sub = parcels_frame.filter(pl.col('parcel_seq_id').is_in(int_ids))\n"
        "    return sub.select(feature_cols).to_numpy().astype(np.float64)\n"
        "\n"
        "X_train = slice_matrix(parcel_frame, tuple(fa0.train_ids), ae_cols_final)\n"
        "X_val = slice_matrix(parcel_frame, tuple(fa0.val_ids), ae_cols_final)\n"
        "X_test = slice_matrix(parcel_frame, tuple(fa0.test_ids), ae_cols_final)\n"
        "\n"
        "rows = []\n"
        "for split_name, mat in (('train', X_train), ('val', X_val), ('test', X_test)):\n"
        "    if mat.shape[0] == 0:\n"
        "        rows.append({'split': split_name, 'n': 0, 'mean_post': float('nan'), 'std_post': float('nan')})\n"
        "        continue\n"
        "    scaled = scaler.transform(mat)\n"
        "    rows.append({\n"
        "        'split': split_name,\n"
        "        'n': mat.shape[0],\n"
        "        'mean_post': float(scaled.mean()),\n"
        "        'std_post': float(scaled.std()),\n"
        "    })\n"
        "display(Markdown('**Estadísticas post-scaler por split** (train debería tener mean=0, std=1):'))\n"
        "display(pl.DataFrame(rows))\n"
    ),
    _md(
        "## 8.5. Matriz de fusión multisensor: AlphaEarth + SRTM + ERA5 + geometría (parcel-level)\n"
        "\n"
        "Construimos la matriz de fusión real a nivel parcela cargando los caches\n"
        "generados por `scripts/generate_srtm_era5_pastis_parcels.py` (SRTM + ERA5\n"
        "muestreados sobre los polígonos reales de las parcelas, no centroides) más\n"
        "el bloque geometría calculado localmente con `to_crs('EPSG:3857')`.\n"
        "El módulo `ml.features.fusion.build_fused_features` ya soporta inyección\n"
        "de frames pre-muestreados; lo invocamos en modo ablation (sin\n"
        "`sentinel1` ni `farslip`) para obtener una matriz fusion 94-dim coherente\n"
        "**a nivel parcela individual**, no a nivel patch.\n"
        "\n"
        "Si los caches parcel-level no existen, hacemos fallback a los caches\n"
        "patch-level (2433 filas) generados en la iteración anterior — la matriz\n"
        "fusion queda como demo del contrato pero no se alinea con las 85k\n"
        "parcelas reales del notebook.\n"
        "\n"
        "El bloque `indices_stats` (85 columnas) ya está cubierto por el\n"
        "subconjunto espectro-temporal del notebook anterior (sección 4). El\n"
        "bloque Sentinel-1 (10 columnas) queda pendiente: su cálculo es costoso\n"
        "(unas 9 horas de procesamiento en Earth Engine por el filtrado de\n"
        "moteado Lee 7x7 sobre unas 130 imágenes por parcela) y está planificado\n"
        "como un trabajo posterior, una sola vez, cuando se incorpore.\n"
    ),
    _code(
        "from ml.features import build_fused_features\n"
        "import geopandas as gpd\n"
        "\n"
        "# Preferimos los caches parcel-level (re-muestreados sobre poligonos 85k).\n"
        "# Si no existen, hacemos fallback a los patch-level (2433 centroides).\n"
        "SRTM_PARCEL = REPO_ROOT / 'data/cache/gee/srtm_pastis_fr_parcels_enriched.parquet'\n"
        "ERA5_PARCEL = REPO_ROOT / 'data/cache/gee/era5_pastis_fr_parcels_2019_enriched.parquet'\n"
        "S1_PATCH = REPO_ROOT / 'data/cache/gee/s1_pastis_fr_full_2019_both_lee_7x7_dB_enriched.parquet'\n"
        "SRTM_PATCH = REPO_ROOT / 'data/cache/gee/srtm_pastis_fr_full.parquet'\n"
        "ERA5_PATCH = REPO_ROOT / 'data/cache/gee/era5_monthly_pastis_fr_full_2019_C.parquet'\n"
        "\n"
        "fusion_built = False\n"
        "fusion_level = None  # 'parcel' o 'patch'\n"
        "\n"
        "if PASTIS_PARCELS_GEOPARQUET.exists() and SRTM_PARCEL.exists() and ERA5_PARCEL.exists():\n"
        "    # Modo parcel-level: usar geometrias reales de las 85k parcelas vectorizadas.\n"
        "    gdf_parcels_fusion = gpd.read_parquet(PASTIS_PARCELS_GEOPARQUET)\n"
        "    # Reasignar parcel_id a int sequential (mismo mapping que generate_srtm_era5_pastis_parcels.py).\n"
        "    gdf_parcels_fusion = gdf_parcels_fusion.reset_index(drop=True)\n"
        "    gdf_parcels_fusion['parcel_id_str'] = gdf_parcels_fusion['parcel_id'].astype(str)\n"
        "    gdf_parcels_fusion['parcel_id'] = gdf_parcels_fusion.index.astype('int64')\n"
        "    gdf_parcels_fusion['year'] = 2019\n"
        "\n"
        "    # Cargar caches enriquecidos.\n"
        "    srtm_enriched = pl.read_parquet(SRTM_PARCEL)\n"
        "    era5_enriched = pl.read_parquet(ERA5_PARCEL)\n"
        "\n"
        "    # AE frame: del cache enriched re-mapear parcel_id_str (10000_1) a parcel_id int.\n"
        "    mapping_df = pl.DataFrame({\n"
        "        'parcel_id_str': gdf_parcels_fusion['parcel_id_str'].tolist(),\n"
        "        'parcel_id_int': gdf_parcels_fusion['parcel_id'].astype('int64').tolist(),\n"
        "    })\n"
        "    ae_for_fusion = (\n"
        "        df_parcels\n"
        "        .rename({c: c.replace('dim_', 'ae_') for c in df_parcels.columns if c.startswith('dim_')})\n"
        "        .rename({'parcel_id': 'parcel_id_str'})\n"
        "        .join(mapping_df, on='parcel_id_str', how='inner')\n"
        "        .rename({'parcel_id_int': 'parcel_id'})\n"
        "        .with_columns(pl.lit(2019).cast(pl.Int16).alias('year'))\n"
        "        .select(['parcel_id', 'year', *[f'ae_{i:02d}' for i in range(64)]])\n"
        "    )\n"
        "\n"
        "    # SRTM/ERA5 enriquecidos: dropear parcel_id_str y mantener int.\n"
        "    srtm_for_fusion = srtm_enriched.drop('parcel_id_str').with_columns(\n"
        "        pl.lit(2019).cast(pl.Int16).alias('year')\n"
        "    )\n"
        "    era5_for_fusion = era5_enriched.drop('parcel_id_str').with_columns(\n"
        "        pl.lit(2019).cast(pl.Int16).alias('year')\n"
        "    )\n"
        "\n"
        "    # S1 patch-level (2433): se propaga a parcel-level via JOIN por patch_id.\n"
        "    # Es metodologicamente valido porque S1 ya es agregado espacial al nivel del patch\n"
        "    # (todas las parcelas del mismo patch comparten el mismo VV/VH backscatter).\n"
        "    blocks_to_use = ['alphaearth', 'srtm', 'era5_monthly', 'geometry']\n"
        "    s1_for_fusion = None\n"
        "    s1_join_pct = 0.0\n"
        "    if S1_PATCH.exists():\n"
        "        s1_patch_df = pl.read_parquet(S1_PATCH)\n"
        "        # JOIN por patch_id derivado del parcel_id_str ('10000_1' -> 10000).\n"
        "        parcels_with_patch = pl.DataFrame({\n"
        "            'parcel_id': gdf_parcels_fusion['parcel_id'].astype('int64').tolist(),\n"
        "            'patch_id': gdf_parcels_fusion['parcel_id_str'].str.split('_').str[0].astype('int64').tolist(),\n"
        "            'year': [2019] * len(gdf_parcels_fusion),\n"
        "        })\n"
        "        s1_propagated = (\n"
        "            parcels_with_patch\n"
        "            .join(\n"
        "                s1_patch_df.rename({'parcel_id': 'patch_id'}).drop('year'),\n"
        "                on='patch_id',\n"
        "                how='left',\n"
        "            )\n"
        "            .drop('patch_id')\n"
        "            .with_columns(pl.col('year').cast(pl.Int16))\n"
        "        )\n"
        "        # Cobertura: cuantas parcelas tienen S1 valido (no-null).\n"
        "        s1_valid = s1_propagated.filter(pl.col('s1_vv_mean').is_not_null()).height\n"
        "        s1_join_pct = 100.0 * s1_valid / s1_propagated.height\n"
        "        s1_for_fusion = s1_propagated\n"
        "        blocks_to_use.append('sentinel1')\n"
        "        display(Markdown(\n"
        "            f'**S1 patch-level propagado a parcel-level**: `{s1_valid}` de `{s1_propagated.height}` parcelas '\n"
        "            f'(`{s1_join_pct:.1f}%` cobertura tras JOIN por `patch_id`). '\n"
        "            f'Cache S1: `{s1_patch_df.shape[0]}` patches (de 2433 = `{100*s1_patch_df.shape[0]/2433:.1f}%`).'\n"
        "        ))\n"
        "\n"
        "    fused = build_fused_features(\n"
        "        gdf_parcels_fusion[['parcel_id', 'year', 'geometry']],\n"
        "        year=2019,\n"
        "        blocks=tuple(blocks_to_use),\n"
        "        ae_frame=ae_for_fusion,\n"
        "        srtm_frame=srtm_for_fusion,\n"
        "        era5_frame=era5_for_fusion,\n"
        "        s1_frame=s1_for_fusion,\n"
        "    )\n"
        "    fusion_built = True\n"
        "    fusion_level = 'parcel-level' + (' +S1' if s1_for_fusion is not None else '')\n"
        "    display(Markdown(\n"
        "        f'**Matriz de fusión parcel-level construida**: `{fused.shape[0]}` parcelas x '\n"
        "        f'`{fused.shape[1]}` columnas. Granularidad coherente con `df_parcels` (85k).'\n"
        "    ))\n"
        "    display(fused.head(3))\n"
        "elif SRTM_PATCH.exists() and ERA5_PATCH.exists() and PASTIS_ROOT.exists():\n"
        "    # Fallback patch-level: 2433 centroides.\n"
        "    from pyproj import Transformer\n"
        "    from shapely.geometry import shape\n"
        "    from shapely.ops import transform as shp_transform\n"
        "    META_PATH = PASTIS_ROOT / 'metadata.geojson'\n"
        "    with META_PATH.open(encoding='utf-8') as fh:\n"
        "        gj = json.load(fh)\n"
        "    transformer = Transformer.from_crs('EPSG:2154', 'EPSG:4326', always_xy=True)\n"
        "    records = []\n"
        "    for feat in gj.get('features', []):\n"
        "        gd = feat.get('geometry') or {}\n"
        "        if gd.get('type') not in ('Polygon', 'MultiPolygon'):\n"
        "            continue\n"
        "        try:\n"
        "            g = shape(gd)\n"
        "            if not g.is_valid:\n"
        "                g = g.buffer(0)\n"
        "            g_4326 = shp_transform(transformer.transform, g)\n"
        "        except Exception:\n"
        "            continue\n"
        "        pid = (feat.get('properties') or {}).get('ID_PATCH')\n"
        "        if pid is None:\n"
        "            continue\n"
        "        records.append({'parcel_id': int(pid), 'year': 2019, 'geometry': g_4326})\n"
        "    parcels_gdf_patch = gpd.GeoDataFrame(records, crs='EPSG:4326')\n"
        "    srtm_patch_df = pl.read_parquet(SRTM_PATCH)\n"
        "    era5_patch_df = pl.read_parquet(ERA5_PATCH)\n"
        "    # AE patch-level desde cache viejo si existe; si no, frame vacio.\n"
        "    ae_patch_path = REPO_ROOT / 'data/cache/gee/alphaearth_at_pastis_fr_full_2019_2433.parquet'\n"
        "    if ae_patch_path.exists():\n"
        "        ae_patch = (\n"
        "            pl.read_parquet(ae_patch_path)\n"
        "            .rename({c: c.replace('dim_', 'ae_') for c in pl.read_parquet(ae_patch_path).columns if c.startswith('dim_')})\n"
        "            .with_columns(pl.col('px_id').cast(pl.Int64).alias('parcel_id'))\n"
        "            .with_columns(pl.lit(2019).cast(pl.Int16).alias('year'))\n"
        "            .select(['parcel_id', 'year', *[f'ae_{i:02d}' for i in range(64)]])\n"
        "        )\n"
        "    else:\n"
        "        ae_patch = None\n"
        "    fused = build_fused_features(\n"
        "        parcels_gdf_patch,\n"
        "        year=2019,\n"
        "        blocks=('alphaearth', 'srtm', 'era5_monthly', 'geometry'),\n"
        "        ae_frame=ae_patch,\n"
        "        srtm_frame=srtm_patch_df,\n"
        "        era5_frame=era5_patch_df,\n"
        "    )\n"
        "    fusion_built = True\n"
        "    fusion_level = 'patch-level (fallback)'\n"
        "    display(Markdown(\n"
        "        f'**Matriz de fusión patch-level fallback**: `{fused.shape[0]}` patches x '\n"
        "        f'`{fused.shape[1]}` columnas. Caveat: no se alinea con las 85k parcelas reales del notebook.'\n"
        "    ))\n"
        "    display(fused.head(3))\n"
        "else:\n"
        "    display(Markdown(\n"
        "        f'**Matriz de fusión omitida**: falta alguno de los caches.  \\n'\n"
        "        f'Parcel-level: SRTM={SRTM_PARCEL.exists()}, ERA5={ERA5_PARCEL.exists()}, GeoParquet={PASTIS_PARCELS_GEOPARQUET.exists()}.  \\n'\n"
        "        f'Patch-level (fallback): SRTM={SRTM_PATCH.exists()}, ERA5={ERA5_PATCH.exists()}.  \\n'\n"
        "        f'Generar con: `poetry run python scripts/generate_srtm_era5_pastis_parcels.py --year 2019`.'\n"
        "    ))\n"
        "    fused = None\n"
    ),
    _code(
        "# Caracterización por bloque del frame fusion construido.\n"
        "if fusion_built and fused is not None:\n"
        "    feat_cols_fused = [c for c in fused.columns if c not in ('parcel_id', 'year')]\n"
        "    # Cobertura: cuántas filas tienen NaN por columna?\n"
        "    fused_pd = fused.to_pandas()\n"
        "    nan_per_col = fused_pd[feat_cols_fused].isna().sum()\n"
        "    cov_rows = []\n"
        "    for prefix, label in [('ae_', 'alphaearth'), ('s1_', 'sentinel1'), ('srtm_', 'srtm'), ('era5_', 'era5_monthly'), ('geom_', 'geometry')]:\n"
        "        block_cols = [c for c in feat_cols_fused if c.startswith(prefix)]\n"
        "        if not block_cols:\n"
        "            continue\n"
        "        nan_block = nan_per_col[block_cols].sum()\n"
        "        total_block = len(block_cols) * fused.shape[0]\n"
        "        cov_rows.append({\n"
        "            'block': label,\n"
        "            'n_cols': len(block_cols),\n"
        "            'n_parcels': fused.shape[0],\n"
        "            'nan_cells': int(nan_block),\n"
        "            'coverage_pct': round(100.0 * (1 - nan_block / max(total_block, 1)), 2),\n"
        "        })\n"
        "    cov_df = pl.DataFrame(cov_rows)\n"
        "    cov_path = REPORTS_DIR / 'fusion_block_coverage.csv'\n"
        "    cov_df.write_csv(cov_path)\n"
        "    display(Markdown(\n"
        "        f'**Cobertura por bloque de la matriz fusion** → `{cov_path.relative_to(REPO_ROOT)}`.  \\n'\n"
        "        f'NaN = parcelas donde GEE no devolvió valor (típicamente parcelas costeras pequeñas para ERA5).'\n"
        "    ))\n"
        "    display(cov_df)\n"
        "else:\n"
        "    cov_df = None\n"
    ),
    _md(
        "### 8.6. Extensión de la comparativa: AE solo vs fusion multisensor\n"
        "\n"
        "Cerramos la comparativa simétrica de la sección 4 agregando una tercera\n"
        "vista: la matriz de fusión real (AE + SRTM + ERA5 + geom) sobre los\n"
        "mismos folds oficiales PASTIS-R. Esperamos que el bloque SRTM + ERA5\n"
        "agregue señal de contexto geográfico (relieve y clima) que el embedding\n"
        "AlphaEarth no captura de forma explícita.\n"
    ),
    _code(
        "# Vista fusion: agregar al comp_df de la seccion 4 una fila con la matriz multisensor.\n"
        "if fusion_built and fused is not None:\n"
        "    # Pasar a numpy y manejar NaN (parcelas costeras con ERA5 missing).\n"
        "    # Drop srtm_aspect_dominant (es categorical string, no util sin one-hot).\n"
        "    feat_cols_fusion = [c for c in fused.columns\n"
        "                        if c not in ('parcel_id', 'year', 'srtm_aspect_dominant')]\n"
        "    X_fusion = fused.select(feat_cols_fusion).to_numpy().astype(np.float64)\n"
        "    X_fusion = np.nan_to_num(X_fusion, nan=0.0, posinf=0.0, neginf=0.0)\n"
        "    # Alinear y/folds segun el fusion_level (parcel-level vs patch-level fallback).\n"
        "    fused_pids = fused.get_column('parcel_id').to_list()\n"
        "    if fusion_level and fusion_level.startswith('parcel-level'):\n"
        "        # En parcel-level, parcel_id es int sequential (0..N-1). gdf_parcels_fusion lo mapea.\n"
        "        pid_to_class = dict(zip(\n"
        "            gdf_parcels_fusion['parcel_id'].astype('int64').tolist(),\n"
        "            df_parcels.join(\n"
        "                pl.DataFrame({\n"
        "                    'parcel_id_str': gdf_parcels_fusion['parcel_id_str'].tolist(),\n"
        "                    '_int_pid': gdf_parcels_fusion['parcel_id'].astype('int64').tolist(),\n"
        "                }),\n"
        "                left_on='parcel_id', right_on='parcel_id_str', how='inner',\n"
        "            ).get_column('class_id').to_list(),\n"
        "        ))\n"
        "        # Build int->fold map via join.\n"
        "        fold_join = df_parcels.join(\n"
        "            pl.DataFrame({\n"
        "                'parcel_id_str': gdf_parcels_fusion['parcel_id_str'].tolist(),\n"
        "                '_int_pid': gdf_parcels_fusion['parcel_id'].astype('int64').tolist(),\n"
        "            }),\n"
        "            left_on='parcel_id', right_on='parcel_id_str', how='inner',\n"
        "        )\n"
        "        pid_to_fold = dict(zip(fold_join['_int_pid'].to_list(), fold_join['fold'].to_list()))\n"
        "    else:\n"
        "        # Patch-level fallback: parcel_id es patch_id int. Mapeo desde df_parcels por patch_id.\n"
        "        pid_to_class = dict(zip(\n"
        "            df_parcels.get_column('patch_id').to_list(),\n"
        "            df_parcels.get_column('class_id').to_list(),\n"
        "        ))\n"
        "        pid_to_fold = dict(zip(\n"
        "            df_parcels.get_column('patch_id').to_list(),\n"
        "            df_parcels.get_column('fold').to_list(),\n"
        "        ))\n"
        "    y_fusion = np.array([pid_to_class.get(int(p), -1) for p in fused_pids])\n"
        "    folds_fusion = np.array([pid_to_fold.get(int(p), -1) for p in fused_pids])\n"
        "    # Filtrar parcelas sin label.\n"
        "    valid = y_fusion >= 0\n"
        "    X_fusion = X_fusion[valid]\n"
        "    y_fusion = y_fusion[valid]\n"
        "    folds_fusion = folds_fusion[valid]\n"
        "\n"
        "    fusion_f1_mean, fusion_f1_std = cv_f1_macro_official_folds(X_fusion, y_fusion, folds_fusion)\n"
        "    fusion_row = {\n"
        "        'fuente': f'Fusion multisensor AE+SRTM+ERA5+geom 94-dim ({fusion_level}, folds oficiales)',\n"
        "        'n_features': int(X_fusion.shape[1]),\n"
        "        'n_samples': int(X_fusion.shape[0]),\n"
        "        'n_classes': int(np.unique(y_fusion).size),\n"
        "        'f1_macro_mean': round(fusion_f1_mean, 4),\n"
        "        'f1_macro_std': round(fusion_f1_std, 4),\n"
        "    }\n"
        "    comp_df_extended = pl.concat([comp_df, pl.DataFrame([fusion_row])], how='vertical')\n"
        "    comp_extended_path = REPORTS_DIR / 'ae_vs_spectral_temporal_vs_fusion.csv'\n"
        "    comp_df_extended.write_csv(comp_extended_path)\n"
        "\n"
        "    # Calcular ganancia fusion vs AE solo.\n"
        "    ae_only_f1 = comp_df.filter(pl.col('fuente').str.contains('AlphaEarth')).row(0, named=True)['f1_macro_mean']\n"
        "    gain_vs_ae = round(fusion_f1_mean - ae_only_f1, 4)\n"
        "    display(Markdown(\n"
        "        f'**Comparativa extendida con fusion multisensor** → `{comp_extended_path.relative_to(REPO_ROOT)}`  \\n'\n"
        "        f'**Ganancia fusion vs AE solo**: `{gain_vs_ae:+.4f}` puntos F1-macro '\n"
        "        f'sobre los mismos `{int(X_fusion.shape[0])}` parcelas y los mismos folds oficiales PASTIS-R.'\n"
        "    ))\n"
        "    display(comp_df_extended)\n"
        "else:\n"
        "    comp_df_extended = comp_df\n"
        "    gain_vs_ae = None\n"
    ),
    _md(
        "## 9. Selección y normalización sobre el bloque AlphaEarth\n"
        "\n"
        "Aplicamos la suite de selección sobre el bloque AlphaEarth para\n"
        "demostrar que la API es la misma que el notebook anterior:\n"
        "filtro de varianza, deduplicación por correlación, ANOVA F\n"
        "supervisado, proyección PCA y `ColumnTransformer` reutilizable.\n"
    ),
    _code(
        "# Frame con parcel_id + year + 64 dimensiones AE para la suite de seleccion.\n"
        "X_ae = parcel_frame.select(['parcel_id', 'year', *ae_cols_final])\n"
        "y_ae = parcel_frame.get_column('class_id')\n"
        "\n"
        "X_var, var_report = apply_variance_threshold(X_ae, threshold=0.0001)\n"
        "X_corr, corr_report = drop_correlated_features(X_var, threshold=0.9, method='pearson')\n"
        "display(Markdown(\n"
        "    f'**Filtro de varianza (0.0001)**: removidas `{len(var_report[\"removed\"])}`  \\n'\n"
        "    f'**Pearson |r|>0.9**: removidas `{len(corr_report[\"removed\"])}`  \\n'\n"
        "    f'**Forma final**: `{X_corr.shape[0]} x {X_corr.shape[1] - 2}` características (sin parcel_id/year)'\n"
        "))\n"
    ),
    _code(
        "# ANOVA F sobre el bloque AlphaEarth (cuando hay suficientes clases).\n"
        "if y_ae.n_unique() >= 2:\n"
        "    _, anova_scores = anova_f_select(X_corr, y_ae, k_best=min(10, X_corr.shape[1] - 2))\n"
        "    anova_df = pl.DataFrame({\n"
        "        'feature': list(anova_scores.keys()),\n"
        "        'f_value': list(anova_scores.values()),\n"
        "    }).sort('f_value', descending=True)\n"
        "    anova_path = REPORTS_DIR / 'ae_anova_f_top.csv'\n"
        "    anova_df.write_csv(anova_path)\n"
        "    display(Markdown(\n"
        "        f'**Top dimensiones AlphaEarth por ANOVA F** (`{y_ae.n_unique()}` clases) → '\n"
        "        f'`{anova_path.relative_to(REPO_ROOT)}`'\n"
        "    ))\n"
        "    display(anova_df.head(10))\n"
        "else:\n"
        "    display(Markdown('**ANOVA F omitido**: se requiere al menos 2 clases.'))\n"
        "    anova_df = pl.DataFrame()\n"
    ),
    _code(
        "# Proyeccion PCA sobre el bloque AlphaEarth + ColumnTransformer reusable.\n"
        "from sklearn.preprocessing import StandardScaler as SkScaler\n"
        "\n"
        "feat_only = X_corr.drop(['parcel_id', 'year']).to_numpy().astype(np.float64)\n"
        "feat_only = np.nan_to_num(feat_only, nan=0.0)\n"
        "feat_std = SkScaler().fit_transform(feat_only)\n"
        "pca_res = fit_pca(feat_std, target_variance=0.95)\n"
        "display(Markdown(\n"
        "    f'**PCA sobre bloque AlphaEarth**: `{pca_res[\"n_components\"]}` componentes '\n"
        "    f'capturan el 95% de la varianza (entrada: `{feat_std.shape[1]}` dimensiones).'\n"
        "))\n"
        "\n"
        "pre_linear = make_preprocessor(X_corr, strategy='linear')\n"
        "pre_nn = make_preprocessor(X_corr, strategy='nn')\n"
        "display(Markdown('**ColumnTransformer reutilizable construido para dos familias de modelo**'))\n"
        "print(f'linear -> {pre_linear}')\n"
        "print(f'nn     -> {pre_nn}')\n"
    ),
    _md(
        "## 10. Persistencia de outputs consumibles\n"
        "\n"
        "Guardamos el frame parcel-level final más un manifiesto JSON que\n"
        "describe el contrato de datos para que cualquier script downstream\n"
        "pueda cargar los outputs sin reproducir el pipeline completo.\n"
        "El cache pre-generado ya vive en `data/cache/gee/` y no necesita\n"
        "duplicarse aquí.\n"
    ),
    _code(
        "# Parcel-level: 64 dims AE + class_id + agronomic_group + fold oficial + coords.\n"
        "parcel_path = REPORTS_DIR / 'ae_parcel_level.parquet'\n"
        "parcel_frame.write_parquet(parcel_path)\n"
        "\n"
        "manifest = {\n"
        "    'parcel_level': {\n"
        "        'path': str(parcel_path.relative_to(REPO_ROOT)),\n"
        "        'n_parcels': parcel_frame.height,\n"
        "        'n_features': len(ae_cols_final),\n"
        "        'feature_prefix': 'ae_',\n"
        "        'label_cols': ['class_id', 'agronomic_group'],\n"
        "        'fold_col': 'fold',\n"
        "        'aggregation': 'AlphaEarth sampled at PASTIS patch centroid; no pixel->parcel reduction',\n"
        "    },\n"
        "    'source_cache': {\n"
        "        'path': str(AE_PARQUET.relative_to(REPO_ROOT)),\n"
        "        'description': 'AlphaEarth annual embedding 2019 over 2433 PASTIS-R patch centroids',\n"
        "        'year': 2019,\n"
        "    },\n"
        "    'scaler': {\n"
        "        'path': str(scaler_path.relative_to(REPO_ROOT)),\n"
        "        'version': meta['version'],\n"
        "        'fitted_on': f'train split of official PASTIS fold-1 ({meta[\"n_train\"]} parcels)',\n"
        "        'feature_cols': meta['feature_cols'],\n"
        "    },\n"
        "    'spatial_folds': {\n"
        "        'source': 'official PASTIS-R folds 1-5 from metadata.geojson',\n"
        "        'k': k_folds,\n"
        "        'val_fraction': 0.2,\n"
        "        'random_state': 42,\n"
        "    },\n"
        "    'pipeline_steps': [\n"
        "        'apply_variance_threshold(threshold=0.0001)',\n"
        "        'drop_correlated_features(threshold=0.9, method=pearson)',\n"
        "    ],\n"
        "    'pca_n_components_95pct': int(pca_res['n_components']),\n"
        "}\n"
        "manifest_path = REPORTS_DIR / 'fusion_manifest.json'\n"
        "manifest_path.write_text(json.dumps(manifest, indent=2), encoding='utf-8')\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Parcel-level**: `{parcel_path.relative_to(REPO_ROOT)}` '\n"
        "    f'(`{parcel_path.stat().st_size / 1024:.1f}` KB, `{parcel_frame.height}` filas)  \\n'\n"
        "    f'**Cache fuente**: `{AE_PARQUET.relative_to(REPO_ROOT)}`  \\n'\n"
        "    f'**Manifiesto**: `{manifest_path.relative_to(REPO_ROOT)}`'\n"
        "))\n"
    ),
    _md(
        "## 11. Conclusiones\n"
        "\n"
        "Esta sección se actualiza automáticamente al re-ejecutar el notebook\n"
        "con números frescos del run. La narrativa fija (qué importa y por\n"
        "qué) se complementa con los valores empíricos del run actual,\n"
        "siguiendo la regla de citar números reales en lugar de afirmaciones\n"
        "genéricas.\n"
    ),
    _code(
        "# Generacion dinamica del bloque de conclusiones con metricas reales del run.\n"
        "lines: list[str] = []\n"
        "lines.append('### Qué aporta el bloque AlphaEarth a la matriz de fusión\\n')\n"
        "lines.append(\n"
        "    f'El embedding AlphaEarth de **64 dimensiones** se comporta como un vector '\n"
        "    f'semántico denso sobre las **{n_pixels} parcelas** PASTIS-R con etiqueta '\n"
        "    f'(`{df_parcels[\"class_id\"].n_unique()}` clases agrupadas en '\n"
        "    f'`{df_parcels[\"agronomic_group\"].n_unique()}` familias agronómicas). '\n"
        ")\n"
        "lines.append(\n"
        "    f'La media global del embedding es `{ae_matrix.mean():.4f}` con sigma `{ae_matrix.std():.4f}`. '\n"
        "    f'La norma L2 por parcela tiene CV = `{l2_stats[\"cv\"]:.4f}` → '\n"
        '    f\'{"AlphaEarth normaliza al hipersphere" if is_l2_normalized else "NO normaliza al hipersphere (varía por píxel)"}. \'\n'
        "    f'Hay `{dead_dims}` dimensiones muertas y `{low_var_dims}` de baja varianza, lo que indica '\n"
        '    f\'{"un embedding muy denso (todas las dims aportan)" if dead_dims == 0 and low_var_dims < 4 else "que algunas dims aportan poco y podrían descartarse"}.\'\n'
        ")\n"
        "lines.append('')\n"
        "lines.append('### Ortogonalidad y correlación cruzada\\n')\n"
        "lines.append(\n"
        "    f'La correlación cruzada entre las 64 dimensiones tiene media `|r| = {np.abs(off_diag).mean():.4f}` '\n"
        "    f'(mediana `{np.median(np.abs(off_diag)):.4f}`, máx `{np.abs(off_diag).max():.4f}`). '\n"
        "    f'El `{frac_low_corr:.2%}` de los pares tiene `|r| < 0.1` (casi ortogonales) y solo el '\n"
        "    f'`{frac_high_corr:.2%}` tiene `|r| > 0.5` (acopladas). '\n"
        "    f'Esto confirma que el foundation model entrena para ortogonalidad efectiva, lo que justifica usar '\n"
        "    f'el embedding crudo sin necesidad de aplicar PCA agresivo antes del baseline.'\n"
        ")\n"
        "lines.append('')\n"
        "\n"
        "if stability_computed and stab_df.height > 0:\n"
        "    mean_cos = float(stab_df['cos_sim_mean'].mean())\n"
        "    min_cos = float(stab_df['cos_sim_min'].min())\n"
        "    lines.append('### Estabilidad inter-anual\\n')\n"
        "    lines.append(\n"
        "        f'Sobre `{n_common}` píxeles comunes a los `{len(available_years)}` años cacheados '\n"
        "        f'({available_years}), la similitud coseno año-a-año tiene media `{mean_cos:.4f}` '\n"
        "        f'y mínimo `{min_cos:.4f}`. '\n"
        "    )\n"
        "    if mean_cos >= 0.9:\n"
        "        lines.append(\n"
        "            'El embedding es **altamente estable** entre años: la misma parcela produce vectores '\n"
        "            'casi idénticos en años distintos, lo que permite confiar en comparaciones temporales y '\n"
        "            'en transfer learning año-a-año.'\n"
        "        )\n"
        "    elif mean_cos >= 0.7:\n"
        "        lines.append(\n"
        "            'El embedding tiene **estabilidad moderada** entre años. Hay variabilidad inter-anual '\n"
        "            'que el modelo downstream debe absorber, pero la estructura semántica se preserva '\n"
        "            'lo suficiente como para usar embeddings multi-año en el mismo entrenamiento.'\n"
        "        )\n"
        "    else:\n"
        "        lines.append(\n"
        "            'El embedding muestra **estabilidad inter-anual baja**, lo que sugiere que tratar embeddings '\n"
        "            'de años distintos como features intercambiables introduce ruido. Recomendable normalizar '\n"
        "            'o entrenar por año.'\n"
        "        )\n"
        "    lines.append('')\n"
        "\n"
        "if comp_df.height >= 2:\n"
        "    ae_row = comp_df.row(0, named=True)\n"
        "    st_row = comp_df.row(1, named=True)\n"
        "    diff = ae_row['f1_macro_mean'] - st_row['f1_macro_mean']\n"
        "    lines.append('### AlphaEarth vs spectral-temporal (comparativa simétrica)\\n')\n"
        "    lines.append(\n"
        "        f'Random Forest 80 árboles bajo CV sobre los 5 folds espaciales oficiales PASTIS-R '\n"
        "        f'(misma partición, mismas parcelas). '\n"
        '        f\'AlphaEarth 64-dim: F1-macro `{ae_row["f1_macro_mean"]:.4f} ± {ae_row["f1_macro_std"]:.4f}` \'\n'
        '        f\'(`{ae_row["n_samples"]}` parcelas, `{ae_row["n_classes"]}` clases). \'\n'
        "        f'Spectral-temporal manual `{st_row[\"n_features\"]}-dim`: '\n"
        '        f\'`{st_row["f1_macro_mean"]:.4f} ± {st_row["f1_macro_std"]:.4f}` \'\n'
        '        f\'(`{st_row["n_samples"]}` parcelas, `{st_row["n_classes"]}` clases). \'\n'
        "    )\n"
        "    direction = 'AlphaEarth' if diff > 0.02 else ('spectral-temporal' if diff < -0.02 else 'ninguna')\n"
        "    if direction == 'AlphaEarth':\n"
        "        ratio = round(st_row['n_features'] / ae_row['n_features'], 1)\n"
        "        lines.append(\n"
        "            f'**AlphaEarth supera por `{abs(diff):.4f}` puntos** pese a usar `{ratio}x` menos features. '\n"
        "            f'Esto justifica preferir el embedding pre-entrenado como bloque principal y reservar '\n"
        "            f'las features manuales como complemento para fusion multisensor.'\n"
        "        )\n"
        "    elif direction == 'spectral-temporal':\n"
        "        lines.append(\n"
        "            f'**Spectral-temporal manual supera por `{abs(diff):.4f}` puntos**. '\n"
        "            f'El embedding solo no captura toda la señal temporal del ciclo fenológico; '\n"
        "            f'la fusion AE + spectral-temporal sigue siendo la mejor apuesta.'\n"
        "        )\n"
        "    else:\n"
        "        lines.append(\n"
        "            f'La diferencia es de `{diff:.4f}` puntos, dentro del ruido esperable. '\n"
        "            f'Las dos vistas aportan información comparable; conviene fusionarlas en el baseline downstream.'\n"
        "        )\n"
        "    lines.append('')\n"
        "\n"
        "if fusion_built and fused is not None and gain_vs_ae is not None:\n"
        "    lines.append('### Fusion multisensor: ganancia sobre AlphaEarth solo\\n')\n"
        "    feat_cols_eval = [c for c in fused.columns if c not in ('parcel_id', 'year')]\n"
        "    direction_fusion = 'aporta' if gain_vs_ae > 0.01 else ('NO aporta' if gain_vs_ae < -0.01 else 'aporta marginal')\n"
        "    lines.append(\n"
        "        f'Agregar SRTM (relieve) + ERA5 (clima mensual) + geometría al embedding AlphaEarth da '\n"
        "        f'`{fusion_f1_mean:.4f} ± {fusion_f1_std:.4f}` F1-macro sobre `{int(X_fusion.shape[0])}` parcelas '\n"
        "        f'y `{len(feat_cols_eval)}` columnas (sobre el contrato fusion completo de 189). '\n"
        "        f'**Ganancia vs AE solo**: `{gain_vs_ae:+.4f}` puntos → el contexto geográfico-climático '\n"
        "        f'**{direction_fusion}** señal adicional a la firma semántica del foundation model.'\n"
        "    )\n"
        "    lines.append('')\n"
        "\n"
        "lines.append('### Folds espaciales oficiales y scaler\\n')\n"
        "lines.append(\n"
        "    f'Se usaron los **{k_folds} folds espaciales oficiales PASTIS-R** distribuidos en '\n"
        "    f'`metadata.geojson` (Sainte-Fare-Garnot 2021), con `{duplicates}` duplicados en test acumulado '\n"
        "    f'(cero fuga cross-fold por construcción oficial: cada tile Sentinel-2 cae en un solo fold). '\n"
        "    f'El `StandardScaler` se ajustó sobre `{meta[\"n_train\"]}` parcelas del train del Fold-1 '\n"
        "    f'y se persistió como `{Path(meta[\"version\"]).name}` joblib '\n"
        "    f'(`{scaler_path.stat().st_size / 1024:.1f}` KB). '\n"
        "    f'`fit_scaler_on_train` validó explícitamente la ausencia de intersección train/val/test.'\n"
        ")\n"
        "lines.append('')\n"
        "lines.append('### Limitaciones del run\\n')\n"
        "lim_lines = [\n"
        "    f'- Dataset a escala completa: **{parcel_frame.height} parcelas PASTIS-R** con embeddings AlphaEarth 2019. '\n"
        "    f'Cubre los 5 folds oficiales sin truncar.',\n"
        "]\n"
        "if fusion_built and fused is not None and cov_df is not None:\n"
        "    n_blocks_real = cov_df.height\n"
        "    avg_cov = float(cov_df['coverage_pct'].mean())\n"
        "    lim_lines.append(\n"
        "        f'- Matriz de fusión multisensor construida sobre **{n_blocks_real} bloques reales** '\n"
        "        f'(AE + SRTM + ERA5 + geometría) con cobertura promedio `{avg_cov:.1f}%` '\n"
        "        f'(NaN típicamente en parcelas costeras pequeñas donde el píxel ERA5 ~11 km '\n"
        "        f'no tiene cobertura terrestre clara).'\n"
        "    )\n"
        "lim_lines.append(\n"
        "    f'- **Bloque Sentinel-1 pendiente**: su cálculo se estima en unas '\n"
        "    f'9 horas de Earth Engine por el filtrado de moteado Lee 7x7 sobre '\n"
        "    f'unas 130 imágenes por parcela; queda planificado como un trabajo '\n"
        "    f'posterior. La función `build_fused_features` ya admite incorporar '\n"
        "    f'el bloque en cuanto el cache de radar esté disponible.'\n"
        ")\n"
        "lim_lines.append(\n"
        "    f'- **Bloque indices_stats** (85 cols, índices espectrales x stats temporales agregadas): '\n"
        "    f'no se ejecuta sobre PASTIS-FR aquí porque requiere un sampler GEE específico. '\n"
        "    f'El subset spectral-temporal cargado en la sección 4 (notebook anterior) ya cubre esto.'\n"
        ")\n"
        "lim_lines.append(\n"
        "    f'- El bloque de características visuales destiladas (512 dimensiones, '\n"
        "    f'derivadas de un modelo de visión-lenguaje) se incorporará en una '\n"
        "    f'fase posterior, cuando esté disponible su cache de embeddings. '\n"
        "    f'En esa fase el total de columnas esperado pasa de 189 a 701.'\n"
        ")\n"
        "lim_lines.append(\n"
        "    f'- La comparativa AE vs spectral-temporal vs fusion usa Random Forest 80 árboles sin tuning Optuna '\n"
        "    f'ni XGBoost. El baseline final downstream con tuning espera F1-macro ≥ 0.60.'\n"
        ")\n"
        "lim_lines.append(\n"
        "    f'- AlphaEarth se muestreó en el centroide del patch reproyectado a EPSG:4326. '\n"
        "    f'Una alternativa más fiel sería muestrear sobre el polígono completo del patch con '\n"
        "    f'`reduceRegions` + `Reducer.mean`, lo que daría un embedding ponderado por área de cada parcela.'\n"
        ")\n"
        "lines.append('\\n'.join(lim_lines))\n"
        "lines.append('')\n"
        "lines.append('### Lo que sigue\\n')\n"
        "lines.append(\n"
        "    f'Los artefactos persistidos en `reports/feature_fusion/` (parcel-level AE + matriz fusion 94-dim '\n"
        "    f'multisensor + scaler + manifiesto JSON) alimentan los baselines tabulares Random Forest y XGBoost '\n"
        "    f'del siguiente paso del proyecto. La próxima integración natural es el bloque Sentinel-1 '\n"
        "    f'(10 cols backscatter VV+VH x 5 stats, ~9h GEE one-shot), que cierra la matriz fusion 189-dim '\n"
        "    f'completa según el contrato de `ml.features.fusion`. Sobre ese set la hipótesis de la literatura '\n"
        "    f'agronómica es que la fusion multisensor supere al baseline solo-AlphaEarth en ≥ 0.05 puntos F1-macro.'\n"
        ")\n"
        "\n"
        "display(Markdown('\\n'.join(lines)))\n"
    ),
]


def build_notebook(out_path: Path) -> None:
    nb = nbf.v4.new_notebook()
    nb.cells = CELLS
    nb.metadata.update(
        {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        }
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, str(out_path))


if __name__ == "__main__":
    OUT = (
        Path(__file__).resolve().parents[1]
        / "notebooks"
        / "feature_engineering"
        / "03c_fe_alphaearth_pastis.ipynb"
    )
    build_notebook(OUT)
    print(f"Notebook escrito en {OUT}")
