"""Generate baseline scenario (b): raw Sentinel-2 at parcel level.

Operational tool of US-022 (EPIC 4). Aggregates the 10 Sentinel-2 bands of
PASTIS-R (``PASTIS_S2_BANDS``) averaged **temporally and spatially**
within each parcel polygon, producing scenario (b) of the baseline
comparison (``ml/eval/comparison.py``).

For each PASTIS-R patch:

1. Loads the Sentinel-2 tensor ``DATA_S2/S2_<patch_id>.npy`` of shape
   ``(T, 10, 128, 128)`` int16.
2. Loads the instance mask ``ANNOTATIONS/TARGET_<patch_id>.npy`` channel 1,
   which assigns each pixel to an ``instance_id`` (= one parcel).
3. For each ``instance_id`` present in the patch, averages the 10 bands
   over the ``T`` time steps and over the mask pixels.

The resulting ``parcel_id`` is ``"<patch_id>_<instance_id>"``, identical to
the convention of ``scripts/vectorize_pastis_parcels.py`` and of the
AlphaEarth and feature_selection parquets — the three scenarios align by
``parcel_id``.

The parcels to process (and their ``class_id``, ``fold``) come from the
GeoParquet ``data/processed/pastis_parcels_full.geoparquet`` (85,951
parcels, generated by ``vectorize_pastis_parcels.py``); only the bands of
those parcels are aggregated to guarantee the inner join with the other
scenarios.

Usage::

    poetry run python scripts/build_s2_raw_parcels.py \\
        --pastis-root data/PASTIS-R \\
        --parcels data/processed/pastis_parcels_full.geoparquet \\
        --out data/cache/pastis/s2_raw_parcels_2019_85951.parquet \\
        --n-jobs -1
"""

from __future__ import annotations

import time
from pathlib import Path

import numpy as np
import polars as pl
import structlog
import typer
from joblib import Parallel, delayed

from ml.ingest.pastis_loader import PASTIS_S2_BANDS

logger = structlog.get_logger(__name__)
app = typer.Typer(add_completion=False, help=__doc__)

# Names of the mean-band columns in the output parquet.
_BAND_MEAN_COLS: list[str] = [f"{band}_mean" for band in PASTIS_S2_BANDS]

# Canonical schema of the output parquet (stable order).
_OUTPUT_SCHEMA: dict[str, pl.DataType] = {
    "parcel_id": pl.Utf8(),
    "patch_id": pl.Int64(),
    "instance_id": pl.Int64(),
    **{col: pl.Float64() for col in _BAND_MEAN_COLS},
    "class_id": pl.Int64(),
    "fold": pl.Int64(),
}


def aggregate_patch_bands(
    patch_id: int,
    s2_path: Path,
    instance_path: Path,
    parcels: list[dict[str, object]],
) -> list[dict[str, object]]:
    """Aggregate the 10 mean S2 bands of a patch's parcels.

    Loads the patch's Sentinel-2 tensor and instance mask, and for each
    requested parcel computes the mean of each band over the ``T`` time
    steps and over the pixels of its mask.

    Args:
        patch_id: PASTIS-R patch identifier.
        s2_path: Path to the tensor ``S2_<patch_id>.npy`` ``(T, 10, H, W)``.
        instance_path: Path to ``TARGET_<patch_id>.npy`` ``(3, H, W)``;
            channel 1 is the instance mask.
        parcels: List of dicts with ``parcel_id``, ``instance_id``,
            ``class_id`` and ``fold`` of this patch's parcels.

    Returns:
        List of dicts with ``parcel_id``, ``patch_id``, ``instance_id``,
        the 10 ``<band>_mean`` columns, ``class_id`` and ``fold``. Empty
        if the tensors cannot be loaded or no parcel has valid pixels.
    """
    if not s2_path.exists() or not instance_path.exists():
        logger.warning(
            "patch_tensor_missing",
            patch_id=patch_id,
            s2=str(s2_path),
            instance=str(instance_path),
        )
        return []

    try:
        s2 = np.load(s2_path)
        target = np.load(instance_path)
    except (OSError, ValueError) as exc:
        logger.warning("patch_load_failed", patch_id=patch_id, error=str(exc))
        return []

    if s2.ndim != 4 or s2.shape[1] != len(PASTIS_S2_BANDS):
        logger.warning("patch_s2_unexpected_shape", patch_id=patch_id, shape=tuple(s2.shape))
        return []
    if target.ndim != 3 or target.shape[0] < 2:
        logger.warning(
            "patch_target_unexpected_shape",
            patch_id=patch_id,
            shape=tuple(target.shape),
        )
        return []

    instance = target[1]
    # Temporal mean per band: (T, 10, H, W) -> (10, H, W). float64 avoids
    # int16 overflow when summing T time steps.
    band_means_thw = s2.astype(np.float64).mean(axis=0)

    records: list[dict[str, object]] = []
    for parcel in parcels:
        instance_id = int(parcel["instance_id"])  # type: ignore[arg-type]
        mask = instance == instance_id
        n_pixels = int(mask.sum())
        if n_pixels == 0:
            # The GeoParquet parcel has no pixels in the instance
            # mask of this patch (rare: misaligned instance_id).
            continue
        # Spatial mean of each band over the pixels of the mask.
        band_values = band_means_thw[:, mask].mean(axis=1)
        record: dict[str, object] = {
            "parcel_id": str(parcel["parcel_id"]),
            "patch_id": int(patch_id),
            "instance_id": instance_id,
            "class_id": int(parcel["class_id"]),  # type: ignore[arg-type]
            "fold": int(parcel["fold"]),  # type: ignore[arg-type]
        }
        for col, value in zip(_BAND_MEAN_COLS, band_values, strict=True):
            record[col] = float(value)
        records.append(record)

    return records


def _parcels_by_patch(
    parcels_path: Path,
) -> dict[int, list[dict[str, object]]]:
    """Group the GeoParquet parcels by ``patch_id``.

    Reads only the scalar columns (without the geometry) — the band
    aggregation uses the raster instance mask, not the vector polygon.

    Args:
        parcels_path: Path to ``pastis_parcels_full.geoparquet``.

    Returns:
        Map ``{patch_id: [parcel, ...]}`` where each parcel is a dict
        with ``parcel_id``, ``instance_id``, ``class_id`` and ``fold``.

    Raises:
        FileNotFoundError: if the GeoParquet does not exist.
    """
    if not parcels_path.exists():
        raise FileNotFoundError(
            f"Parcels GeoParquet not found at {parcels_path}. "
            "Generate the parcels with `scripts/vectorize_pastis_parcels.py`."
        )

    # `pl.read_parquet` reads the GeoParquet ignoring the binary `geometry`
    # column; we select only the scalar columns needed.
    cols = ["parcel_id", "patch_id", "instance_id", "class_id", "fold"]
    parcels_df = pl.read_parquet(parcels_path, columns=cols)

    grouped: dict[int, list[dict[str, object]]] = {}
    for row in parcels_df.iter_rows(named=True):
        patch_id = int(row["patch_id"])
        grouped.setdefault(patch_id, []).append(
            {
                "parcel_id": str(row["parcel_id"]),
                "instance_id": int(row["instance_id"]),
                "class_id": int(row["class_id"]),
                "fold": int(row["fold"]),
            }
        )
    return grouped


@app.command()
def main(
    pastis_root: Path = typer.Option(  # noqa: B008
        Path("data/PASTIS-R"),
        "--pastis-root",
        help="Raiz del dataset PASTIS-R (con DATA_S2/ y ANNOTATIONS/).",
    ),
    parcels: Path = typer.Option(  # noqa: B008
        Path("data/processed/pastis_parcels_full.geoparquet"),
        "--parcels",
        help="GeoParquet de poligonos de parcela (vectorize_pastis_parcels.py).",
    ),
    out: Path = typer.Option(  # noqa: B008
        Path("data/cache/pastis/s2_raw_parcels_2019_85951.parquet"),
        "--out",
        help="Parquet de salida con las 10 bandas medias por parcela.",
    ),
    n_jobs: int = typer.Option(-1, "--n-jobs", help="Paralelismo joblib (-1 = todos los nucleos)."),
    limit_patches: int = typer.Option(
        0,
        "--limit-patches",
        help="Si > 0, procesa solo los primeros N patches (smoke test).",
    ),
) -> None:
    """Generate scenario (b) raw Sentinel-2 at parcel level."""
    if not pastis_root.exists():
        logger.error("pastis_root_missing", path=str(pastis_root))
        raise typer.Exit(code=2)

    s2_dir = pastis_root / "DATA_S2"
    annotations_dir = pastis_root / "ANNOTATIONS"
    if not s2_dir.exists() or not annotations_dir.exists():
        logger.error(
            "pastis_subdirs_missing",
            data_s2=str(s2_dir),
            annotations=str(annotations_dir),
        )
        raise typer.Exit(code=2)

    logger.info("s2_raw_parcels_start", parcels=str(parcels), out=str(out))
    parcels_by_patch = _parcels_by_patch(parcels)
    patch_ids = sorted(parcels_by_patch)
    if limit_patches > 0:
        patch_ids = patch_ids[:limit_patches]
    n_parcels_total = sum(len(parcels_by_patch[p]) for p in patch_ids)
    logger.info(
        "patches_to_process",
        n_patches=len(patch_ids),
        n_parcels=n_parcels_total,
        n_jobs=n_jobs,
    )

    t0 = time.time()
    batches: list[list[dict[str, object]]] = Parallel(n_jobs=n_jobs)(
        delayed(aggregate_patch_bands)(
            patch_id,
            s2_dir / f"S2_{patch_id}.npy",
            annotations_dir / f"TARGET_{patch_id}.npy",
            parcels_by_patch[patch_id],
        )
        for patch_id in patch_ids
    )
    all_records: list[dict[str, object]] = [rec for batch in batches for rec in batch]
    elapsed = time.time() - t0
    logger.info(
        "s2_raw_aggregation_done",
        n_records=len(all_records),
        elapsed_s=round(elapsed, 1),
    )

    if not all_records:
        logger.error("no_records_extracted")
        raise typer.Exit(code=3)

    df = pl.DataFrame(all_records, schema=_OUTPUT_SCHEMA).sort("parcel_id")
    out.parent.mkdir(parents=True, exist_ok=True)
    df.write_parquet(out)
    file_size_mb = out.stat().st_size / 1e6
    logger.info(
        "s2_raw_parcels_written",
        path=str(out),
        n_parcels=df.height,
        n_bands=len(_BAND_MEAN_COLS),
        file_size_mb=round(file_size_mb, 2),
    )

    fold_counts = df.group_by("fold").len().sort("fold").to_dicts() if df.height else []
    n_classes = df.get_column("class_id").n_unique()
    typer.echo(
        f"S2 raw parcels: {df.height} parcelas, {len(_BAND_MEAN_COLS)} bandas, "
        f"{n_classes} clases, folds={fold_counts}"
    )
    typer.echo(f"Output: {out}")


if __name__ == "__main__":
    app()
