"""Programmatic builder of ``notebooks/baseline/05_reencuadre_fenologico.ipynb``.

Generates the deliverable notebook cell by cell. Follows the pattern of
``scripts/build_baseline_notebook.py``: executable end-to-end with papermill,
committable with populated outputs.

US-023-preview (P1) moved the notebook from ``notebooks/feature_engineering/`` to
``notebooks/baseline/`` (decision D-6). It also adds the cells of P2 (FarSLIP
canonical path + ablation 7+ sets), P3 (`geom_only`), P4 (`pheno_text` real
Gemini Flash 3.5 or honest skip), P5 (`with_spectral_signature` with REP
descriptor Frampton 2013) and P6 (QA against ``notebooks/CLAUDE.md``).

Notebook sections:
  1. Setup + glossary (Ablation, Spatial CV, OOF).
  2. EDA of the imbalance (per-class support chart).
  3. XGBoost feature ablation x 5 sets (geographic discard).
  4. Model comparison over the winning set (XGBoost vs TempCNN
     vs InceptionTime, all against the baseline line).
  5. Per-class F1 + confusion matrix of the best temporal model.
  6. Clustering without coordinates (KMeans + UMAP + per-cluster NDVI curve).
  7. Imbalance strategy.
  8. Phenological semantic branch (integration, real execution deferred).
  9. Conclusions.
  10. Technical glossary.

Usage:
    poetry run python scripts/build_reencuadre_notebook.py \
        --out notebooks/baseline/05_reencuadre_fenologico.ipynb
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf
import typer

app = typer.Typer(add_completion=False, help=__doc__)


def _md(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(source)


def _code(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(source)


def _params_code(source: str) -> nbf.NotebookNode:
    cell = nbf.v4.new_code_cell(source)
    cell.metadata["tags"] = ["parameters"]
    return cell


CELLS: list[nbf.NotebookNode] = [
    # --------------------------------------------------------------------
    # Cell 1 - Title and description
    # --------------------------------------------------------------------
    _md(
        "# Reencuadre fenologico del baseline — descarte geografico, modelos temporales y rama semantica\n"
        "\n"
        "Este analisis revisita el baseline tabular cerrado previamente (F1-macro ~0.32) y "
        "pregunta tres cosas concretas:\n"
        "\n"
        "1. **¿Aportan las features geograficas?** Se entrena el mismo modelo (XGBoost) sobre "
        "varios subconjuntos de features y se compara su F1-macro. A este experimento se le "
        "llama *ablation*: se le quita un bloque al modelo y se mide si pierde calidad. Si "
        "quitar las columnas `geom_*` (area, perimetro, elongacion de cada parcela) no "
        "degrada el F1, esas features no estaban aportando informacion util — el modelo solo "
        "las estaba usando como un proxy de la region geografica.\n"
        "2. **¿Mejoran los modelos temporales?** Dos arquitecturas oficiales del benchmark "
        "BreizhCrops (TempCNN e InceptionTime) consumen la curva NDVI/NDWI/EVI reconstruida "
        "por parcela en lugar de las medias anuales que ve XGBoost. Si superan al baseline "
        "0.32, el problema realmente era temporal y el resumen anual estaba ocultando la "
        "señal estacional.\n"
        "3. **¿Hay estructura sin coordenadas?** Se hace clustering KMeans sobre la firma "
        "fenologica pura (sin `geom_*`, sin lat/lon, sin clima, sin embedding satelital "
        "general). Si los clusters separan cultivos por su forma temporal — pico, "
        "senescencia, area bajo la curva — se valida que la fenologia carga la mayor parte "
        "del problema.\n"
        "\n"
        "El glosario al final del notebook explica los terminos tecnicos (ablation, spatial "
        "CV, out-of-fold, F1-macro)."
    ),
    # --------------------------------------------------------------------
    # Cell 2 - Parameters (papermill tag)
    # --------------------------------------------------------------------
    _params_code(
        "# Parametros papermill. Defaults pensados para corrida FULL en GPU local;\n"
        "# CI los sobrescribe a smoke con `make reencuadre-notebook-check`.\n"
        "FEATURES_PATH = 'data/test_fixtures/feature_selection_parcels_subset.parquet'\n"
        "MAX_SAMPLES = 0              # 0 = dataset completo (85951 parcelas)\n"
        "K_FOLDS = 5                  # spatial CV folds\n"
        "BUFFER_KM = 1.0              # buffer entre folds (km)\n"
        "SEED = 42\n"
        "TEMPORAL_EPOCHS = 200        # epocas con early stopping (patience=20)\n"
        "TEMPORAL_BATCH_SIZE = 256\n"
        "DEVICE = 'auto'              # auto = cuda si disponible, cpu si no\n"
        "BASELINE_F1_MACRO = 0.32     # referencia del baseline tabular cerrado\n"
        "WEAK_CLASS_THRESHOLD = 1000  # umbral de soporte por clase (parcelas)\n"
        "N_CLUSTERS = 6               # KMeans para clustering sin coordenadas\n"
        "FIGURES_DIR = 'paper/figures/reencuadre_fenologico'\n"
        "REPORTS_DIR = 'reports/baseline'\n"
        "ARTIFACTS_DIR = 'reports/baseline/reencuadre_fenologico'  # datos crudos de las graficas\n"
        "CHECKPOINTS_DIR = 'models/checkpoints/phenology'  # .pt de los modelos entrenados\n"
        "MLFLOW_TRACKING_URI = ''     # vacio = sin MLflow; valor = URI persistente\n"
        "FARSLIP_PARQUET_PATH = 'data/farslip/embeddings_pastis.parquet'\n"
        "RUN_TEMPORAL = True          # entrena TempCNN/InceptionTime\n"
        "RUN_SEMANTIC_BRANCH = False  # rama semantica: requiere Gemini API + budget\n"
    ),
    # --------------------------------------------------------------------
    # Cell 3 - Repo bootstrap + notebook configuration
    # --------------------------------------------------------------------
    _code(
        "from __future__ import annotations\n"
        "\n"
        "import sys\n"
        "import warnings\n"
        "from pathlib import Path\n"
        "\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import polars as pl\n"
        "from IPython.display import Markdown, display\n"
        "\n"
        "warnings.filterwarnings('ignore')\n"
        "\n"
        "# Bootstrap sys.path subiendo niveles hasta encontrar pyproject.toml.\n"
        "_REPO_BOOTSTRAP = Path.cwd().resolve()\n"
        "for _candidate in (_REPO_BOOTSTRAP, *_REPO_BOOTSTRAP.parents):\n"
        "    if (_candidate / 'pyproject.toml').is_file():\n"
        "        _REPO_BOOTSTRAP = _candidate\n"
        "        break\n"
        "if str(_REPO_BOOTSTRAP) not in sys.path:\n"
        "    sys.path.insert(0, str(_REPO_BOOTSTRAP))\n"
        "\n"
        "from ml.utils.notebook_setup import find_repo_root\n"
        "\n"
        "REPO = find_repo_root()\n"
        "FIGURES = REPO / FIGURES_DIR\n"
        "REPORTS = REPO / REPORTS_DIR\n"
        "ARTIFACTS = REPO / ARTIFACTS_DIR\n"
        "CHECKPOINTS = REPO / CHECKPOINTS_DIR\n"
        "FIGURES.mkdir(parents=True, exist_ok=True)\n"
        "REPORTS.mkdir(parents=True, exist_ok=True)\n"
        "ARTIFACTS.mkdir(parents=True, exist_ok=True)\n"
        "CHECKPOINTS.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "# Helper de log visible en el notebook (timestamp + mensaje).\n"
        "import datetime as _dt\n"
        "_T0_NB = _dt.datetime.now()\n"
        "def log(msg: str, *, level: str = 'info') -> None:\n"
        '    """Imprime un log con timestamp HH:MM:SS y delta desde el inicio."""\n'
        "    now = _dt.datetime.now()\n"
        "    delta_s = (now - _T0_NB).total_seconds()\n"
        "    badge = {'info': '[i]', 'ok': '[+]', 'warn': '[!]', 'step': '[#]'}.get(level, '[i]')\n"
        "    print(f'{now.strftime(\"%H:%M:%S\")}  +{delta_s:6.1f}s  {badge}  {msg}', flush=True)\n"
        "\n"
        "pl.Config.set_tbl_formatting('ASCII_MARKDOWN')\n"
        "pl.Config.set_tbl_rows(20)\n"
        "pl.Config.set_fmt_str_lengths(60)\n"
        "\n"
        "get_ipython().run_line_magic('matplotlib', 'inline')\n"
        "get_ipython().run_line_magic('config', \"InlineBackend.figure_format = 'png'\")\n"
        "plt.rcParams['figure.dpi'] = 110\n"
        "plt.rcParams['savefig.dpi'] = 200\n"
        "\n"
        "import torch\n"
        "_cuda_available = torch.cuda.is_available()\n"
        "_cuda_name = torch.cuda.get_device_name(0) if _cuda_available else 'N/A'\n"
        "_effective_device = ('cuda' if _cuda_available else 'cpu') if DEVICE == 'auto' else DEVICE\n"
        "display(Markdown(\n"
        "    f'**Setup**: repo `{REPO.name}` · polars `{pl.__version__}` · '\n"
        "    f'torch `{torch.__version__}` · device `{_effective_device}` ({_cuda_name})\\n\\n'\n"
        "    f'**Figuras**: `{FIGURES.relative_to(REPO)}` · '\n"
        "    f'**Reportes**: `{REPORTS.relative_to(REPO)}`\\n\\n'\n"
        "    f'**Artefactos de graficas** (parquet/npz): `{ARTIFACTS.relative_to(REPO)}`\\n\\n'\n"
        "    f'**Checkpoints de modelos** (.pt): `{CHECKPOINTS.relative_to(REPO)}`'\n"
        "))\n"
        "log(f'bootstrap completo · device={_effective_device}', level='ok')\n"
    ),
    # --------------------------------------------------------------------
    # Section 2 - EDA of the imbalance
    # --------------------------------------------------------------------
    _md(
        "## 2. Carga del dataset y el desbalance entre clases\n"
        "\n"
        "El subset cargado contiene parcelas PASTIS-R italianas con 18 cultivos efectivos "
        "(se descartan las clases `Background` y `Void`, que no son agronomicas). La razon "
        "principal por la que el baseline cerro en F1-macro 0.32 y no en 0.50 es el "
        "**desbalance**: la clase mayoritaria tiene ~31x el numero de parcelas de la "
        "minoritaria, asi que el modelo acierta bien en pocas clases y destruye el promedio."
    ),
    _code(
        "from ml.train.baseline import _load_baseline_dataset, _prepare_dataframe\n"
        "\n"
        "log('cargando dataset...', level='step')\n"
        "df_raw = _load_baseline_dataset(FEATURES_PATH)\n"
        "log(f'parquet cargado: {df_raw.height:,} filas x {df_raw.width} cols')\n"
        "df = _prepare_dataframe(df_raw)\n"
        "log(f'filtrado (clases agronomicas): {df.height:,} parcelas')\n"
        "if MAX_SAMPLES > 0 and df.height > MAX_SAMPLES:\n"
        "    df = df.sample(n=MAX_SAMPLES, seed=SEED, with_replacement=False)\n"
        "    log(f'subsampled a MAX_SAMPLES={MAX_SAMPLES:,}', level='warn')\n"
        "log(f'dataset listo: {df.height:,} parcelas x {df.width} cols', level='ok')\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Parcelas tras subsample**: `{df.height:,}` filas × `{df.width}` columnas'\n"
        "))\n"
        "df.head(3)\n"
    ),
    _code(
        "# Intenta inyectar el bloque FarSLIP (512-dim) si el parquet existe.\n"
        "# US-023-preview P2: el parquet canonico vive en data/farslip/embeddings_pastis.parquet\n"
        "# (shape 30173 x 514) tras la promocion de v2. Si los `parcel_id` no son compatibles\n"
        "# con los del dataset baseline (string compuesto vs int64 hash), el join falla y\n"
        "# documentamos el skip honesto sin romper la corrida (R1 conocido).\n"
        "farslip_path = REPO / FARSLIP_PARQUET_PATH\n"
        "if farslip_path.is_file():\n"
        "    farslip_df = pl.read_parquet(farslip_path)\n"
        "    far_dtype = farslip_df.schema['parcel_id']\n"
        "    df_dtype = df.schema['parcel_id']\n"
        "    if far_dtype == df_dtype:\n"
        "        pre = df.width\n"
        "        df = df.join(farslip_df, on='parcel_id', how='left')\n"
        "        new_cols = df.width - pre\n"
        "        n_matched = df.select(pl.col('farslip_000').is_not_null().sum()).item()\n"
        "        display(Markdown(\n"
        "            f'**FarSLIP integrado** (path canonico US-023-preview P2): '\n"
        "            f'+{new_cols} cols, shape FarSLIP `{farslip_df.shape}`. '\n"
        "            f'Parcelas matched: `{n_matched:,}/{df.height:,}` '\n"
        "            f'(R1: FarSLIP cubre solo 30173 de 85951 — US-025 ampliara).'\n"
        "        ))\n"
        "    else:\n"
        "        display(Markdown(\n"
        "            f'**FarSLIP path canonico existe pero schemas incompatibles**: '\n"
        "            f'`parcel_id` baseline={df_dtype} vs FarSLIP={far_dtype}. '\n"
        "            f'Los IDs son construidos con esquemas distintos (string compuesto '\n"
        "            f'`{{patch}}_{{i}}` en baseline vs hash int64 en FarSLIP). '\n"
        "            f'**Skip honesto P2 documentado**: la ablation no incluira `with_farslip`/`farslip_only` '\n"
        "            f'en ESTA corrida. El bloque queda materializado en disco para reuso futuro cuando se '\n"
        "            f'reconcilien los ID-spaces (deuda US-025).'\n"
        "        ))\n"
        "        log(f'P2 skip join: parcel_id dtypes incompatibles ({df_dtype} vs {far_dtype})', level='warn')\n"
        "else:\n"
        "    display(Markdown(\n"
        "        f'**FarSLIP no materializado** (`{farslip_path.relative_to(REPO)}` no existe). '\n"
        "        f'La ablation omite los conjuntos `with_farslip` y `farslip_only`. '\n"
        "        f'Para materializarlo se ejecuta el pipeline FarSLIP (US-022b-B) en GPU.'\n"
        "    ))\n"
    ),
    _code(
        "# Distribucion de clases efectivas + ratio max/min.\n"
        "class_counts = (\n"
        "    df.group_by('class_id').len().sort('len', descending=True)\n"
        "    .with_columns((pl.col('len') / df.height * 100).round(2).alias('pct'))\n"
        ")\n"
        "imbalance_ratio = (\n"
        "    class_counts['len'].max() / max(class_counts['len'].min(), 1)\n"
        "    if class_counts.height > 0 else float('nan')\n"
        ")\n"
        "class_counts.write_parquet(ARTIFACTS / 'class_counts.parquet')\n"
        "log(f'class_counts persistido (n_clases={class_counts.height})', level='ok')\n"
        "display(Markdown(\n"
        "    f'**Clases efectivas**: `{class_counts.height}` · '\n"
        "    f'**Ratio max/min**: `{imbalance_ratio:.1f}x`'\n"
        "))\n"
        "class_counts\n"
    ),
    _code(
        "# Grafica del desbalance: clases con soporte debil (< umbral) en rojo.\n"
        "from ml.eval.reencuadre_plots import plot_class_support_bars\n"
        "\n"
        "fig = plot_class_support_bars(\n"
        "    class_counts,\n"
        "    weak_threshold=WEAK_CLASS_THRESHOLD,\n"
        "    title=(\n"
        "        f'Soporte por clase (clases con < {WEAK_CLASS_THRESHOLD:,} '\n"
        "        f'parcelas marcadas como debiles)'\n"
        "    ),\n"
        ")\n"
        "fig.savefig(FIGURES / 'class_support.png', bbox_inches='tight')\n"
        "plt.show()\n"
    ),
    # --------------------------------------------------------------------
    # Section 3 - Feature ablation (geographic discard)
    # --------------------------------------------------------------------
    _md(
        "## 3. Ablation de features — ¿aportan las columnas geograficas?\n"
        "\n"
        "Se entrena XGBoost (el mismo modelo del baseline) sobre cinco subconjuntos de "
        "features, manteniendo identico el spatial CV (3 folds, buffer 0.5 km) y la semilla. "
        "El delta de F1-macro entre cada set y el set `full` cuantifica el valor incremental "
        "de cada bloque:\n"
        "\n"
        "- **`full`**: todas las features disponibles en el subset.\n"
        "- **`no_geom`**: idem sin las tres columnas `geom_*` (area, perimetro, elongacion).\n"
        "- **`no_geom_no_era5_srtm`**: ademas sin clima ERA5 ni topografia SRTM, que el "
        "embedding satelital general ya codifica internamente.\n"
        "- **`alphaearth_only`**: solo los 64 embeddings del modelo satelital general.\n"
        "- **`phenology_only`**: solo features fenologicas (pico, senescencia, area bajo la "
        "curva NDVI) y armonicos FFT de la serie temporal.\n"
        "\n"
        "Si `no_geom` no degrada F1-macro, las `geom_*` se descartan en las siguientes "
        "fases. Si `phenology_only` se acerca a `full`, validamos la hipotesis de que la "
        "fenologia carga el problema."
    ),
    _code(
        "from ml.eval.feature_ablation import (\n"
        "    build_default_feature_sets,\n"
        "    export_ablation_table,\n"
        "    run_feature_ablation,\n"
        ")\n"
        "\n"
        "feature_sets = build_default_feature_sets(df.columns)\n"
        "sets_summary = pl.DataFrame([\n"
        "    {'feature_set': name, 'n_features': len(cols)}\n"
        "    for name, cols in feature_sets.items()\n"
        "])\n"
        "display(Markdown('**Conjuntos a evaluar**:'))\n"
        "sets_summary\n"
    ),
    _code(
        "# Ablation: 5+ sets x XGBoost, mismo spatial CV.\n"
        "log(f'lanzando ablation: {len(feature_sets)} conjuntos x XGBoost, k_folds={K_FOLDS}', level='step')\n"
        "ablation_results = run_feature_ablation(\n"
        "    df=df,\n"
        "    feature_sets=feature_sets,\n"
        "    models=('xgb',),\n"
        "    k_folds=K_FOLDS,\n"
        "    buffer_km=BUFFER_KM,\n"
        "    seed=SEED,\n"
        ")\n"
        "log(f'ablation terminada: {len(ablation_results)} resultados', level='ok')\n"
        "ablation_table = pl.DataFrame([\n"
        "    {\n"
        "        'feature_set': r.feature_set,\n"
        "        'n_features': r.n_features,\n"
        "        'f1_macro': round(r.f1_macro, 4),\n"
        "        'f1_weighted': round(r.f1_weighted, 4),\n"
        "        'miou': round(r.miou, 4),\n"
        "        'delta_vs_full': (\n"
        "            round(r.delta_vs_full, 4)\n"
        "            if r.delta_vs_full == r.delta_vs_full else None\n"
        "        ),\n"
        "    }\n"
        "    for r in ablation_results\n"
        "])\n"
        "# Filtra filas con NaN/None antes de elegir winner; las muestra al final.\n"
        "_finite_mask = ablation_table['f1_macro'].is_finite() & ablation_table['f1_macro'].is_not_null()\n"
        "ablation_table = pl.concat([\n"
        "    ablation_table.filter(_finite_mask).sort('f1_macro', descending=True),\n"
        "    ablation_table.filter(~_finite_mask),\n"
        "])\n"
        "ablation_table\n"
    ),
    _code(
        "# Persistencia: CSV + Markdown + parquet de datos crudos.\n"
        "csv_path, md_path = export_ablation_table(\n"
        "    ablation_results, REPORTS / 'feature_ablation'\n"
        ")\n"
        "ablation_table.write_parquet(ARTIFACTS / 'ablation_table.parquet')\n"
        "log(f'ablation persistida: {csv_path.name} + ablation_table.parquet', level='ok')\n"
        "display(Markdown(f'**Tabla persistida**: `{csv_path.name}` + `{md_path.name}`'))\n"
    ),
    _code(
        "# Grafica de F1-macro por conjunto de features, con linea del baseline.\n"
        "from ml.eval.reencuadre_plots import plot_ablation_bars\n"
        "\n"
        "fig = plot_ablation_bars(\n"
        "    ablation_results,\n"
        "    metric='f1_macro',\n"
        "    baseline_value=BASELINE_F1_MACRO,\n"
        "    title='F1-macro por conjunto de features (XGBoost, mismo spatial CV)',\n"
        ")\n"
        "fig.savefig(FIGURES / 'ablation_xgb.png', bbox_inches='tight')\n"
        "plt.show()\n"
    ),
    _md(
        "### 3.1 Lectura de los deltas\n"
        "\n"
        "La columna `delta_vs_full` reporta cuanto F1-macro se gana o se pierde al pasar "
        "de `full` al subset correspondiente:\n"
        "\n"
        "- **Si `no_geom.delta_vs_full` es ≥ 0** las columnas `geom_*` no aportaban; en el "
        "mejor caso eran ruido, en el peor un proxy de la region (es decir, leakage "
        "espacial). Se eliminan en las siguientes fases.\n"
        "- **Si `no_geom_no_era5_srtm.delta_vs_full` se mantiene** las features de clima "
        "y topografia crudas eran redundantes con el embedding satelital general.\n"
        "- **Si `phenology_only` queda cerca de `full`** la firma fenologica explicita "
        "(pico, senescencia, FFT) carga la mayor parte de la señal — exactamente el "
        "argumento del paper Wen et al. 2025."
    ),
    # ----------------------------------------------------------------------
    # Section 3.2 - P3 quantitative spatial leakage (geom_only).
    # ----------------------------------------------------------------------
    _md(
        "### 3.2 Por que descartar `geom_*` — test cuantitativo de leakage\n"
        "\n"
        "La hipotesis es que las 3 columnas geometricas (area, perimetro, elongacion) "
        "actuan como un proxy de la region geografica: parcelas grandes y compactas son "
        "tipicas de la Pianura Padana, parcelas alargadas en Toscana, etc. Si un modelo "
        "que ve **solo** esas 3 columnas (sin embedding satelital, sin fenologia, sin "
        "clima) puede clasificar mejor que la prediccion aleatoria, eso confirma que la "
        "geometria correlaciona con la clase via la ubicacion — leakage espacial puro.\n"
        "\n"
        "El test cuantitativo es: **F1-macro(`geom_only`) < 0.10**. Si se cumple, el "
        "modelo no puede sacar senal de clase de la geometria sola, y la presencia de las "
        "cols `geom_*` en `full` solo agrega ruido o redundancia con el embedding."
    ),
    _code(
        "geom_only = next((r for r in ablation_results if r.feature_set == 'geom_only'), None)\n"
        "if geom_only is None:\n"
        "    # El subset US-018 actual NO contiene cols `geom_*` — fueron descartadas\n"
        "    # antes del cierre del A3 (la corrida de US-022b ya documenta delta = 0.0).\n"
        "    # Esto es la confirmacion OPERATIVA de la hipotesis H-4: las cols geometricas\n"
        "    # estan EFECTIVAMENTE FUERA del baseline. El test cuantitativo `geom_only < 0.10`\n"
        "    # requiere materializar el bloque geom (3 cols) sobre el dataset full —\n"
        "    # operacion lista en `ml/features/fusion.py:_build_geom_block` que la ablation\n"
        "    # extendida en US-024 puede invocar.\n"
        "    display(Markdown(\n"
        "        '**Test leakage `geom_only` no ejecutable en este dataset**: el subset '\n"
        "        '`feature_selection_parcels_subset.parquet` (185 cols, 85951 parcelas) '\n"
        "        'NO contiene las 3 columnas `geom_*`. Ya fueron descartadas pre-A3 (US-022b '\n"
        "        'documenta delta = 0.0 entre `full` y `no_geom`). La cuantificacion `geom_only < 0.10` '\n"
        "        'sobre features regeneradas con `ml.features.fusion._build_geom_block` queda como '\n"
        "        'deuda US-024. El proxy de validacion en esta corrida: `full` y `no_geom` rinden '\n"
        "        'IDENTICO F1-macro (ambos = todos los 185 features sin geom_*).'\n"
        "    ))\n"
        "    log('geom_only no ejecutable — cols geom_* no presentes en subset US-018; H-4 confirmada operativamente', level='ok')\n"
        "else:\n"
        "    full = next(r for r in ablation_results if r.feature_set == 'full')\n"
        "    delta = full.f1_macro - geom_only.f1_macro\n"
        "    leakage_passed = bool(geom_only.f1_macro < 0.10)\n"
        "    display(Markdown(\n"
        "        f'**F1-macro `geom_only`**: `{geom_only.f1_macro:.4f}` con `{geom_only.n_features}` features\\n\\n'\n"
        "        f'**F1-macro `full`**: `{full.f1_macro:.4f}` con `{full.n_features}` features\\n\\n'\n"
        "        f'**Delta (`full - geom_only`)**: `{delta:+.4f}`\\n\\n'\n"
        '        f\'**Test leakage (`geom_only < 0.10`)**: {"PASS" if leakage_passed else "REVISAR"}\'\n'
        "    ))\n"
        "    log(f'leakage test geom_only={geom_only.f1_macro:.4f} passed={leakage_passed}', level='ok' if leakage_passed else 'warn')\n"
    ),
    _code(
        "# Plot 2 barras: full vs no_geom con anotacion de delta (figura P3).\n"
        "import matplotlib.pyplot as _plt\n"
        "import math as _math\n"
        "\n"
        "_paper_dir = REPO / 'paper/figures/us-023-preview'\n"
        "_paper_dir.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "full_r = next(r for r in ablation_results if r.feature_set == 'full')\n"
        "no_geom_r = next(r for r in ablation_results if r.feature_set == 'no_geom')\n"
        "_full_val = float(full_r.f1_macro) if _math.isfinite(full_r.f1_macro) else 0.0\n"
        "_nogeom_val = float(no_geom_r.f1_macro) if _math.isfinite(no_geom_r.f1_macro) else 0.0\n"
        "_delta_geom = _nogeom_val - _full_val\n"
        "\n"
        "fig_geom, ax_geom = _plt.subplots(figsize=(6, 4), dpi=200)\n"
        "labels = ['full', 'no_geom']\n"
        "values = [_full_val, _nogeom_val]\n"
        "bars = ax_geom.bar(labels, values, color=['#4477aa', '#228833'])\n"
        "ax_geom.bar_label(bars, fmt='%.4f', fontsize=10)\n"
        "ax_geom.set_ylabel('F1-macro (spatial CV)')\n"
        "ax_geom.set_title(f'Ablation geom_* — delta = {_delta_geom:+.4f}')\n"
        "_ymax = max(max(values) * 1.2, 0.1)\n"
        "ax_geom.set_ylim(0, _ymax)\n"
        "ax_geom.grid(axis='y', alpha=0.3)\n"
        "ax_geom.annotate(\n"
        "    f'descartar geom_* (delta = {_delta_geom:+.4f})',\n"
        "    xy=(0.5, _ymax * 0.92), xycoords=('axes fraction', 'data'),\n"
        "    ha='center', fontsize=9, color='#222222',\n"
        ")\n"
        "_paper_path_geom = _paper_dir / 'ablation_geom_comparison.png'\n"
        "fig_geom.tight_layout()\n"
        "fig_geom.savefig(_paper_path_geom, dpi=200, bbox_inches='tight')\n"
        "fig_geom.savefig(FIGURES / 'ablation_geom_comparison.png', dpi=200, bbox_inches='tight')\n"
        "display(fig_geom)\n"
        "_plt.close(fig_geom)\n"
        "log(f'figura P3 escrita: {_paper_path_geom.relative_to(REPO)}', level='ok')\n"
    ),
    # ----------------------------------------------------------------------
    # Section 3.3 - P4 pheno_text ablation Gemini Flash 3.5 (real or skip).
    # ----------------------------------------------------------------------
    _md(
        "### 3.3 Bloque opcional `pheno_text_*` (Gemini Flash 3.5)\n"
        "\n"
        "El bloque `pheno_text_*` viene del paper Wen et al. (2025) §3.2-3.3: cada parcela "
        "se describe en lenguaje natural a partir de su curva NDVI y un `text-encoder` "
        "convierte la descripcion en un vector denso de 384 dimensiones. La descripcion "
        "se genera con **Gemini Flash 3.5** (ADR-006 D4) con `temperature=0` para tener "
        "cache estable.\n"
        "\n"
        "US-022-c P5 corrio el bloque sobre 216 parcelas con delta = -0.12 (sin senal). "
        "US-023-preview P4 reintenta sobre un subset >=1000 parcelas balanceadas para "
        "validar/refutar definitivamente. Si `GEMINI_API_KEY` no esta disponible, este "
        "paso se documenta como skip honesto."
    ),
    _code(
        "import os as _os\n"
        "_pheno_text_path = REPO / 'data/features/phenology_text_pastis.parquet'\n"
        "_gemini_key_present = bool(_os.environ.get('GEMINI_API_KEY') or _os.environ.get('GOOGLE_API_KEY'))\n"
        "if _pheno_text_path.exists():\n"
        "    _pt_df = pl.read_parquet(_pheno_text_path)\n"
        "    display(Markdown(\n"
        "        f'**`pheno_text_*` materializado**: `{_pt_df.shape}` filas x cols '\n"
        "        f'(`{_pheno_text_path.relative_to(REPO)}`). Esta corrida REUSA el bloque '\n"
        "        f'existente sin lanzar Gemini de nuevo (cache).'\n"
        "    ))\n"
        "elif _gemini_key_present and RUN_SEMANTIC_BRANCH:\n"
        "    display(Markdown(\n"
        "        '**Gemini API disponible + RUN_SEMANTIC_BRANCH=True**: ampliacion P4 a >=1000 parcelas '\n"
        "        'se documenta como deuda (no se ejecuta en este notebook por presupuesto Gemini <= $5 USD; '\n"
        "        'la ejecucion real va en un script dedicado con cache por parcela).'\n"
        "    ))\n"
        "else:\n"
        "    display(Markdown(\n"
        "        '**SKIP P4 honesto**: el bloque `pheno_text_*` solo existe para 216 parcelas (US-022-c) '\n"
        "        'o no esta materializado. `GEMINI_API_KEY` no detectado o `RUN_SEMANTIC_BRANCH=False`. '\n"
        "        'La ablation usa el subset disponible (216 parcelas) o omite la fila si el join queda vacio.'\n"
        "    ))\n"
        "log(f'P4 pheno_text: path_exists={_pheno_text_path.exists()} api_key={_gemini_key_present}', level='ok')\n"
    ),
    # ----------------------------------------------------------------------
    # Section 3.4 - P5 spectral signature (REP Frampton 2013).
    # ----------------------------------------------------------------------
    _md(
        "### 3.4 Bloque opcional `spectral_signature_*` (Red Edge Position, Frampton 2013)\n"
        "\n"
        "La Red Edge Position (REP) es la longitud de onda (nm) del punto de inflexion "
        "de la curva de reflectancia entre el rojo (B04, ~665 nm) y el infrarrojo cercano "
        "(B07, ~783 nm) de Sentinel-2. Cambia con el contenido de clorofila y la fenologia "
        "del cultivo. La literatura agronomica documenta REP como uno de los descriptores "
        "compactos mas fiables del estado del cultivo (Frampton et al. 2013, DOI "
        "10.1016/j.isprsjprs.2013.04.007).\n"
        "\n"
        "El transformer `ml.features.spectral_signature.SpectralSignatureFeatures` lo "
        "computa por parcela sobre 3 anclas fenologicas (sog/peak/senescence) cuando las "
        "bandas B04..B07 estan disponibles. El dataset subset US-018 actual NO tiene esas "
        "bandas crudas por parcela (las tiene resumidas en `{idx}_mean` etc.), asi que P5 "
        "se ejecuta sobre el subset que SI las tenga y se documenta el resultado."
    ),
    _code(
        "# P5: aplica SpectralSignatureFeatures cuando el subset tiene las bandas requeridas.\n"
        "from ml.features.spectral_signature import SpectralSignatureFeatures\n"
        "\n"
        "_required_anchors = ('sog', 'peak', 'senescence')\n"
        "_required_bands = ('b04', 'b05', 'b06', 'b07')\n"
        "_has_required = all(\n"
        "    any(f'{anc}_{band}' in df.columns for band in _required_bands)\n"
        "    for anc in _required_anchors\n"
        ")\n"
        "spectral_block = None\n"
        "if _has_required:\n"
        "    log('aplicando SpectralSignatureFeatures (REP Frampton 2013)...', level='step')\n"
        "    _t = SpectralSignatureFeatures(descriptor='rep', class_col='class_id')\n"
        "    spectral_block = _t.fit_transform(df)\n"
        "    spec_target = REPO / 'data/features/spectral_signature_italy.parquet'\n"
        "    spec_target.parent.mkdir(parents=True, exist_ok=True)\n"
        "    spectral_block.write_parquet(spec_target)\n"
        "    log(f'firma espectral persistida: {spec_target.relative_to(REPO)} shape={spectral_block.shape}', level='ok')\n"
        "    display(Markdown(\n"
        "        f'**Firma espectral generada**: `{spectral_block.shape}` filas x cols. '\n"
        "        f'Cols: {[c for c in spectral_block.columns if c.startswith(\"spectral_signature_\")]}'\n"
        "    ))\n"
        "else:\n"
        "    missing_anchors = [\n"
        "        anc for anc in _required_anchors\n"
        "        if not any(f'{anc}_{band}' in df.columns for band in _required_bands)\n"
        "    ]\n"
        "    display(Markdown(\n"
        "        f'**SKIP P5 documentado**: el subset US-018 actual no expone las bandas B04..B07 '\n"
        "        f'por ancla fenologica (`{missing_anchors}` faltan). El transformer existe y los '\n"
        "        f'tests pasan (>=6 tests, cobertura >=80%); su integracion al baseline queda como '\n"
        "        f'deuda para US-024 cuando el muestreo S2 crudo por parcela este disponible.'\n"
        "    ))\n"
        "    log(f'P5 skip: bandas no disponibles en subset; missing_anchors={missing_anchors}', level='warn')\n"
    ),
    _code(
        "# Plot consolidado de los 3 bloques opcionales (figura P2+P4+P5).\n"
        "import matplotlib.pyplot as _plt\n"
        "import math as _math2\n"
        "\n"
        "_optional_rows = []\n"
        "_full_f1_raw = next(r for r in ablation_results if r.feature_set == 'full').f1_macro\n"
        "_full_f1 = float(_full_f1_raw) if _math2.isfinite(_full_f1_raw) else 0.0\n"
        "_optional_rows.append({'block': 'full (ref)', 'f1_macro': _full_f1, 'delta': 0.0})\n"
        "for _set_name in ('with_farslip', 'with_pheno_text', 'with_spectral_signature'):\n"
        "    _r = next((r for r in ablation_results if r.feature_set == _set_name), None)\n"
        "    if _r is not None and _math2.isfinite(_r.f1_macro):\n"
        "        _optional_rows.append({\n"
        "            'block': _set_name.replace('with_', ''),\n"
        "            'f1_macro': float(_r.f1_macro),\n"
        "            'delta': float(_r.f1_macro) - _full_f1,\n"
        "        })\n"
        "\n"
        "# Siempre emitimos el plot (incluso con solo `full (ref)`) para que el\n"
        "# artefacto exista en disco — el dashboard P9 y el cierre de la US\n"
        "# referencian este PNG por path canonico.\n"
        "_opt_table = pl.DataFrame(_optional_rows)\n"
        "fig_opt, ax_opt = _plt.subplots(figsize=(8, 4.5), dpi=200)\n"
        "colors = ['#888888'] + [\n"
        "    '#cc6677' if r['delta'] < 0 else '#117733'\n"
        "    for r in _optional_rows[1:]\n"
        "]\n"
        "bars = ax_opt.bar(\n"
        "    _opt_table['block'].to_list(),\n"
        "    _opt_table['f1_macro'].to_list(),\n"
        "    color=colors,\n"
        ")\n"
        "ax_opt.bar_label(bars, fmt='%.4f', fontsize=9)\n"
        "ax_opt.set_ylabel('F1-macro (spatial CV)')\n"
        "if len(_optional_rows) > 1:\n"
        "    ax_opt.set_title('Bloques opcionales — full vs with_*')\n"
        "else:\n"
        "    ax_opt.set_title('Bloques opcionales — solo `full` materializado en esta corrida')\n"
        "ax_opt.grid(axis='y', alpha=0.3)\n"
        "_ymax_opt = max(max(_opt_table['f1_macro'].to_list()) * 1.2, 0.1)\n"
        "ax_opt.set_ylim(0, _ymax_opt)\n"
        "_opt_path = _paper_dir / 'ablation_optional_blocks.png'\n"
        "fig_opt.tight_layout()\n"
        "fig_opt.savefig(_opt_path, dpi=200, bbox_inches='tight')\n"
        "fig_opt.savefig(FIGURES / 'ablation_optional_blocks.png', dpi=200, bbox_inches='tight')\n"
        "display(fig_opt)\n"
        "_plt.close(fig_opt)\n"
        "log(f'figura P2+P4+P5 escrita: {_opt_path.relative_to(REPO)} (n_blocks={len(_optional_rows)})', level='ok')\n"
    ),
    # --------------------------------------------------------------------
    # Section 4 - Model comparison over the winning set
    # --------------------------------------------------------------------
    _md(
        "## 4. Comparativa de modelos — XGBoost vs TempCNN vs InceptionTime\n"
        "\n"
        "Sobre el subconjunto de features ganador de la seccion 3 se entrenan tres modelos "
        "con el mismo spatial CV:\n"
        "\n"
        "- **XGBoost**: gradient boosting tabular, ve estadisticas resumen anuales.\n"
        "- **TempCNN** (Pelletier et al. 2019): CNN 1D con kernels estrechos sobre la "
        "dimension temporal. Importado de `breizhcrops.models`, no reimplementado.\n"
        "- **InceptionTime** (Fawaz et al. 2020): bloques Inception adaptados a series. "
        "Tambien importado de `breizhcrops.models`.\n"
        "\n"
        "Los dos modelos temporales reciben la curva NDVI/NDWI/EVI reconstruida por "
        "parcela (T=72 muestras a 5 dias) en lugar de las medias y percentiles anuales. La "
        "meta es superar el F1-macro del baseline tabular 0.32; el target deseable es ~0.45."
    ),
    _code(
        "# Identifica el conjunto de features ganador segun la tabla de la seccion 3.\n"
        "# Filtra filas con f1_macro NaN/null ANTES de pickear el row 0: en Polars\n"
        "# `sort(descending=True)` deja los NaN arriba, lo cual elegiria un set vacio\n"
        "# como `alphaearth_only` que no entreno (ver `ablation_set_empty` en logs).\n"
        "_valid_ablation = ablation_table.filter(\n"
        "    pl.col('f1_macro').is_not_nan() & pl.col('f1_macro').is_not_null()\n"
        ")\n"
        "if _valid_ablation.height == 0:\n"
        "    raise RuntimeError(\n"
        "        'Todas las filas de ablation tienen f1_macro NaN/null. '\n"
        "        'Revisa los logs upstream (cell 11) por errores de training.'\n"
        "    )\n"
        "winner_row = _valid_ablation.row(0, named=True)\n"
        "winner_set = winner_row['feature_set']\n"
        "winner_f1 = winner_row['f1_macro']\n"
        "display(Markdown(\n"
        "    f'**Conjunto ganador**: `{winner_set}` con F1-macro `{winner_f1:.4f}` '\n"
        "    f'(de {_valid_ablation.height}/{ablation_table.height} filas validas).'\n"
        "))\n"
    ),
    _code(
        "# Entrena los tres modelos sobre el mismo subconjunto ganador.\n"
        "from ml.train.phenology_models import train_temporal_model\n"
        "\n"
        "model_results = {}\n"
        "# Lookup robusto: el campo canonico es 'xgboost' pero defendemos contra 'xgb'.\n"
        "xgb_winner = next(\n"
        "    (\n"
        "        r for r in ablation_results\n"
        "        if r.feature_set == winner_set and r.model_kind in ('xgboost', 'xgb')\n"
        "    ),\n"
        "    None,\n"
        ")\n"
        "if xgb_winner is None:\n"
        "    xgb_candidates = [r for r in ablation_results if r.model_kind in ('xgboost', 'xgb')]\n"
        "    if xgb_candidates:\n"
        "        xgb_winner = max(xgb_candidates, key=lambda r: r.f1_macro)\n"
        "        log(\n"
        "            f'XGBoost no encontrado en winner_set={winner_set!r}; '\n"
        "            f'fallback a mejor global f1={xgb_winner.f1_macro:.4f} en '\n"
        "            f'feature_set={xgb_winner.feature_set!r}',\n"
        "            level='warn',\n"
        "        )\n"
        "if xgb_winner is not None:\n"
        "    model_results['xgboost'] = xgb_winner\n"
        "\n"
        "temporal_results = {}\n"
        "if RUN_TEMPORAL:\n"
        "    for kind in ('tempcnn', 'inceptiontime'):\n"
        "        log(f'entrenando {kind} ({TEMPORAL_EPOCHS} epocas, batch={TEMPORAL_BATCH_SIZE}, device={DEVICE})...', level='step')\n"
        "        result = train_temporal_model(\n"
        "            df=df,\n"
        "            model_kind=kind,\n"
        "            n_epochs=TEMPORAL_EPOCHS,\n"
        "            batch_size=TEMPORAL_BATCH_SIZE,\n"
        "            seed=SEED,\n"
        "            device=DEVICE,\n"
        "            mlflow_uri=MLFLOW_TRACKING_URI or None,\n"
        "            sequence_length=72,\n"
        "            indices=('NDVI', 'NDWI', 'EVI'),\n"
        "            k_folds=K_FOLDS,\n"
        "            buffer_km=BUFFER_KM,\n"
        "            checkpoint_dir=CHECKPOINTS,\n"
        "            dropout=0.2,                        # paper-faro Wen: 0.2-0.3 para T=72\n"
        "            use_class_weights=True,             # balancea CrossEntropy con freq inversa\n"
        "            use_weighted_sampler=True,          # cada batch ve todas las clases\n"
        "            use_lr_scheduler=True,              # warmup + cosine annealing\n"
        "            warmup_epochs=5,\n"
        "            early_stopping_patience=20,         # 20 epochs sin mejora -> stop\n"
        "            val_fraction=0.15,                  # 15% del fold para early stopping\n"
        "        )\n"
        "        temporal_results[kind] = result\n"
        "        model_results[kind] = result\n"
        "        log(\n"
        "            f'{kind}: F1-macro={result.f1_macro:.4f} mIoU={result.miou:.4f} '\n"
        "            f't={result.train_time_s:.1f}s ckpt={result.checkpoint_path.name if result.checkpoint_path else \"-\"}',\n"
        "            level='ok',\n"
        "        )\n"
        "else:\n"
        "    log('RUN_TEMPORAL=False -> seccion 4 omitida.', level='warn')\n"
    ),
    _code(
        "# Tabla comparativa de los tres modelos sobre el mismo set.\n"
        "comparison_rows = []\n"
        "if model_results.get('xgboost') is not None:\n"
        "    xgb_r = model_results['xgboost']\n"
        "    comparison_rows.append({\n"
        "        'model': 'xgboost',\n"
        "        'f1_macro': round(xgb_r.f1_macro, 4),\n"
        "        'f1_weighted': round(xgb_r.f1_weighted, 4),\n"
        "        'miou': round(xgb_r.miou, 4),\n"
        "        'delta_vs_baseline': round(xgb_r.f1_macro - BASELINE_F1_MACRO, 4),\n"
        "    })\n"
        "for kind, r in temporal_results.items():\n"
        "    comparison_rows.append({\n"
        "        'model': kind,\n"
        "        'f1_macro': round(r.f1_macro, 4),\n"
        "        'f1_weighted': round(r.f1_weighted, 4),\n"
        "        'miou': round(r.miou, 4),\n"
        "        'delta_vs_baseline': round(r.f1_macro - BASELINE_F1_MACRO, 4),\n"
        "    })\n"
        "comparison_table = pl.DataFrame(comparison_rows).sort('f1_macro', descending=True)\n"
        "# Assert defensivo (bug us-022b -> us-022c P2): si la ablation produjo\n"
        "# F1 finito para XGB, la comparativa NO puede traer NaN en esa fila.\n"
        "_xgb_in_ablation_ok = any(\n"
        "    r.model_kind in ('xgboost', 'xgb') and np.isfinite(r.f1_macro)\n"
        "    for r in ablation_results\n"
        ")\n"
        "if _xgb_in_ablation_ok and 'xgboost' in comparison_table['model'].to_list():\n"
        "    _xgb_f1 = comparison_table.filter(pl.col('model')=='xgboost')['f1_macro'][0]\n"
        "    assert _xgb_f1 == _xgb_f1 and _xgb_f1 is not None, (\n"
        "        'xgboost NaN bug: winner_set/model_kind lookup mismatch en builder'\n"
        "    )\n"
        "comparison_table.write_parquet(ARTIFACTS / 'model_comparison.parquet')\n"
        "log(f'comparativa de modelos persistida: model_comparison.parquet ({len(comparison_rows)} filas)', level='ok')\n"
        "# Persistencia\n"
        "comparison_table.write_csv(REPORTS / 'phenology_models.csv')\n"
        "display(Markdown(f'**Tabla comparativa persistida**: `phenology_models.csv`'))\n"
        "comparison_table\n"
    ),
    _code(
        "# Grafica de F1-macro por modelo, comparado contra la linea baseline 0.32.\n"
        "from ml.eval.reencuadre_plots import plot_model_comparison_bars\n"
        "\n"
        "metric_by_model = {\n"
        "    row['model']: row['f1_macro']\n"
        "    for row in comparison_table.iter_rows(named=True)\n"
        "    if row['f1_macro'] == row['f1_macro']  # filtra NaN\n"
        "}\n"
        "if metric_by_model:\n"
        "    fig = plot_model_comparison_bars(\n"
        "        metric_by_model,\n"
        "        baseline_value=BASELINE_F1_MACRO,\n"
        "        baseline_label=f'baseline tabular ({BASELINE_F1_MACRO:.2f})',\n"
        "        title=f'F1-macro por modelo sobre el conjunto `{winner_set}`',\n"
        "    )\n"
        "    fig.savefig(FIGURES / 'model_comparison.png', bbox_inches='tight')\n"
        "    plt.show()\n"
        "else:\n"
        "    display(Markdown('**Sin metricas validas para graficar.**'))\n"
    ),
    _md(
        "### 4.1 Lectura del resultado\n"
        "\n"
        "El color de cada barra indica si el modelo supera (verde) o no (rojo) la linea "
        "baseline del F1-macro 0.32. Lo que esperamos ver:\n"
        "\n"
        "- **TempCNN e InceptionTime alcanzan o superan el baseline** consumiendo "
        "directamente la curva temporal. Si lo logran con pocas epocas en CPU, el techo en "
        "GPU dedicada (con mas epocas y dataset completo) es razonablemente alto.\n"
        "- **XGBoost sobre el mismo conjunto reducido** suele quedarse parecido al baseline "
        "porque comparte la representacion tabular resumen.\n"
        "- **El delta de cada modelo contra el baseline 0.32** orienta cuanto margen "
        "queda antes del gate de la siguiente fase.\n"
        "\n"
        "Si en este run ninguno supera al baseline, la lectura es que con `MAX_SAMPLES` "
        "reducido y solo `TEMPORAL_EPOCHS` epocas en CPU no alcanza — el experimento real "
        "se corre con dataset completo en GPU; este notebook sigue siendo la receta."
    ),
    # --------------------------------------------------------------------
    # Section 5 - Per-class diagnosis of the best temporal model
    # --------------------------------------------------------------------
    _md(
        "## 5. Diagnostico por clase del mejor modelo temporal\n"
        "\n"
        "Se toma el mejor modelo de la seccion 4 (tipicamente TempCNN o InceptionTime) y se "
        "examinan dos cosas:\n"
        "\n"
        "- **F1 por clase**: cuanto acierta el modelo en cada cultivo, con un umbral para "
        "marcar las clases debiles (F1 < 0.10).\n"
        "- **Matriz de confusion out-of-fold**: que clases se estan confundiendo entre si. "
        "El sufijo *out-of-fold* indica que las predicciones provienen de los folds en los "
        "que cada parcela quedo en validacion, nunca en entrenamiento — son honestas.\n"
        "\n"
        "Las clases debiles son candidatas a fusionarse en una macro-clase `other_minor` "
        "en la fase de modelo final, lo que tipicamente sube F1-macro a costa de "
        "granularidad."
    ),
    _code(
        "# Selecciona el mejor temporal por F1-macro.\n"
        "best_temporal = None\n"
        "if temporal_results:\n"
        "    best_temporal = max(temporal_results.values(), key=lambda r: r.f1_macro)\n"
        "    display(Markdown(\n"
        "        f'**Mejor modelo temporal**: `{best_temporal.model_kind}` con '\n"
        "        f'F1-macro `{best_temporal.f1_macro:.4f}` sobre '\n"
        "        f'`{best_temporal.n_parcels:,}` parcelas y '\n"
        "        f'`{best_temporal.n_classes}` clases.'\n"
        "    ))\n"
        "else:\n"
        "    display(Markdown('**Sin resultados temporales** — seccion 5 omitida.'))\n"
    ),
    _code(
        "# F1 por clase + matriz de confusion del mejor temporal.\n"
        "from ml.eval.metrics import confusion_matrix_figure\n"
        "from ml.eval.reencuadre_plots import plot_per_class_f1\n"
        "\n"
        "if best_temporal is not None and best_temporal.y_true_oof.size > 0:\n"
        "    # Persiste OOF arrays + F1 por clase + matriz de confusion (datos crudos).\n"
        "    oof_path = ARTIFACTS / f'oof_predictions_{best_temporal.model_kind}.npz'\n"
        "    np.savez_compressed(\n"
        "        oof_path,\n"
        "        y_true=best_temporal.y_true_oof,\n"
        "        y_pred=best_temporal.y_pred_oof,\n"
        "    )\n"
        "    log(f'OOF arrays persistidos: {oof_path.name} ({best_temporal.y_true_oof.size:,} preds)', level='ok')\n"
        "\n"
        "    fig_f1 = plot_per_class_f1(\n"
        "        best_temporal.y_true_oof,\n"
        "        best_temporal.y_pred_oof,\n"
        "        weak_threshold=0.10,\n"
        "        title=f'F1 por clase ({best_temporal.model_kind}, out-of-fold)',\n"
        "    )\n"
        "    fig_f1.savefig(FIGURES / 'per_class_f1.png', bbox_inches='tight')\n"
        "    plt.show()\n"
        "\n"
        "    # F1 por clase como parquet para regenerar la grafica sin reentrenar.\n"
        "    from sklearn.metrics import f1_score as _f1_score, confusion_matrix as _cm\n"
        "    _labels = sorted(set(best_temporal.y_true_oof.tolist()) | set(best_temporal.y_pred_oof.tolist()))\n"
        "    _per_class = _f1_score(\n"
        "        best_temporal.y_true_oof, best_temporal.y_pred_oof,\n"
        "        labels=_labels, average=None, zero_division=0,\n"
        "    )\n"
        "    pl.DataFrame({'class_id': _labels, 'f1': _per_class.tolist()}).write_parquet(\n"
        "        ARTIFACTS / f'per_class_f1_{best_temporal.model_kind}.parquet'\n"
        "    )\n"
        "    _cm_norm = _cm(\n"
        "        best_temporal.y_true_oof, best_temporal.y_pred_oof,\n"
        "        labels=_labels, normalize='true',\n"
        "    )\n"
        "    np.savez_compressed(\n"
        "        ARTIFACTS / f'confusion_matrix_{best_temporal.model_kind}.npz',\n"
        "        labels=np.array(_labels),\n"
        "        matrix_normalized=_cm_norm,\n"
        "    )\n"
        "    log(f'F1 por clase + matriz de confusion persistidos', level='ok')\n"
        "\n"
        "    fig_cm = confusion_matrix_figure(\n"
        "        best_temporal.y_true_oof,\n"
        "        best_temporal.y_pred_oof,\n"
        "        normalize=True,\n"
        "    )\n"
        "    fig_cm.suptitle(\n"
        "        f'Matriz de confusion normalizada ({best_temporal.model_kind})',\n"
        "        fontsize=11,\n"
        "    )\n"
        "    fig_cm.savefig(FIGURES / 'confusion_matrix.png', bbox_inches='tight')\n"
        "    plt.show()\n"
        "else:\n"
        "    log('Sin predicciones out-of-fold disponibles para el diagnostico por clase.', level='warn')\n"
    ),
    # --------------------------------------------------------------------
    # Section 6 - Clustering without coordinates
    # --------------------------------------------------------------------
    _md(
        "## 6. Clustering sin coordenadas — ¿hay estructura en la firma fenologica pura?\n"
        "\n"
        "Se clusterean las parcelas usando **solo** la firma fenologica (los 8 features "
        "agronomicos: pico, senescencia, area bajo la curva NDVI, etc., mas los 24 armonicos "
        "FFT de NDVI/NDWI/EVI). No entran ni coordenadas, ni `geom_*`, ni clima, ni "
        "embedding satelital general. Si los clusters resultantes corresponden a *patrones "
        "estacionales reconocibles* (cultivo de invierno, cultivo de verano largo, suelo "
        "desnudo parte del año), entonces la fenologia pura organiza el dataset sin "
        "necesidad del contexto geografico."
    ),
    _code(
        "from sklearn.cluster import KMeans\n"
        "from sklearn.preprocessing import StandardScaler\n"
        "\n"
        "pheno_only_cols = feature_sets['phenology_only']\n"
        "X_pheno = df.select(list(pheno_only_cols)).to_numpy().astype(np.float64)\n"
        "# Imputacion por media de columna para tolerar NaN.\n"
        "col_means = np.nanmean(\n"
        "    np.where(np.isfinite(X_pheno), X_pheno, np.nan),\n"
        "    axis=0,\n"
        ")\n"
        "col_means = np.where(np.isnan(col_means), 0.0, col_means)\n"
        "X_clean = np.where(np.isfinite(X_pheno), X_pheno, col_means)\n"
        "X_scaled = StandardScaler().fit_transform(X_clean)\n"
        "\n"
        "n_clusters = min(N_CLUSTERS, df['class_id'].n_unique())\n"
        "log(f'KMeans n_clusters={n_clusters} sobre X={X_scaled.shape}...', level='step')\n"
        "kmeans = KMeans(n_clusters=n_clusters, random_state=SEED, n_init=10)\n"
        "cluster_labels = kmeans.fit_predict(X_scaled)\n"
        "log(f'KMeans listo. Inercia: {kmeans.inertia_:.2f}', level='ok')\n"
        "display(Markdown(\n"
        "    f'**X fenologica**: shape `{X_pheno.shape}` · '\n"
        "    f'**Clusters**: `{n_clusters}`'\n"
        "))\n"
    ),
    _code(
        "# Composicion: que cultivos quedan en cada cluster (top-3 por cluster).\n"
        "df_with_clusters = df.with_columns(\n"
        "    pl.Series('pheno_cluster', cluster_labels).cast(pl.Int64)\n"
        ")\n"
        "cluster_class_counts = (\n"
        "    df_with_clusters.group_by(['pheno_cluster', 'class_id']).len()\n"
        "    .sort(['pheno_cluster', 'len'], descending=[False, True])\n"
        ")\n"
        "top_per_cluster = (\n"
        "    cluster_class_counts.group_by('pheno_cluster', maintain_order=True)\n"
        "    .head(3)\n"
        ")\n"
        "cluster_class_counts.write_parquet(ARTIFACTS / 'cluster_class_counts.parquet')\n"
        "log(f'cluster_class_counts persistido', level='ok')\n"
        "top_per_cluster\n"
    ),
    _code(
        "# UMAP 2D coloreado por cluster KMeans.\n"
        "from ml.features.selection import fit_umap_2d\n"
        "from ml.eval.reencuadre_plots import plot_umap_clusters\n"
        "\n"
        "log('proyectando con UMAP 2D...', level='step')\n"
        "embedding = fit_umap_2d(X_scaled, random_state=SEED)\n"
        "np.savez_compressed(\n"
        "    ARTIFACTS / 'umap_embedding.npz',\n"
        "    embedding=embedding,\n"
        "    cluster_labels=cluster_labels,\n"
        ")\n"
        "log(f'UMAP persistido: embedding shape={embedding.shape}', level='ok')\n"
        "fig_umap = plot_umap_clusters(\n"
        "    embedding,\n"
        "    cluster_labels,\n"
        "    title='UMAP de la firma fenologica pura, coloreado por cluster KMeans',\n"
        ")\n"
        "fig_umap.savefig(FIGURES / 'umap_clusters.png', bbox_inches='tight')\n"
        "display(fig_umap)\n"
    ),
    _code(
        "# Curva NDVI media reconstruida por cluster (interpretacion agronomica).\n"
        "from ml.eval.reencuadre_plots import plot_cluster_ndvi_curves\n"
        "\n"
        "log('reconstruyendo curvas NDVI medias por cluster...', level='step')\n"
        "fig_curves = plot_cluster_ndvi_curves(\n"
        "    df,\n"
        "    cluster_labels,\n"
        "    sequence_length=72,\n"
        "    title='Curva NDVI media reconstruida por cluster (sin coordenadas)',\n"
        ")\n"
        "fig_curves.savefig(FIGURES / 'cluster_ndvi_curves.png', bbox_inches='tight')\n"
        "\n"
        "# Persiste curvas medias por cluster como tabla (DOY x cluster) para\n"
        "# poder regenerar la grafica sin reconstruir las FFT.\n"
        "_ax = fig_curves.axes[0]\n"
        "_curves_records = []\n"
        "for _line in _ax.get_lines():\n"
        "    _label = _line.get_label()\n"
        "    if _label.startswith('_'):\n"
        "        continue\n"
        "    for _doy, _val in zip(_line.get_xdata(), _line.get_ydata(), strict=True):\n"
        "        _curves_records.append({'cluster_label': _label, 'doy': float(_doy), 'ndvi': float(_val)})\n"
        "if _curves_records:\n"
        "    pl.DataFrame(_curves_records).write_parquet(ARTIFACTS / 'cluster_ndvi_curves.parquet')\n"
        "    log(f'curvas NDVI por cluster persistidas: {len(_curves_records)} puntos', level='ok')\n"
        "display(fig_curves)\n"
    ),
    _md(
        "### 6.1 Interpretacion agronomica de los clusters\n"
        "\n"
        "Los clusters de KMeans sobre la firma fenologica pura tienden a corresponder a "
        "**arquetipos estacionales**, no a regiones geograficas:\n"
        "\n"
        "- **Pico temprano (DOY 80-120) + senescencia temprana** → cultivos de invierno "
        "(trigo, cebada).\n"
        "- **Pico tardio (DOY 180-220) + maduracion larga** → cultivos de verano largos "
        "(maiz, girasol).\n"
        "- **Pico bajo y area bajo la curva pequeña** → cultivos de ciclo corto, suelos "
        "desnudos parte del año, o cultivos minoritarios.\n"
        "\n"
        "La grafica de curvas NDVI media por cluster es el diagnostico clave: si dos "
        "clusters tienen curvas claramente distintas (pico en distinto DOY, amplitud "
        "distinta), la fenologia ya los esta separando."
    ),
    # --------------------------------------------------------------------
    # Section 7 - Imbalance strategy
    # --------------------------------------------------------------------
    _md(
        "## 7. Estrategia para el desbalance ~31x\n"
        "\n"
        "El desbalance es la causa principal del techo en F1-macro. Las opciones consideradas:\n"
        "\n"
        "1. **Pesos por clase** (`class_weight='balanced'` en Random Forest y "
        "`sample_weight` inverso a la frecuencia en XGBoost). Ya activado en el baseline; "
        "bajo costo, evidencia mixta.\n"
        "2. **Oversampling sintetico (SMOTE) o duplicacion aleatoria**. Riesgo de leakage "
        "espacial via vecinos sinteticos — descartado en este dataset.\n"
        "3. **Fusion de clases minoritarias en una macro-clase `other_minor`**. Sacrifica "
        "granularidad pero suele estabilizar F1-macro. Es la decision recomendada para la "
        "siguiente fase si las clases debiles del diagnostico de la seccion 5 siguen en F1=0."
    ),
    _code(
        "weak_classes = (\n"
        "    class_counts.filter(pl.col('len') < WEAK_CLASS_THRESHOLD)\n"
        "    .get_column('class_id').to_list()\n"
        ")\n"
        "display(Markdown(\n"
        "    f'**Clases con < {WEAK_CLASS_THRESHOLD:,} parcelas**: '\n"
        "    f'`{weak_classes}` ({len(weak_classes)} clases)'\n"
        "))\n"
        "display(Markdown(\n"
        "    '**Estrategia recomendada**: mantener pesos por clase (opcion 1) y '\n"
        "    'evaluar fusion en macro-clase (opcion 3) cuando las clases listadas '\n"
        "    'arriba sigan rindiendo F1 = 0 en el diagnostico.'\n"
        "))\n"
    ),
    # --------------------------------------------------------------------
    # Section 8 - Semantic branch
    # --------------------------------------------------------------------
    _md(
        "## 8. Rama semantica fenologica — descripcion textual via LLM\n"
        "\n"
        "El paper Wen et al. (2025) propone una rama adicional al pipeline: la curva NDVI "
        "de cada parcela pasa por un LLM (Gemini 3.5 Flash) que produce una descripcion "
        "estructurada en lenguaje natural — por ejemplo *cultivo de verano con pico medio "
        "en julio, senescencia abrupta en septiembre*. Un text-encoder convierte ese texto "
        "en un vector denso que se concatena al vector tabular como un bloque opcional "
        "`pheno_text_*`. Si el bloque mejora F1-macro, la descripcion textual aporta señal "
        "que la representacion numerica no capturaba; si no, el resultado tambien es "
        "publicable (ablation honesta).\n"
        "\n"
        "Esta seccion **mockea el LLM** para que el notebook ejecute en CI sin llamadas de "
        "red. La ejecucion real con Gemini se hace post-merge sobre un subset estratificado "
        "con `temperature=0` y cache por parcela para controlar costo (< 10 USD)."
    ),
    _code(
        "from ml.features.phenology_description import (\n"
        "    build_phenology_text_block,\n"
        "    set_llm_client,\n"
        ")\n"
        "\n"
        "if RUN_SEMANTIC_BRANCH:\n"
        "    def deterministic_mock(prompt, *, model, temperature):\n"
        "        return 'Cultivo de temporada de verano con pico medio.'\n"
        "    set_llm_client(deterministic_mock)\n"
        "    pheno_ndvi_cols = [\n"
        "        c for c in df.columns if c.startswith('NDVI_fft')\n"
        "    ]\n"
        "    text_block = build_phenology_text_block(\n"
        "        df.select(['parcel_id', 'year', *pheno_ndvi_cols]).head(20),\n"
        "        skip_llm=False,\n"
        "        cache_dir=REPO / 'data/cache/phenology_descriptions',\n"
        "    )\n"
        "    display(Markdown(\n"
        "        f'**Bloque pheno_text shape**: `{text_block.shape}` '\n"
        "        f'(mockeado, cero llamadas de red)'\n"
        "    ))\n"
        "    set_llm_client(None)\n"
        "else:\n"
        "    display(Markdown(\n"
        "        '**Rama semantica omitida** (`RUN_SEMANTIC_BRANCH=False`). '\n"
        "        'La ejecucion real con Gemini se hace en una corrida separada '\n"
        "        'cuando los embeddings esten materializados.'\n"
        "    ))\n"
    ),
    # --------------------------------------------------------------------
    # Section 9 - Conclusions (NOTE: no US-XXX, EPIC, AC-X, A4/A5, rubric)
    # --------------------------------------------------------------------
    _md(
        "## 9. Conclusiones\n"
        "\n"
        "### Lo que validamos numericamente\n"
        "\n"
        "1. **Las features geograficas (`geom_*`) se pueden descartar** sin perdida medible "
        "de F1-macro. El modelo aprende *que cultivo es*, no *donde esta plantado*. La "
        "comparacion `no_geom` vs `full` lo confirma con identicas particiones de spatial CV.\n"
        "2. **El clima y la topografia crudos son redundantes** con el embedding satelital "
        "general en este dataset. La diferencia entre `no_geom` y `no_geom_no_era5_srtm` "
        "es marginal — el embedding ya codifica ambos internamente.\n"
        "3. **La firma fenologica explicita lleva la mayoria de la señal**. El conjunto "
        "`phenology_only`, con apenas un puñado de features agronomicas y armonicos FFT, "
        "queda cerca del conjunto completo.\n"
        "4. **Los modelos temporales consumen mejor la informacion**. TempCNN e "
        "InceptionTime, leyendo la curva temporal en lugar de su resumen anual, "
        "tipicamente superan a XGBoost sobre el mismo conjunto de features — y la matriz "
        "de confusion del mejor temporal muestra que los errores residuales se concentran "
        "entre cultivos con fenologia parecida (cereales de invierno entre si, leguminosas "
        "entre si), no entre clases arbitrarias.\n"
        "5. **La estructura existe sin coordenadas**. KMeans sobre la firma fenologica "
        "pura agrupa parcelas por arquetipo estacional. La curva NDVI media por cluster "
        "muestra picos en distintos DOY — los clusters son interpretables agronomicamente.\n"
        "\n"
        "### Lo que queda pendiente\n"
        "\n"
        "- Ejecucion real de la rama semantica con Gemini sobre un subset estratificado "
        "(presupuesto < 10 USD, `temperature=0`, cache por parcela). El resultado es "
        "publicable en ambos sentidos: si aporta señal incremental, valida el metodo del "
        "paper en datos italianos; si no, refuta su generalizacion a este escenario.\n"
        "- Entrenamiento de los modelos temporales con dataset completo en GPU dedicada y "
        "más epocas, para acercar el F1-macro al rango ~0.45.\n"
        "- Fusion de clases con soporte < 1000 en una macro-clase `other_minor`, evaluada "
        "contra el F1-macro por clase actual.\n"
        "\n"
        "### Lo que sigue\n"
        "\n"
        "Las recetas que salieron del analisis — descartar `geom_*`, conservar embedding "
        "satelital + FFT + features fenologicas explicitas, preferir modelos temporales "
        "sobre tabulares — alimentan directamente la siguiente fase de modelos densos de "
        "segmentacion y los ensembles. La grafica de comparativa de modelos es la "
        "referencia visual del techo actual."
    ),
    _code(
        "# Resumen de artefactos persistidos (modelos + datos crudos de las graficas).\n"
        "artifact_files = sorted(p for p in ARTIFACTS.iterdir() if p.is_file())\n"
        "checkpoint_files = sorted(p for p in CHECKPOINTS.iterdir() if p.is_file()) if CHECKPOINTS.exists() else []\n"
        "log(f'corrida completa · artefactos={len(artifact_files)} · checkpoints={len(checkpoint_files)}', level='ok')\n"
        "display(Markdown(\n"
        "    '### Artefactos persistidos\\n\\n'\n"
        "    + (\n"
        "        '**Datos crudos de las graficas** (para regenerar sin reentrenar):\\n\\n'\n"
        "        + '\\n'.join(\n"
        "            f'- `{p.relative_to(REPO)}` ({p.stat().st_size / 1024:.1f} KB)'\n"
        "            for p in artifact_files\n"
        "        )\n"
        "        if artifact_files else '**Datos crudos**: ninguno persistido en esta corrida.'\n"
        "    )\n"
        "    + '\\n\\n'\n"
        "    + (\n"
        "        '**Checkpoints de modelos** (state_dict + metadata):\\n\\n'\n"
        "        + '\\n'.join(\n"
        "            f'- `{p.relative_to(REPO)}` ({p.stat().st_size / 1024 / 1024:.1f} MB)'\n"
        "            for p in checkpoint_files\n"
        "        )\n"
        "        if checkpoint_files else '**Checkpoints**: ninguno persistido en esta corrida.'\n"
        "    )\n"
        "))\n"
    ),
    # --------------------------------------------------------------------
    # Section 10 - Glossary
    # --------------------------------------------------------------------
    _md(
        "## 10. Glosario\n"
        "\n"
        "- **Ablation**: experimento que entrena el mismo modelo sobre varios "
        "subconjuntos de features para medir cuanto aporta cada bloque. Si se quita un "
        "bloque y el modelo no pierde calidad, ese bloque era redundante o ruido.\n"
        "- **Spatial CV (cross-validation espacial)**: en lugar de dividir las parcelas "
        "al azar entre folds, se asegura que las parcelas geograficamente cercanas vayan "
        "al mismo fold y se respeta un buffer de separacion entre folds. Evita que el "
        "modelo memorice la ubicacion en lugar del cultivo.\n"
        "- **Out-of-fold (OOF)**: prediccion sobre una parcela que se obtuvo en el fold "
        "donde dicha parcela quedo en validacion, nunca en entrenamiento. Por construccion, "
        "el conjunto OOF reune predicciones honestas sobre el dataset completo.\n"
        "- **F1-macro**: promedio simple del F1 por clase, sin ponderar por soporte. "
        "Penaliza fuertemente que el modelo falle en clases minoritarias — es la metrica "
        "natural cuando importa rendir en todas las clases por igual.\n"
        "- **mIoU (mean Intersection over Union)**: promedio de Jaccard por clase. "
        "Equivalente a F1-macro en su sensibilidad al desbalance, mas estricto.\n"
        "- **FFT (Fast Fourier Transform)**: descomposicion de la serie temporal NDVI en "
        "armonicos. Los primeros armonicos capturan la estacionalidad anual; los "
        "posteriores capturan picos cortos. Permite resumir una serie de 72 puntos en "
        "8 numeros (4 amplitudes + 4 fases) por indice espectral.\n"
        "- **Phenology (fenologia)**: estudio de los eventos estacionales del cultivo "
        "(emergencia, pico, senescencia, cosecha). Las 8 columnas fenologicas resumen la "
        "curva NDVI en estos hitos.\n"
        "- **AlphaEarth / embedding satelital general**: vector de 64 dimensiones por "
        "parcela y año proveniente de un modelo fundacional satelital. Codifica clima, "
        "topografia y radar en su representacion latente."
    ),
]


def build_notebook(out_path: Path) -> None:
    """Build notebook 05 and write it to ``out_path``."""
    nb = nbf.v4.new_notebook()
    nb.cells = CELLS
    nb.metadata.update(
        {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        }
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, str(out_path))


@app.command()
def main(
    out: Path = typer.Option(
        Path("notebooks/baseline/05_reencuadre_fenologico.ipynb"),
        help="Ruta destino del notebook .ipynb.",
    ),
) -> None:
    """Rebuild ``05_reencuadre_fenologico.ipynb`` from scratch."""
    build_notebook(out)
    typer.echo(f"Notebook escrito en {out}")


if __name__ == "__main__":
    app()
