"""Build notebooks/eda/02e_eda_metodos_paper.ipynb (permanent Typer CLI).

Reusable permanent operational tool: regenerates the .ipynb from a declarative
cell definition to keep the canonical structure of the project's EDA notebooks.
The resulting notebook applies the 8 methods derived from 4 papers
(``ml.analysis.paper_methods``) over real PASTIS-R data, with a synthetic
fallback if the dataset is not present.

The actual execution (populating outputs) is done afterwards with papermill:

    MPLBACKEND=Agg poetry run papermill \\
        notebooks/eda/02e_eda_metodos_paper.ipynb \\
        notebooks/eda/02e_eda_metodos_paper.ipynb --no-progress-bar
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf
import typer

app = typer.Typer(add_completion=False)


def _md(source: str) -> nbf.NotebookNode:
    """Create a markdown cell."""
    return nbf.v4.new_markdown_cell(source)


def _code(source: str, tags: list[str] | None = None) -> nbf.NotebookNode:
    """Create a code cell with optional tags."""
    cell = nbf.v4.new_code_cell(source.strip("\n"))
    if tags:
        cell.metadata["tags"] = tags
    return cell


CELLS: list[nbf.NotebookNode] = [
    _md(
        "# EDA avanzado — métodos derivados de la literatura\n"
        "\n"
        "Este notebook traslada a código reproducible ocho métodos de análisis\n"
        "exploratorio y de ingeniería de características extraídos de la lectura\n"
        "completa de cuatro publicaciones de teledetección agrícola. Cada método\n"
        "vive en `ml/analysis/paper_methods.py`, está cubierto por pruebas\n"
        "automatizadas y se demuestra aquí sobre datos PASTIS-R reales.\n"
        "\n"
        "La pregunta que responde el notebook es concreta: ¿qué técnicas de la\n"
        "literatura reciente aportan diagnósticos útiles sobre nuestros datos\n"
        "antes de entrenar modelos, y qué nos dicen esos diagnósticos?\n"
        "\n"
        "## Las cuatro publicaciones de referencia\n"
        "\n"
        "Dos son artículos clásicos de referencia del área, dos son\n"
        "publicaciones recientes que confirman y extienden esas técnicas:\n"
        "\n"
        "- **Artículo A — Rußwurm y Körner (2018)**, *Multi-Temporal Land Cover\n"
        "  Classification with Sequential Recurrent Encoders*. ISPRS IJGI\n"
        "  7(4):129, arXiv:1802.02080. Aporta: profundidad de características\n"
        "  d=15, preprocesamiento mínimo, kappa de Cohen para clases\n"
        "  desbalanceadas, análisis de confusiones simétricas/asimétricas y\n"
        "  agregación de clases raras por umbral de frecuencia.\n"
        "- **Artículo B — Tarasiou, Güler y Zafeiriou (2021)**, *Context-self\n"
        "  contrastive pretraining for crop type semantic segmentation*. IEEE\n"
        "  TGRS, arXiv:2104.04310. Aporta: la varianza espectral de una parcela\n"
        "  proviene casi enteramente de sus píxeles de frontera (Fig. 2); el\n"
        "  cuello de botella de la segmentación está en los bordes.\n"
        "- **Artículo C — Phenology-Aware Transformer / PVM (2025)**. Remote\n"
        "  Sensing 17(14):2346. Aporta: el *calendario de crecimiento del\n"
        "  cultivo*, una codificación de las etapas fenológicas por clase de\n"
        "  cultivo indexada por día del año.\n"
        "- **Artículo D — Qin et al. (2025)**, *Spatiotemporal masked\n"
        "  pre-training for advancing crop mapping on satellite image time\n"
        "  series with limited labels (STCLN)*. Int. J. Applied Earth Obs.\n"
        "  Geoinf. Aporta: el enmascaramiento espaciotemporal como técnica para\n"
        "  aprender (y aquí, para auditar) la robustez ante huecos de nubes.\n"
        "\n"
        "## Requisitos para ejecución end-to-end\n"
        "\n"
        "- `poetry install --with ml,dev,test` ejecutado.\n"
        "- Dataset `data/PASTIS-R/` presente (auto-detectado). Si falta, el\n"
        "  notebook degrada a un patch sintético equivalente y completa la\n"
        "  ejecución sin error ni acceso a red.\n"
        "\n"
        "Secciones:\n"
        "\n"
        "0. Preparación del entorno e introducción\n"
        "1. Análisis interior-vs-frontera de parcela (Artículo B)\n"
        "2. Irregularidad de revisita temporal (Artículo A)\n"
        "3. Confusiones simétricas vs asimétricas (Artículo A)\n"
        "4. Calendario fenológico (Artículo C)\n"
        "5. Robustez ante huecos de nubes (Artículo D)\n"
        "6. Conclusiones\n"
    ),
    _code(
        "n_pastis_patches = 4\nseed = 42\n",
        tags=["parameters"],
    ),
    _md("## 0. Preparación del entorno e introducción"),
    _code(
        "from __future__ import annotations\n"
        "\n"
        "import os\n"
        "os.environ.setdefault('MPLBACKEND', 'Agg')\n"
        "\n"
        "import sys\n"
        "from pathlib import Path\n"
        "\n"
        "import matplotlib\n"
        "matplotlib.use('Agg')\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import polars as pl\n"
        "import structlog\n"
        "import xarray as xr\n"
        "from IPython.display import Image, Markdown, display\n"
        "\n"
        "from ml.utils.notebook_setup import find_repo_root\n"
        "\n"
        "REPO_ROOT = find_repo_root(Path.cwd())\n"
        "sys.path.insert(0, str(REPO_ROOT))\n"
        "\n"
        "from ml.analysis.paper_methods import (\n"
        "    aggregate_rare_classes,\n"
        "    boundary_interior_stats,\n"
        "    boundary_pixel_mask,\n"
        "    cloud_gap_robustness,\n"
        "    compute_boundary_ratio,\n"
        "    confusion_symmetry_analysis,\n"
        "    phenology_calendar_features,\n"
        "    temporal_sampling_stats,\n"
        ")\n"
        "from ml.features.temporal_features import extract_temporal_features\n"
        "from ml.ingest.pastis_loader import (\n"
        "    PASTIS_CLASS_MAP,\n"
        "    load_pastis_patch,\n"
        "    pastis_patch_index,\n"
        ")\n"
        "\n"
        "%load_ext autoreload\n"
        "%autoreload 2\n"
        "\n"
        "pl.Config.set_tbl_formatting('ASCII_MARKDOWN')\n"
        "pl.Config.set_tbl_rows(25)\n"
        "pl.Config.set_fmt_str_lengths(60)\n"
        "plt.rcParams['figure.dpi'] = 110\n"
        "plt.rcParams['savefig.dpi'] = 150\n"
        "\n"
        "log = structlog.get_logger('eda_paper_methods')\n"
        "\n"
        "FIGURES_DIR = REPO_ROOT / 'reports' / 'paper_methods'\n"
        "FIGURES_DIR.mkdir(parents=True, exist_ok=True)\n"
        "\n"
        "PASTIS_ROOT = REPO_ROOT / 'data' / 'PASTIS-R'\n"
        "HAS_PASTIS = (PASTIS_ROOT / 'DATA_S2').exists()\n"
        "MODE = 'real' if HAS_PASTIS else 'synthetic'\n"
        "display(Markdown(\n"
        "    f'**Modo de datos**: `{MODE}`  \\n'\n"
        "    f'**PASTIS-R detectado**: `{HAS_PASTIS}` en '\n"
        "    f'`{PASTIS_ROOT.relative_to(REPO_ROOT)}`'\n"
        "))\n"
    ),
    _code(
        "# Fixture sintetica reutilizable: patch PASTIS-like con 2 parcelas + fondo.\n"
        "def make_synthetic_patch(size: int = 32, n_timesteps: int = 6, seed_: int = 42) -> dict:\n"
        '    """Construye un patch PASTIS-like determinista para el modo degradado."""\n'
        "    rng = np.random.default_rng(seed_)\n"
        "    half = size // 2\n"
        "    semantic = np.zeros((size, size), dtype=np.uint8)\n"
        "    semantic[:half, :half] = 2\n"
        "    semantic[half:, half:] = 5\n"
        "    instance = np.zeros((size, size), dtype=np.int16)\n"
        "    instance[:half, :half] = 1\n"
        "    instance[half:, half:] = 2\n"
        "    s2 = rng.normal(1000.0, 60.0, size=(n_timesteps, 10, size, size))\n"
        "    s2[:, 6, :half, :half] += 3000.0\n"
        "    s2[:, 6, half:, half:] += 600.0\n"
        "    return {\n"
        "        's2': s2.astype(np.int16),\n"
        "        'semantic': semantic,\n"
        "        'instance': instance,\n"
        "        'zone': np.zeros((size, size), dtype=np.uint8),\n"
        "        'dates_s2': [20190101 + i * 100 for i in range(n_timesteps)],\n"
        "        'patch_id': 'synthetic',\n"
        "        'fold': 1,\n"
        "    }\n"
        "\n"
        "# Seleccion de patches reales (o sintetico de respaldo).\n"
        "if HAS_PASTIS:\n"
        "    idx = pastis_patch_index(PASTIS_ROOT / 'metadata.geojson')\n"
        "    patch_ids = idx.get_column('patch_id').to_list()[:n_pastis_patches]\n"
        "    patches = [load_pastis_patch(pid, root=PASTIS_ROOT) for pid in patch_ids]\n"
        "    display(Markdown(f'**Patches PASTIS-R cargados**: `{patch_ids}`'))\n"
        "else:\n"
        "    patches = [make_synthetic_patch(seed_=seed + i) for i in range(n_pastis_patches)]\n"
        "    display(Markdown(\n"
        "        f'**Patches sintéticos generados**: `{len(patches)}` (modo degradado)'\n"
        "    ))\n"
        "\n"
        "primary_patch = patches[0]\n"
        "display(Markdown(\n"
        "    f'Patch primario `{primary_patch[\"patch_id\"]}` — dimensiones S2 '\n"
        "    f'`{tuple(primary_patch[\"s2\"].shape)}`, '\n"
        "    f'`{len(primary_patch[\"dates_s2\"])}` fechas de adquisición.'\n"
        "))\n"
    ),
    _md(
        "## 1. Análisis interior-vs-frontera de parcela (Artículo B)\n"
        "\n"
        "Tarasiou et al. 2021 (arXiv:2104.04310) muestran en su Figura 2 que la\n"
        "varianza espectral de una parcela agrícola no se reparte de forma\n"
        "homogénea: los píxeles **interiores** son espectralmente uniformes,\n"
        "mientras que los píxeles de **frontera** concentran casi toda la\n"
        "dispersión. Esto explica por qué el cuello de botella de la\n"
        "segmentación de cultivos está en los bordes de parcela.\n"
        "\n"
        "Replicamos su análisis con dos funciones: `boundary_pixel_mask`\n"
        "clasifica cada píxel de un patch PASTIS-R en `interior / frontera /\n"
        "exterior`, y `boundary_interior_stats` calcula los estadísticos\n"
        "espectrales por grupo. Comparamos los histogramas de la banda B08\n"
        "(infrarrojo cercano) de los tres grupos.\n"
    ),
    _code(
        "# Estadisticos descriptivos por grupo (B08 NIR = band_index 6).\n"
        "bi_stats = boundary_interior_stats(primary_patch, band_index=6, neighbourhood=3)\n"
        "display(Markdown(\n"
        "    '**Estadísticos de B08 por grupo de píxel** (réplica de la Fig. 2 '\n"
        "    'de Tarasiou et al. 2021)'\n"
        "))\n"
        "display(bi_stats)\n"
        "\n"
        "interior_std = bi_stats.filter(pl.col('group') == 'interior').get_column('std')[0]\n"
        "boundary_std = bi_stats.filter(pl.col('group') == 'boundary').get_column('std')[0]\n"
        "if interior_std and interior_std > 0:\n"
        "    bi_ratio = boundary_std / interior_std\n"
        "    ratio_txt = f'{bi_ratio:.2f}x'\n"
        "    if bi_ratio >= 1.15:\n"
        "        bi_reading = (\n"
        "            'la frontera concentra claramente más dispersión que el '\n"
        "            'interior, en línea con la Fig. 2 del artículo: los bordes '\n"
        "            'de parcela son la zona espectralmente más heterogénea.'\n"
        "        )\n"
        "    elif bi_ratio >= 0.95:\n"
        "        bi_reading = (\n"
        "            'frontera e interior tienen una dispersión comparable en '\n"
        "            'este patch concreto; el efecto descrito en la Fig. 2 del '\n"
        "            'artículo se aprecia mejor agregando muchos patches.'\n"
        "        )\n"
        "    else:\n"
        "        bi_reading = (\n"
        "            'en este patch la frontera es algo más uniforme que el '\n"
        "            'interior. El efecto descrito en la Fig. 2 del artículo es '\n"
        "            'una tendencia estadística sobre el conjunto completo, no '\n"
        "            'una regla que se cumpla patch a patch.'\n"
        "        )\n"
        "else:\n"
        "    ratio_txt = 'n/a'\n"
        "    bi_reading = 'sin píxeles interiores suficientes para comparar.'\n"
        "display(Markdown(\n"
        "    f'La desviación estándar de B08 en la **frontera** es `{ratio_txt}` '\n"
        "    f'la del **interior** — {bi_reading}'\n"
        "))\n"
    ),
    _code(
        "# Histogramas de B08 para los 3 conjuntos de pixeles (estilo Fig. 2).\n"
        "s2 = np.asarray(primary_patch['s2'], dtype=np.float64)\n"
        "semantic = np.asarray(primary_patch['semantic'])\n"
        "band_map = s2[:, 6, :, :].mean(axis=0)\n"
        "\n"
        "boundary = boundary_pixel_mask(semantic, neighbourhood=3)\n"
        "is_parcel = semantic > 0\n"
        "vals_interior = band_map[is_parcel & ~boundary]\n"
        "vals_boundary = band_map[boundary & is_parcel]\n"
        "vals_exterior = band_map[~is_parcel]\n"
        "\n"
        "fig, axes = plt.subplots(1, 3, figsize=(14, 4), sharey=True)\n"
        "specs = [\n"
        "    ('Interior de parcela', vals_interior, '#2ca02c'),\n"
        "    ('Frontera de parcela', vals_boundary, '#d62728'),\n"
        "    ('Exterior (fondo)', vals_exterior, '#7f7f7f'),\n"
        "]\n"
        "for ax, (title, vals, color) in zip(axes, specs):\n"
        "    if vals.size > 0:\n"
        "        ax.hist(vals, bins=40, color=color, alpha=0.85)\n"
        "        ax.axvline(float(np.mean(vals)), color='black', linestyle='--', linewidth=1)\n"
        "    ax.set_title(f'{title}\\n(n={vals.size})')\n"
        "    ax.set_xlabel('B08 infrarrojo cercano (reflectancia)')\n"
        "    ax.grid(alpha=0.3)\n"
        "axes[0].set_ylabel('Frecuencia')\n"
        "fig.suptitle(\n"
        "    'Distribución de B08 por conjunto de píxeles '\n"
        "    '(réplica de la Fig. 2, Tarasiou et al. 2021)'\n"
        ")\n"
        "plt.tight_layout()\n"
        "hist_png = FIGURES_DIR / 'boundary_interior_histograms.png'\n"
        "fig.savefig(hist_png, dpi=130, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(hist_png)))\n"
    ),
    _code(
        "# Feature nuevo por parcela: ratio frontera / total (compute_boundary_ratio).\n"
        "ratio_rows = []\n"
        "for patch in patches:\n"
        "    ratios = compute_boundary_ratio(patch, neighbourhood=3)\n"
        "    for inst_id, ratio in ratios.items():\n"
        "        ratio_rows.append({\n"
        "            'patch_id': str(patch['patch_id']),\n"
        "            'instance_id': inst_id,\n"
        "            'boundary_ratio': ratio,\n"
        "        })\n"
        "ratio_df = pl.DataFrame(ratio_rows) if ratio_rows else pl.DataFrame(\n"
        "    schema={'patch_id': pl.Utf8, 'instance_id': pl.Int64, 'boundary_ratio': pl.Float64}\n"
        ")\n"
        "ratio_csv = FIGURES_DIR / 'boundary_ratio_per_parcel.csv'\n"
        "ratio_df.write_csv(ratio_csv)\n"
        "if ratio_df.height > 0:\n"
        "    mean_ratio = float(ratio_df.get_column('boundary_ratio').mean())\n"
        "    display(Markdown(\n"
        "        f'**Proporción frontera/total por parcela** ({ratio_df.height} '\n"
        "        f'instancias). Media: `{mean_ratio:.3f}`. Las parcelas pequeñas o '\n"
        "        f'irregulares tienen una proporción alta, lo que las vuelve más '\n"
        "        f'difíciles de segmentar. Guardado en '\n"
        "        f'`{ratio_csv.relative_to(REPO_ROOT)}`.'\n"
        "    ))\n"
        "    display(ratio_df.sort('boundary_ratio', descending=True).head(10))\n"
        "else:\n"
        "    display(Markdown(\n"
        "        'Sin instancias de parcela detectadas en los patches cargados.'\n"
        "    ))\n"
    ),
    _md(
        "## 2. Irregularidad de revisita temporal (Artículo A)\n"
        "\n"
        "Rußwurm y Körner 2018 (arXiv:1802.02080) defienden un preprocesamiento\n"
        "mínimo: sin corrección atmosférica ni máscara de nubes, tratando la\n"
        "nube como ruido temporal y filtrando solo los productos con más del\n"
        "80% de cobertura nubosa. La consecuencia directa es que la serie\n"
        "Sentinel-2 queda con una revisita **irregular**: los intervalos entre\n"
        "imágenes válidas no son constantes. La función `temporal_sampling_stats`\n"
        "cuantifica esa irregularidad midiendo los huecos entre adquisiciones y\n"
        "la fracción del calendario anual que queda cubierta.\n"
    ),
    _code(
        "# Estadisticos de muestreo temporal por patch.\n"
        "sampling_rows = []\n"
        "for patch in patches:\n"
        "    stats = temporal_sampling_stats(patch['dates_s2'])\n"
        "    sampling_rows.append({'patch_id': str(patch['patch_id']), **stats})\n"
        "sampling_df = pl.DataFrame(sampling_rows)\n"
        "display(Markdown(\n"
        "    '**Estadísticos de revisita temporal por patch.** '\n"
        "    '`mean_gap_days` es el intervalo medio entre imágenes; '\n"
        "    '`doy_coverage` es la fracción del año con observaciones.'\n"
        "))\n"
        "display(sampling_df)\n"
    ),
    _code(
        "# Distribucion de gaps entre adquisiciones del patch primario.\n"
        "dates = sorted(int(d) for d in primary_patch['dates_s2'] if int(d) > 0)\n"
        "if len(dates) >= 2:\n"
        "    days = np.array([\n"
        "        (np.datetime64(f'{d:08d}'[:4] + '-' + f'{d:08d}'[4:6] + '-' + f'{d:08d}'[6:8])\n"
        "         - np.datetime64('2000-01-01')) / np.timedelta64(1, 'D')\n"
        "        for d in dates\n"
        "    ])\n"
        "    gaps = np.diff(days)\n"
        "    fig, ax = plt.subplots(figsize=(10, 4))\n"
        "    ax.bar(range(len(gaps)), gaps, color='#1f77b4')\n"
        "    ax.axhline(float(np.mean(gaps)), color='red', linestyle='--',\n"
        "               label=f'gap medio {np.mean(gaps):.1f} d')\n"
        "    ax.set_xlabel('Índice de intervalo entre adquisiciones consecutivas')\n"
        "    ax.set_ylabel('Hueco temporal (días)')\n"
        "    ax.set_title(\n"
        "        f'Revisita irregular de Sentinel-2 — patch {primary_patch[\"patch_id\"]}'\n"
        "    )\n"
        "    ax.legend()\n"
        "    ax.grid(alpha=0.3, axis='y')\n"
        "    plt.tight_layout()\n"
        "    gap_png = FIGURES_DIR / 'temporal_gap_distribution.png'\n"
        "    fig.savefig(gap_png, dpi=130, bbox_inches='tight')\n"
        "    plt.close(fig)\n"
        "    display(Image(filename=str(gap_png)))\n"
        "    display(Markdown(\n"
        "        f'El hueco máximo (`{np.max(gaps):.0f}` días) frente al mínimo '\n"
        "        f'(`{np.min(gaps):.0f}` días) muestra la irregularidad que '\n"
        "        f'motiva interpolar la serie a una rejilla diaria antes de '\n"
        "        f'calcular las características temporales por transformada de '\n"
        "        f'Fourier.'\n"
        "    ))\n"
        "else:\n"
        "    display(Markdown(\n"
        "        'Patch sin suficientes fechas para el análisis de huecos.'\n"
        "    ))\n"
    ),
    _md(
        "## 3. Confusiones simétricas vs asimétricas (Artículo A)\n"
        "\n"
        "Rußwurm y Körner 2018 distinguen dos tipos de error entre clases: las\n"
        "confusiones **simétricas** (por ejemplo, triticale confundido con\n"
        "centeno y centeno con triticale en proporciones parecidas) delatan una\n"
        "similitud espectral o fenológica real entre cultivos, mientras que las\n"
        "**asimétricas** apuntan a factores externos como el desbalance de\n"
        "clases o errores de anotación. Para construir una matriz de confusión\n"
        "entrenamos un Random Forest ligero sobre el subconjunto de\n"
        "características de selección del proyecto usando folds espaciales\n"
        "(entrenamos en cuatro folds y evaluamos en uno distinto, para que el\n"
        "error medido refleje generalización y no memorización del contexto\n"
        "regional). Luego analizamos la simetría de los errores con\n"
        "`confusion_symmetry_analysis`.\n"
    ),
    _code(
        "from sklearn.ensemble import RandomForestClassifier\n"
        "\n"
        "SUBSET = REPO_ROOT / 'data' / 'test_fixtures' / 'feature_selection_subset.parquet'\n"
        "if SUBSET.exists():\n"
        "    df_sub = pl.read_parquet(SUBSET)\n"
        "    feat_cols = [c for c in df_sub.columns if c not in ('parcel_id', 'year', 'class_id', 'fold')]\n"
        "    X = df_sub.select(feat_cols).to_numpy().astype(np.float64)\n"
        "    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)\n"
        "    y_arr = df_sub.get_column('class_id').to_numpy().astype(np.int64)\n"
        "    folds = df_sub.get_column('fold').to_numpy().astype(np.int64)\n"
        "    # Validacion espacial: entrenar en folds != 1, evaluar en fold == 1.\n"
        "    test_mask = folds == 1\n"
        "    train_mask = ~test_mask\n"
        "    clf = RandomForestClassifier(n_estimators=120, random_state=seed, n_jobs=-1)\n"
        "    clf.fit(X[train_mask], y_arr[train_mask])\n"
        "    y_true_cm = y_arr[test_mask]\n"
        "    y_pred_cm = clf.predict(X[test_mask])\n"
        "    cm_mode = 'subconjunto de selección real'\n"
        "else:\n"
        "    # Modo degradado: confusion sintetica con un par simetrico y uno asimetrico.\n"
        "    rng = np.random.default_rng(seed)\n"
        "    y_true_cm = np.repeat([1, 2, 3, 4], 100)\n"
        "    y_pred_cm = y_true_cm.copy()\n"
        "    # Par simetrico 1<->2.\n"
        "    y_pred_cm[0:15] = 2\n"
        "    y_pred_cm[100:115] = 1\n"
        "    # Par asimetrico 3->4.\n"
        "    y_pred_cm[200:230] = 4\n"
        "    cm_mode = 'sintético (subconjunto ausente)'\n"
        "\n"
        "display(Markdown(f'**Fuente de la matriz de confusión**: `{cm_mode}`'))\n"
    ),
    _code(
        "sym_df = confusion_symmetry_analysis(\n"
        "    y_true_cm, y_pred_cm, class_names=PASTIS_CLASS_MAP\n"
        ")\n"
        "sym_csv = FIGURES_DIR / 'confusion_symmetry.csv'\n"
        "sym_df.write_csv(sym_csv)\n"
        "display(Markdown(\n"
        "    f'**Pares de clases confundidas, ordenados por confusión total** '\n"
        "    f'(guardado en `{sym_csv.relative_to(REPO_ROOT)}`)'\n"
        "))\n"
        "display(sym_df.head(15))\n"
        "\n"
        "n_sym = sym_df.filter(pl.col('interpretation') == 'spectral_similarity').height\n"
        "n_asym = sym_df.filter(pl.col('interpretation') == 'external_factor').height\n"
        "display(Markdown(\n"
        "    f'`{n_sym}` pares dominados por la componente **simétrica** '\n"
        "    f'(similitud espectral o fenológica real) frente a `{n_asym}` '\n"
        "    f'dominados por la componente **asimétrica** (factores externos: '\n"
        "    f'desbalance de clases o errores de anotación).'\n"
        "))\n"
    ),
    _code(
        "# Scatter simetrico vs asimetrico para los pares mas confundidos.\n"
        "if sym_df.height > 0:\n"
        "    top = sym_df.head(20)\n"
        "    fig, ax = plt.subplots(figsize=(8, 6))\n"
        "    colors = [\n"
        "        '#1f77b4' if v == 'spectral_similarity' else '#d62728'\n"
        "        for v in top.get_column('interpretation').to_list()\n"
        "    ]\n"
        "    ax.scatter(\n"
        "        top.get_column('symmetric').to_list(),\n"
        "        top.get_column('asymmetric').to_list(),\n"
        "        c=colors, s=70, alpha=0.8, edgecolors='black', linewidths=0.5,\n"
        "    )\n"
        "    lim = max(\n"
        "        top.get_column('symmetric').max() or 1,\n"
        "        top.get_column('asymmetric').max() or 1,\n"
        "    )\n"
        "    ax.plot([0, lim], [0, lim], color='gray', linestyle='--',\n"
        "            label='simétrica = asimétrica')\n"
        "    ax.set_xlabel('Componente simétrica  min(C[i,j], C[j,i])')\n"
        "    ax.set_ylabel('Componente asimétrica  |C[i,j] - C[j,i]|')\n"
        "    ax.set_title('Confusiones simétricas vs asimétricas entre cultivos')\n"
        "    ax.legend()\n"
        "    ax.grid(alpha=0.3)\n"
        "    plt.tight_layout()\n"
        "    sym_png = FIGURES_DIR / 'confusion_symmetry_scatter.png'\n"
        "    fig.savefig(sym_png, dpi=130, bbox_inches='tight')\n"
        "    plt.close(fig)\n"
        "    display(Image(filename=str(sym_png)))\n"
        "else:\n"
        "    display(Markdown(\n"
        "        'Sin pares de confusión para graficar (predicciones perfectas).'\n"
        "    ))\n"
    ),
    _code(
        "# Agregacion de clases raras (Paper A): umbral de frecuencia.\n"
        "y_series = pl.Series('class_id', y_true_cm.tolist())\n"
        "remapped, rare_report = aggregate_rare_classes(y_series, min_count=400, other_label=-1)\n"
        "n_aggregated = len(rare_report['aggregated'])\n"
        "display(Markdown(\n"
        "    f'**Agregación de clases raras** (umbral de '\n"
        "    f'`{rare_report[\"min_count\"]}` ocurrencias, como en el artículo). '\n"
        "    f'`{n_aggregated}` clases por debajo del umbral se colapsan en la '\n"
        "    f'etiqueta `other` (-1). Clases agregadas: '\n"
        "    f'`{rare_report[\"aggregated\"]}`.'\n"
        "))\n"
    ),
    _md(
        "## 4. Calendario fenológico (Artículo C)\n"
        "\n"
        "El Phenology-Aware Transformer (PVM, Remote Sensing 17(14):2346, 2025)\n"
        "introduce un *calendario de crecimiento del cultivo*: una codificación\n"
        "de las etapas de crecimiento (siembra, crecimiento, pico, cosecha) como\n"
        "un vector indexado por día del año, que el modelo usa para ponderar\n"
        "dinámicamente cada imagen de la serie temporal. Aquí construimos una\n"
        "versión de análisis exploratorio del concepto: tomamos el `peak_doy`\n"
        "(día del año en que la vegetación alcanza su máximo) de las\n"
        "características temporales del proyecto y lo discretizamos en etapas\n"
        "fenológicas con `phenology_calendar_features`.\n"
    ),
    _code(
        "# Cargamos el subset de features temporales (incluye peak_doy/sog_doy).\n"
        "if SUBSET.exists():\n"
        "    pheno_in = pl.read_parquet(SUBSET).select(\n"
        "        [c for c in ('parcel_id', 'year', 'class_id', 'peak_doy', 'sog_doy', 'senescence_doy')\n"
        "         if c in pl.read_parquet(SUBSET).columns]\n"
        "    )\n"
        "    pheno_mode = 'subconjunto de selección real'\n"
        "else:\n"
        "    rng = np.random.default_rng(seed)\n"
        "    pheno_in = pl.DataFrame({\n"
        "        'parcel_id': list(range(200)),\n"
        "        'year': [2019] * 200,\n"
        "        'class_id': rng.integers(1, 8, size=200).tolist(),\n"
        "        'peak_doy': rng.integers(60, 320, size=200).tolist(),\n"
        "    })\n"
        "    pheno_mode = 'sintético (subconjunto ausente)'\n"
        "\n"
        "pheno_out = phenology_calendar_features(pheno_in, doy_col='peak_doy', n_stages=4)\n"
        "display(Markdown(f'**Fuente del calendario fenológico**: `{pheno_mode}`'))\n"
        "display(pheno_out.head(10))\n"
    ),
    _code(
        "# Distribucion de etapas de crecimiento globalmente y por clase.\n"
        "stage_dist = (\n"
        "    pheno_out.filter(pl.col('growth_stage') >= 0)\n"
        "    .group_by(['growth_stage', 'growth_stage_name'])\n"
        "    .agg(pl.len().alias('n_parcels'))\n"
        "    .sort('growth_stage')\n"
        ")\n"
        "display(Markdown('**Distribución global de etapas fenológicas**'))\n"
        "display(stage_dist)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(9, 4.5))\n"
        "names = stage_dist.get_column('growth_stage_name').to_list()\n"
        "counts = stage_dist.get_column('n_parcels').to_list()\n"
        "ax.bar(names, counts, color=['#9ecae1', '#74c476', '#fd8d3c', '#cb181d'][:len(names)])\n"
        "ax.set_xlabel('Etapa fenológica (calendario de crecimiento del cultivo)')\n"
        "ax.set_ylabel('Número de parcelas')\n"
        "ax.set_title('Distribución de parcelas por etapa de crecimiento')\n"
        "ax.grid(alpha=0.3, axis='y')\n"
        "plt.tight_layout()\n"
        "pheno_png = FIGURES_DIR / 'phenology_calendar_distribution.png'\n"
        "fig.savefig(pheno_png, dpi=130, bbox_inches='tight')\n"
        "plt.close(fig)\n"
        "display(Image(filename=str(pheno_png)))\n"
    ),
    _code(
        "# Etapa fenologica dominante por clase de cultivo.\n"
        "if 'class_id' in pheno_out.columns:\n"
        "    by_class = (\n"
        "        pheno_out.filter(pl.col('growth_stage') >= 0)\n"
        "        .group_by(['class_id', 'growth_stage_name'])\n"
        "        .agg(pl.len().alias('n'))\n"
        "        .sort(['class_id', 'n'], descending=[False, True])\n"
        "    )\n"
        "    dominant = (\n"
        "        by_class.group_by('class_id', maintain_order=True)\n"
        "        .first()\n"
        "        .rename({'growth_stage_name': 'dominant_stage'})\n"
        "        .with_columns(\n"
        "            pl.col('class_id').cast(pl.Int64)\n"
        "            .replace_strict(PASTIS_CLASS_MAP, default='unknown')\n"
        "            .alias('class_name')\n"
        "        )\n"
        "        .select(['class_id', 'class_name', 'dominant_stage', 'n'])\n"
        "    )\n"
        "    display(Markdown(\n"
        "        '**Etapa de crecimiento dominante por clase de cultivo.** '\n"
        "        'Cada fila indica en qué fase del año concentra su pico cada '\n"
        "        'cultivo, lo que ayuda a separar cultivos de invierno y de verano.'\n"
        "    ))\n"
        "    display(dominant)\n"
        "else:\n"
        "    display(Markdown(\n"
        "        'El subconjunto no tiene columna `class_id`: se omite el '\n"
        "        'desglose por clase.'\n"
        "    ))\n"
    ),
    _md(
        "## 5. Robustez ante huecos de nubes (Artículo D)\n"
        "\n"
        "Qin et al. 2025 (STCLN) usan el enmascaramiento espaciotemporal de la\n"
        "serie de imágenes como tarea de preentrenamiento. Aquí aprovechamos la\n"
        "misma idea como herramienta de **diagnóstico**: eliminamos fracciones\n"
        "crecientes de imágenes de una parcela (simulando que las nubes las\n"
        "ocultan), volvemos a calcular las características temporales del\n"
        "proyecto y medimos cuánto se desplazan respecto al valor original.\n"
        "El resultado cuantifica qué tan robusto es nuestro proceso de\n"
        "ingeniería de características ante la falta de datos por nubes.\n"
    ),
    _code(
        "# Serie temporal de parcela: cargamos el fixture .nc del proyecto o uno sintetico.\n"
        "DEMO_TS = REPO_ROOT / 'data' / 'test_fixtures' / 'parcel_demo_ts.nc'\n"
        "if DEMO_TS.exists():\n"
        "    parcel_ts = xr.open_dataarray(DEMO_TS)\n"
        "    parcel_ts = parcel_ts.assign_coords(\n"
        "        band=[b.decode() if isinstance(b, bytes) else str(b) for b in parcel_ts.coords['band'].values]\n"
        "    )\n"
        "    parcel_ts = parcel_ts.assign_coords(\n"
        "        time=parcel_ts.coords['time'].values.astype('datetime64[ns]')\n"
        "    )\n"
        "    if 'parcel_id' not in parcel_ts.attrs:\n"
        "        parcel_ts.attrs['parcel_id'] = 1\n"
        "    if 'year' not in parcel_ts.attrs:\n"
        "        parcel_ts.attrs['year'] = 2019\n"
        "    ts_mode = 'fixture parcel_demo_ts.nc'\n"
        "else:\n"
        "    rng = np.random.default_rng(seed)\n"
        "    n_t = 28\n"
        "    times = np.array(\n"
        "        [np.datetime64('2019-01-01', 'ns') + np.timedelta64(13 * i, 'D') for i in range(n_t)],\n"
        "        dtype='datetime64[ns]',\n"
        "    )\n"
        "    doy = np.array([(t - times[0]) / np.timedelta64(1, 'D') for t in times])\n"
        "    ndvi = 0.2 + 0.6 * np.exp(-((doy - 180) ** 2) / (2 * 55.0 ** 2)) + rng.normal(0, 0.01, n_t)\n"
        "    ndwi = -0.1 + rng.normal(0, 0.02, n_t)\n"
        "    evi = ndvi * 0.8\n"
        "    parcel_ts = xr.DataArray(\n"
        "        np.stack([ndvi, ndwi, evi], axis=1),\n"
        "        dims=('time', 'band'),\n"
        "        coords={'time': times, 'band': ['NDVI', 'NDWI', 'EVI']},\n"
        "    )\n"
        "    parcel_ts.attrs['parcel_id'] = 1\n"
        "    parcel_ts.attrs['year'] = 2019\n"
        "    ts_mode = 'serie sintetica'\n"
        "\n"
        "available_bands = [str(b) for b in parcel_ts.coords['band'].values]\n"
        "robust_indices = tuple(b for b in ('NDVI', 'NDWI', 'EVI') if b in available_bands)\n"
        "\n"
        "def extractor(ts: xr.DataArray) -> pl.DataFrame:\n"
        '    """Wrapper de extract_temporal_features sobre los indices disponibles."""\n'
        "    return extract_temporal_features(\n"
        "        ts, indices=robust_indices, fft_indices=robust_indices\n"
        "    )\n"
        "\n"
        "display(Markdown(\n"
        "    f'**Fuente de la serie temporal**: `{ts_mode}` '\n"
        "    f'({parcel_ts.sizes[\"time\"]} observaciones, '\n"
        "    f'índices `{robust_indices}`)'\n"
        "))\n"
    ),
    _code(
        "robustness = cloud_gap_robustness(\n"
        "    extractor, parcel_ts, mask_fractions=(0.0, 0.2, 0.4, 0.6), seed=seed\n"
        ")\n"
        "robust_csv = FIGURES_DIR / 'cloud_gap_robustness.csv'\n"
        "robustness.write_csv(robust_csv)\n"
        "\n"
        "# Resumen: deriva media por fraccion de enmascaramiento.\n"
        "drift_summary = (\n"
        "    robustness.filter(pl.col('mask_fraction') > 0.0)\n"
        "    .group_by('mask_fraction')\n"
        "    .agg([\n"
        "        pl.col('drift_from_baseline').drop_nans().mean().alias('mean_drift'),\n"
        "        pl.col('drift_from_baseline').drop_nans().max().alias('max_drift'),\n"
        "        pl.col('n_timesteps_kept').first().alias('n_timesteps_kept'),\n"
        "    ])\n"
        "    .sort('mask_fraction')\n"
        ")\n"
        "display(Markdown(\n"
        "    f'**Deriva de las características por fracción de huecos simulados** '\n"
        "    f'(guardado en `{robust_csv.relative_to(REPO_ROOT)}`). '\n"
        "    f'`mean_drift` mide cuánto cambia en promedio una característica al '\n"
        "    f'ocultar parte de las observaciones; cuanto más bajo, más robusta.'\n"
        "))\n"
        "display(drift_summary)\n"
    ),
    _code(
        "# Curva de deriva vs fraccion enmascarada para features fenologicas clave.\n"
        "key_feats = [\n"
        "    f for f in ('peak_doy', 'NDVI_fft_amp_1', 'ndvi_auc', 'sog_doy')\n"
        "    if f in robustness.get_column('feature_name').unique().to_list()\n"
        "]\n"
        "if key_feats and robustness.height > 0:\n"
        "    fig, ax = plt.subplots(figsize=(9, 5))\n"
        "    for feat in key_feats:\n"
        "        sub = robustness.filter(pl.col('feature_name') == feat).sort('mask_fraction')\n"
        "        ax.plot(\n"
        "            sub.get_column('mask_fraction').to_list(),\n"
        "            sub.get_column('drift_from_baseline').to_list(),\n"
        "            marker='o', label=feat,\n"
        "        )\n"
        "    ax.set_xlabel(\n"
        "        'Fracción de observaciones ocultadas (huecos de nubes simulados)'\n"
        "    )\n"
        "    ax.set_ylabel('Deriva absoluta respecto al valor original')\n"
        "    ax.set_title('Robustez de las características temporales ante huecos de nubes')\n"
        "    ax.legend()\n"
        "    ax.grid(alpha=0.3)\n"
        "    plt.tight_layout()\n"
        "    robust_png = FIGURES_DIR / 'cloud_gap_drift.png'\n"
        "    fig.savefig(robust_png, dpi=130, bbox_inches='tight')\n"
        "    plt.close(fig)\n"
        "    display(Image(filename=str(robust_png)))\n"
        "    display(Markdown(\n"
        "        'Una pendiente suave indica un proceso robusto: las '\n"
        "        'características varían poco al perder hasta el 60% de las '\n"
        "        'observaciones. Una pendiente abrupta delata características '\n"
        "        'frágiles ante la cobertura nubosa.'\n"
        "    ))\n"
        "else:\n"
        "    display(Markdown(\n"
        "        'Sin características clave rastreables en la serie cargada.'\n"
        "    ))\n"
    ),
    _md(
        "## Conclusiones\n"
        "\n"
        "Esta sección se genera de forma dinámica con los números de la\n"
        "ejecución actual, de modo que el texto siempre coincide con las tablas\n"
        "y figuras de arriba aunque cambien los datos de entrada.\n"
    ),
    _code(
        "lines: list[str] = []\n"
        "lines.append('### Qué aporta cada método al análisis del proyecto\\n')\n"
        "\n"
        "# Hallazgo 1: frontera vs interior.\n"
        "if interior_std and interior_std > 0:\n"
        "    bi_ratio_c = boundary_std / interior_std\n"
        "    if bi_ratio_c >= 1.05:\n"
        "        h1_lead = 'La dispersión espectral se concentra en la frontera'\n"
        "        h1_body = (\n"
        "            f'la variabilidad de la banda infrarroja en los píxeles de '\n"
        "            f'borde es `{bi_ratio_c:.2f}x` la del interior. Los bordes '\n"
        "            f'son la zona más difícil de clasificar'\n"
        "        )\n"
        "    else:\n"
        "        h1_lead = 'Los bordes de parcela merecen atención específica'\n"
        "        h1_body = (\n"
        "            f'en el patch analizado la variabilidad de la banda '\n"
        "            f'infrarroja en la frontera es `{bi_ratio_c:.2f}x` la del '\n"
        "            f'interior. El artículo describe esta diferencia como una '\n"
        "            f'tendencia sobre el conjunto completo; aun así, los bordes '\n"
        "            f'siguen siendo la zona más sensible de la segmentación'\n"
        "        )\n"
        "    lines.append(\n"
        "        f'1. **{h1_lead}** (Tarasiou et al. 2021). En concreto, {h1_body}, '\n"
        "        f'lo que justifica vigilar de cerca el rendimiento de los '\n"
        "        f'modelos de segmentación justamente en los límites de parcela. '\n"
        "        f'La función `compute_boundary_ratio` produce además un '\n"
        "        f'descriptor de la geometría de cada parcela.'\n"
        "    )\n"
        "\n"
        "# Hallazgo 2: revisita irregular.\n"
        "mean_cov = float(sampling_df.get_column('doy_coverage').mean())\n"
        "mean_gap = float(sampling_df.get_column('mean_gap_days').mean())\n"
        "lines.append(\n"
        "    f'2. **La revisita de Sentinel-2 es irregular** (Rußwurm y Körner '\n"
        "    f'2018). Los patches analizados tienen un hueco medio de '\n"
        "    f'`{mean_gap:.1f}` días entre imágenes válidas y cubren en promedio '\n"
        "    f'el `{mean_cov:.1%}` del calendario anual. Como las imágenes no '\n"
        "    f'llegan a intervalos fijos, conviene interpolar la serie a una '\n"
        "    f'rejilla diaria antes de calcular las características temporales, y '\n"
        "    f'reportar la métrica kappa de Cohen además de la exactitud para '\n"
        "    f'tener en cuenta el desbalance de clases.'\n"
        ")\n"
        "\n"
        "# Hallazgo 3: simetria de confusiones.\n"
        "lines.append(\n"
        "    f'3. **Las confusiones se separan en estructurales y espurias** '\n"
        "    f'(Rußwurm y Körner 2018). De los pares de clases confundidas, '\n"
        "    f'`{n_sym}` están dominados por la componente simétrica (una '\n"
        "    f'similitud espectral o fenológica real entre cultivos, por ejemplo '\n"
        "    f'entre cereales de invierno) y `{n_asym}` por la componente '\n"
        "    f'asimétrica (desbalance de clases o errores de anotación). '\n"
        "    f'Distinguirlas orienta dónde invertir: características más finas '\n"
        "    f'para las simétricas, y rebalanceo o limpieza de etiquetas para '\n"
        "    f'las asimétricas.'\n"
        ")\n"
        "\n"
        "# Hallazgo 4: calendario fenologico + robustez.\n"
        "n_stages_used = int(pheno_out.filter(pl.col('growth_stage') >= 0).get_column('growth_stage').n_unique())\n"
        "if drift_summary.height > 0:\n"
        "    max_drift_06 = drift_summary.filter(pl.col('mask_fraction') == 0.6)\n"
        "    drift_txt = (\n"
        "        f'{float(max_drift_06.get_column(\"mean_drift\")[0]):.4f}'\n"
        "        if max_drift_06.height > 0 else 'n/a'\n"
        "    )\n"
        "else:\n"
        "    drift_txt = 'n/a'\n"
        "lines.append(\n"
        "    f'4. **El calendario fenológico y la robustez ante nubes se '\n"
        "    f'complementan**. El día del año del pico de vegetación, una vez '\n"
        "    f'discretizado, puebla `{n_stages_used}` etapas de crecimiento: una '\n"
        "    f'característica categórica que resume *cuándo* crece cada cultivo. '\n"
        "    f'La auditoría de huecos de nubes mide cuánto se desplazan las '\n"
        "    f'características al ocultar el 60% de las imágenes: `{drift_txt}` '\n"
        "    f'en promedio — un valor bajo confirma que el proceso temporal '\n"
        "    f'tolera bien la pérdida de observaciones por cobertura nubosa.'\n"
        ")\n"
        "lines.append('')\n"
        "lines.append('### Lo que sigue\\n')\n"
        "lines.append(\n"
        "    'Los ocho métodos quedan disponibles como funciones estables y '\n"
        "    'probadas en `ml/analysis/paper_methods.py` para el resto del '\n"
        "    'proyecto. `compute_boundary_ratio` y `phenology_calendar_features` '\n"
        "    'se incorporan como características adicionales en la fase de fusión '\n"
        "    'de datos; `confusion_symmetry_analysis` se reutilizará en la '\n"
        "    'evaluación de los modelos de segmentación para diagnosticar sus '\n"
        "    'matrices de confusión; `temporal_sampling_stats` y '\n"
        "    '`cloud_gap_robustness` servirán como control de calidad de los '\n"
        "    'datos antes de cada entrenamiento; y `aggregate_rare_classes` '\n"
        "    'orienta la estrategia de rebalanceo del modelo base. Todos los '\n"
        "    'métodos están cubiertos por pruebas automatizadas y citan su '\n"
        "    'artículo de origen.'\n"
        ")\n"
        "display(Markdown('\\n'.join(lines)))\n"
    ),
]


@app.command()
def build(
    out: Path = typer.Option(
        Path("notebooks/eda/02e_eda_metodos_paper.ipynb"),
        help="Ruta destino del .ipynb generado.",
    ),
) -> None:
    """Build the paper-methods EDA notebook from ``CELLS``."""
    nb = nbf.v4.new_notebook()
    nb.cells = CELLS
    nb.metadata.update(
        {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        }
    )
    out_path = out if out.is_absolute() else Path.cwd() / out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, str(out_path))
    typer.echo(f"Notebook escrito en {out_path} ({len(CELLS)} celdas)")


if __name__ == "__main__":
    app()
