"""US-079 runner: dense transfer (fine-tune) + Voting-3 + hierarchical eval.

Orchestrates the full US-079 modelling pipeline on the US-078 Italian homologue,
real-training each dense member on the H100 and combining them with the EPIC 6
deployment winner (the weighted Voting). It is idempotent at the member level
(an already fine-tuned member's ``test_softmax.npz`` is reused unless
``--force``), so a crashed run resumes cheaply.

Pipeline (PARCEL vote = the champion replica, default)
------------------------------------------------------
1. Fine-tune each dense member (``tsvit-pheno``, ``utae``) from its PASTIS
   checkpoint with the warm-started Italian head
   (:func:`ml.transfer.finetune_italia.run_italia_finetune`). Per-epoch
   checkpoints land under ``checkpoints/transfer/<member>-italia/<run>/`` (F: on
   the VM).
2. Aggregate each dense member's post-softmax maps to PER-PARCEL distributions
   (:mod:`ml.transfer.dense_to_parcel_italia`) -> ``oof_parcel_<member>_italia_
   fold5.parquet``, the SAME contract the ``xgb-alphaearth-italia`` member writes.
3. Learn the Voting-3 convex weights over the THREE per-parcel members
   (``tsvit-pheno`` + ``utae`` + ``xgb-alphaearth-italia``) with
   leave-one-spatial-fold-out CV
   (:class:`ml.ensemble.voting_italia.ItaliaParcelVotingEnsemble`), faithfully
   replicating the champion (France F1 0.9069).
4. Evaluate the Voting-3 and each member at the FINE + COARSE granularities,
   build the honest discard curve, and compute the transfer delta vs the
   zero-shot French champion (:mod:`ml.eval.transfer_italia_eval`).
5. Log everything to MLflow (``data_version`` + ``code_version``) and write a
   ``report.json`` under the run dir.

The ``--vote-space pixel`` flag keeps the previous dense-only pixel vote
(:class:`ml.ensemble.voting_italia.ItaliaPixelVotingEnsemble`) for experiments.

Usage
-----
    poetry run python scripts/run_transfer_italia.py \
        --members tsvit-pheno utae xgb-alphaearth-italia \
        --test-fold 3 --finetune-epochs 12 --run us079

    # CPU smoke (tiny, no MLflow server): --device cpu --finetune-epochs 1 \
    #   --head-warmup-epochs 0 --no-mlflow
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import structlog

logger = structlog.get_logger(__name__)

_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_ITALIA_ROOT = _REPO_ROOT / "data" / "pastis_italia_2018"
_DEFAULT_CKPT_ROOT = _REPO_ROOT / "checkpoints" / "transfer"
#: Italian per-class phenology prototypes (US-079 fix B). Generated by
#: scripts/build_phenology_italia.py; the TSViT-pheno semantic branch contrasts
#: Italian pixels against THESE (Mediterranean), not the Bretagne/PASTIS ones.
_DEFAULT_ITALIA_PROTOTYPES = (
    _REPO_ROOT / "data" / "features" / "phenology_class_prototypes_italia.parquet"
)

#: The Voting-3 terna that REPLICATES the champion (France F1 0.9069): the two
#: dense members (aggregated to parcel) + the tabular AlphaEarth XGBoost member.
#: The xgb member is NOT fine-tuned here; its per-parcel OOF is produced upstream
#: by ml.ensemble.xgb_alphaearth_italia. The two dense members ARE fine-tuned.
DEFAULT_MEMBERS: tuple[str, ...] = ("tsvit-pheno", "utae", "xgb-alphaearth-italia")

#: Members that require a dense fine-tune (everything except the tabular xgb).
_XGB_MEMBER: str = "xgb-alphaearth-italia"

#: Rough single-GPU VRAM budget per member at 128px (forward+backward, BF16/FP32
#: mixed), measured headroom on the H100 NVL. Used only to advise serial vs
#: parallel launch; never a hard gate.
_VRAM_GB_PER_MEMBER: dict[str, float] = {
    "tsvit-pheno": 6.0,
    "tsvit-pheno-fullm": 14.0,
    "utae": 5.0,
    "xgb-alphaearth-italia": 0.0,  # CPU XGBoost, no VRAM.
}


def _dense_members(members: list[str]) -> list[str]:
    """Return the members that require a dense fine-tune (xgb is tabular)."""
    return [m for m in members if m != _XGB_MEMBER]


def _member_finetune(
    member: str,
    args: argparse.Namespace,
) -> dict[str, object]:
    """Fine-tune one dense member (or reuse its dump) and return its summary."""
    from ml.transfer.finetune_italia import DenseFineTuneConfig, run_italia_finetune

    run_dir = _DEFAULT_CKPT_ROOT / f"{member}-italia" / args.run
    summary_path = run_dir / "summary.json"
    if summary_path.is_file() and not args.force:
        logger.info("member_finetune_reused", member=member, summary=str(summary_path))
        return json.loads(summary_path.read_text(encoding="utf-8"))

    config = DenseFineTuneConfig(
        model_kind="tsvit-pheno" if member == "tsvit-pheno-fullm" else member,
        n_timesteps=args.n_timesteps,
        head_warmup_epochs=args.head_warmup_epochs,
        finetune_epochs=args.finetune_epochs,
        lr_backbone=args.lr_backbone,
        batch_size=args.batch_size,
        min_patches_per_class=args.min_patches_per_class,
        scheduler=args.scheduler,
        class_weighting=args.class_weighting,
        pheno_prototypes=args.pheno_prototypes,
        lambda_contrast=args.lambda_contrast,
        val_fraction=args.val_fraction,
        seed=args.seed,
        warm_start=not args.no_warm_start,
        from_scratch=args.from_scratch,
        # The Full-M member rebuilds the champion capacity (dim=192, depth 6+6) so
        # the warm-start from tsvit-pheno-fullm-v1 loads without a shape mismatch;
        # the plain tsvit-pheno member keeps the historical L4 topology (dim=128).
        tsvit_capacity="fullm" if member == "tsvit-pheno-fullm" else "l4",
    )
    # The Full-M member shares the tsvit-pheno builder but inits from the Full-M
    # checkpoint; the L4 member inits from tsvit-pheno-v1.
    from ml.transfer.finetune_italia import DEFAULT_PASTIS_CHECKPOINTS

    ckpt = DEFAULT_PASTIS_CHECKPOINTS["tsvit-pheno"]
    if member == "tsvit-pheno-fullm":
        ckpt = _REPO_ROOT / "checkpoints" / "segmentation" / "tsvit-pheno-fullm-v1" / "best.pt"
    elif member == "utae":
        ckpt = DEFAULT_PASTIS_CHECKPOINTS["utae"]

    return run_italia_finetune(
        config,
        italia_root=args.italia_root,
        pastis_checkpoint=ckpt,
        test_fold=args.test_fold,
        ckpt_root=_DEFAULT_CKPT_ROOT,
        run_name=f"{args.run}-{member}",
        device=args.device,
    )


def _load_test_masks_and_folds(
    italia_root: Path, *, test_fold: int, n_timesteps: int
) -> tuple[dict[int, np.ndarray], dict[int, int]]:
    """Load the held-out test masks + their spatial folds for the eval/vote."""
    from ml.transfer.finetune_italia import load_italia_patches

    patches = load_italia_patches(
        italia_root=italia_root, n_timesteps=n_timesteps, folds=(test_fold,)
    )
    masks = {pid: patches.masks[i] for i, pid in enumerate(patches.patch_ids)}
    folds = {pid: patches.folds[i] for i, pid in enumerate(patches.patch_ids)}
    return masks, folds


def _aggregate_dense_to_parcel_oof(
    member: str,
    summary: dict[str, object],
    *,
    italia_root: Path,
    n_timesteps: int,
    label_space: object,
    strategy: str,
    parcel_rasters: dict[int, tuple[np.ndarray, dict[int, str]]] | None,
) -> Path:
    """Aggregate a fine-tuned dense member's softmax dump to a per-parcel OOF.

    Loads the member's test ``test_softmax.npz`` + the matching ground-truth masks
    / folds, reduces the dense maps to per-parcel distributions
    (:func:`ml.transfer.dense_to_parcel_italia.aggregate_dense_member_to_parcel`)
    and dumps ``oof_parcel_<member>_italia_fold5.parquet`` -- the SAME contract the
    xgb member writes, so the three vote in one per-parcel namespace.

    Args:
        member: The dense member name.
        summary: The fine-tune summary (carries ``softmax_path`` + ``test_patch_ids``).
        italia_root: The homologue dataset root.
        n_timesteps: Equispaced dates per patch (to re-load the matching masks).
        label_space: The Italian dense label space.
        strategy: ``"eurocrops"`` (joins the xgb 1:1) or ``"blobs"`` (self-contained).
        parcel_rasters: For ``strategy="eurocrops"``, the per-patch EuroCrops
            ParcelID rasters (``{patch_id: (parcel_id_map, id_to_canonical)}``).

    Returns:
        The path of the written per-parcel OOF parquet.
    """
    from ml.ensemble.voting_italia import load_member_softmax
    from ml.transfer.dense_to_parcel_italia import (
        aggregate_dense_member_to_parcel,
        write_parcel_oof,
    )
    from ml.transfer.finetune_italia import load_italia_patches

    preds = load_member_softmax(member, Path(str(summary["softmax_path"])))
    test_pids = set(preds.probs_by_patch)
    patches = load_italia_patches(italia_root=italia_root, n_timesteps=n_timesteps)
    masks = {pid: patches.masks[i] for i, pid in enumerate(patches.patch_ids) if pid in test_pids}
    folds = {pid: patches.folds[i] for i, pid in enumerate(patches.patch_ids) if pid in test_pids}
    aggregation = aggregate_dense_member_to_parcel(
        member,
        preds.probs_by_patch,
        masks,
        folds,
        num_classes=label_space.num_classes,  # type: ignore[attr-defined]
        strategy=strategy,
        background_id=label_space.background_id,  # type: ignore[attr-defined]
        parcel_rasters=parcel_rasters,
    )
    return write_parcel_oof(aggregation)


def _dense_eval_of_parcel_vote(
    vote_result: object,
    *,
    parcel_rasters: dict[int, tuple[np.ndarray, dict[int, str]]] | None,
    masks: dict[int, np.ndarray],
    label_space: object,
) -> dict[str, object]:
    """Project the per-parcel champion vote onto a dense map and score it.

    The champion votes per PARCEL; the EPIC 5 rubric is a DENSE metric. This
    re-paints every parcel's blended distribution onto its pixels (via the
    EuroCrops ParcelID rasters), then runs the SAME fine/coarse hierarchical eval +
    honest discard curve the dense members use, so the parcel-level winner ALSO
    reports dense mIoU / F1 for the rubric. Needs the ``eurocrops`` strategy (the
    ``blobs`` namespace has no ParcelID raster to project onto); with ``blobs`` or
    no blended vote it returns an empty dict (reported honestly).

    Args:
        vote_result: The :class:`ml.ensemble.voting_italia.ItaliaParcelVotingResult`.
        parcel_rasters: The per-patch EuroCrops ParcelID rasters (eurocrops only).
        masks: ``{patch_id: (H, W)}`` held-out ground-truth class masks.
        label_space: The Italian dense label space.

    Returns:
        A dict with ``voting_dense_eval`` (fine/coarse summary), ``voting_dense_
        per_class``, ``voting_dense_discard_curve`` and ``voting_dense_best_subset_
        f1_over_0.9``; empty if the projection is unavailable.
    """
    from ml.eval.transfer_italia_eval import (
        best_subset_over_threshold,
        discard_curve,
        evaluate_dense_predictions,
        probs_to_class_map,
        project_parcel_vote_to_dense,
    )

    parcel_vote = vote_result.parcel_vote()  # type: ignore[attr-defined]
    if parcel_rasters is None or not parcel_vote:
        logger.info(
            "us079_parcel_vote_dense_skipped",
            note="dense projection needs the eurocrops ParcelID rasters and a "
            "blended vote; not available (blobs strategy or empty vote).",
        )
        return {}

    dense_probs = project_parcel_vote_to_dense(
        parcel_vote,
        vote_result.crop_class_ids,  # type: ignore[attr-defined]
        parcel_rasters,
        num_classes=label_space.num_classes,  # type: ignore[attr-defined]
        background_id=label_space.background_id,  # type: ignore[attr-defined]
    )
    vote_preds = probs_to_class_map(dense_probs)
    ev = evaluate_dense_predictions(
        "voting-3-parcel-projected", vote_preds, masks, label_space=label_space
    )
    curve = discard_curve(ev)
    best_subset = best_subset_over_threshold(ev, threshold=0.9)
    logger.info(
        "us079_parcel_vote_dense_eval",
        fine_f1=ev.summary()["fine_f1_macro"],
        fine_miou=ev.summary()["fine_miou"],
        coarse_f1=ev.summary()["coarse_f1_macro"],
        best_subset_n=best_subset["n_classes"],
    )
    return {
        "voting_dense_eval": ev.summary(),
        "voting_dense_per_class": ev.per_class,
        "voting_dense_discard_curve": curve,
        "voting_dense_best_subset_f1_over_0.9": best_subset,
    }


def main() -> None:
    """Parse the CLI, run the US-079 parcel-level pipeline and persist the report."""
    parser = argparse.ArgumentParser(description="US-079 Italian transfer + Voting-3.")
    parser.add_argument("--members", nargs="+", default=list(DEFAULT_MEMBERS))
    parser.add_argument("--italia-root", type=Path, default=_DEFAULT_ITALIA_ROOT)
    parser.add_argument(
        "--parcels-parquet",
        type=Path,
        default=None,
        help="EuroCrops parcels parquet for the dense->parcel join (e.g. "
        "de4_2023.parquet); defaults to the Italy reference.",
    )
    parser.add_argument(
        "--mapping-csv",
        type=Path,
        default=None,
        help="EuroCrops crosswalk CSV (eurocrops.csv); defaults to the Italy mapping.",
    )
    parser.add_argument(
        "--region-prefix",
        default="it",
        help="NUTS prefix for the crosswalk region (it, de4, nl, ...).",
    )
    parser.add_argument("--test-fold", type=int, default=3)
    parser.add_argument("--n-timesteps", type=int, default=10)
    # US-079 fix A: converged defaults (the F1 0.108 run sub-converged at 12 ep /
    # 2 warmup / batch 4 / flat LR). Override on the CLI for a CPU smoke.
    parser.add_argument("--head-warmup-epochs", type=int, default=5)
    parser.add_argument("--finetune-epochs", type=int, default=40)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--lr-backbone", type=float, default=2e-4)
    parser.add_argument(
        "--scheduler",
        choices=("cosine", "none"),
        default="cosine",
        help="LR schedule of the fine-tune phase (cosine = warmup + cosine decay).",
    )
    parser.add_argument(
        "--class-weighting",
        choices=("inverse", "sqrt_inverse", "none"),
        default="inverse",
        help="Per-class CE weighting from the real train-pixel frequencies.",
    )
    parser.add_argument(
        "--pheno-prototypes",
        type=Path,
        default=_DEFAULT_ITALIA_PROTOTYPES,
        help="Italian per-class phenology prototypes for the TSViT semantic branch "
        "(US-079 fix B). Pass --lambda-contrast 0 to disable the branch.",
    )
    parser.add_argument(
        "--lambda-contrast",
        type=float,
        default=0.1,
        help="Weight of the phenology contrastive term (TSViT-pheno only); 0 = off.",
    )
    parser.add_argument(
        "--no-warm-start",
        action="store_true",
        help="US-079 A/B ablation: init every head row randomly (skip the "
        "kept-class flag) to test whether the Atlantic-France prior hurts the "
        "conserved classes in the Mediterranean domain.",
    )
    parser.add_argument(
        "--from-scratch",
        action="store_true",
        help="US-079 no-transfer baseline: load NOTHING from PASTIS (neither "
        "backbone nor head); train Italy from scratch with the same methodology "
        "(Italian phenology, weighted CE, cosine, Voting-3). Isolates how much the "
        "France->Italy transfer contributes. Implies --no-warm-start.",
    )
    parser.add_argument(
        "--val-fraction",
        type=float,
        default=0.2,
        help="Fraction of the train spatial folds held out as val for best.pt.",
    )
    parser.add_argument("--min-patches-per-class", type=int, default=None)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--run", default="us079")
    parser.add_argument("--device", default="cuda")
    parser.add_argument(
        "--vote-space",
        choices=("parcel", "pixel"),
        default="parcel",
        help="parcel = the champion replica (default); pixel = dense-only experiment.",
    )
    parser.add_argument(
        "--parcel-strategy",
        choices=("eurocrops", "blobs"),
        default="eurocrops",
        help="dense->parcel partition: eurocrops (default, joins the xgb member "
        "1:1 via the EuroCrops ParcelID raster reconstructed from the metadata "
        "bbox -- the champion terna) or blobs (self-contained dense-only vote).",
    )
    parser.add_argument("--force", action="store_true", help="Re-train even if a dump exists.")
    parser.add_argument("--no-mlflow", action="store_true", help="Skip MLflow logging.")
    parser.add_argument("--no-zero-shot", action="store_true", help="Skip the transfer delta.")
    args = parser.parse_args()

    _advise_vram(args.members)

    if args.vote_space == "pixel":
        _run_pixel_vote(args)
        return

    from ml.transfer.italia_label_space import build_italia_label_space

    label_space = build_italia_label_space(italia_root=args.italia_root)

    # 0) For the champion terna, build the EuroCrops ParcelID rasters once (from the
    # metadata bbox via from_bounds; NO tile cache). They drive BOTH the dense->parcel
    # aggregation and the parcel-vote->dense projection for the rubric eval.
    parcel_rasters: dict[int, tuple[np.ndarray, dict[int, str]]] | None = None
    if args.parcel_strategy == "eurocrops":
        from ml.transfer.dense_to_parcel_italia import load_eurocrops_parcel_rasters

        parcel_rasters = load_eurocrops_parcel_rasters(
            args.italia_root,
            parcels_parquet=args.parcels_parquet,
            mapping_csv=args.mapping_csv,
            region_prefix=args.region_prefix,
        )

    # 1) Fine-tune the DENSE members (the xgb member's OOF is produced upstream).
    member_summaries: dict[str, dict[str, object]] = {}
    for member in _dense_members(args.members):
        member_summaries[member] = _member_finetune(member, args)

    # 2) Aggregate each dense member to a per-parcel OOF (champion contract).
    for member, summary in member_summaries.items():
        _aggregate_dense_to_parcel_oof(
            member,
            summary,
            italia_root=args.italia_root,
            n_timesteps=args.n_timesteps,
            label_space=label_space,
            strategy=args.parcel_strategy,
            parcel_rasters=parcel_rasters,
        )

    # 3) Learn the Voting-3 over the THREE per-parcel members (champion replica).
    from ml.ensemble.voting_italia import ItaliaParcelVotingEnsemble

    vote = ItaliaParcelVotingEnsemble(members=tuple(args.members), random_state=args.seed)
    vote_result = vote.fit()

    # 4) Per-member dense eval (granularity demo) on the held-out fold.
    masks, _ = _load_test_masks_and_folds(
        args.italia_root, test_fold=args.test_fold, n_timesteps=args.n_timesteps
    )
    from ml.ensemble.voting_italia import load_member_softmax
    from ml.eval.transfer_italia_eval import evaluate_dense_predictions, probs_to_class_map

    member_evals: dict[str, dict[str, object]] = {}
    for member, summary in member_summaries.items():
        preds = load_member_softmax(member, Path(str(summary["softmax_path"])))
        ev = evaluate_dense_predictions(
            member,
            probs_to_class_map(preds.probs_by_patch),
            masks,
            label_space=label_space,
        )
        member_evals[member] = ev.summary()

    # 5) Project the per-parcel CHAMPION vote back onto a dense map so the
    # parcel-level winner also carries dense fine/coarse metrics (EPIC 5 rubric).
    vote_dense_eval = _dense_eval_of_parcel_vote(
        vote_result,
        parcel_rasters=parcel_rasters,
        masks=masks,
        label_space=label_space,
    )

    report = {
        "run": args.run,
        "vote_space": "parcel",
        "parcel_strategy": args.parcel_strategy,
        "test_fold": args.test_fold,
        "members": list(args.members),
        "voting_weights": vote_result.weight_map(),
        "voting_oof_f1_macro": (
            round(vote_result.oof_f1_macro, 4)
            if vote_result.oof_f1_macro == vote_result.oof_f1_macro  # not NaN
            else None
        ),
        "voting_oof_accuracy": (
            round(vote_result.oof_accuracy, 4)
            if vote_result.oof_accuracy == vote_result.oof_accuracy
            else None
        ),
        "voting_per_fold": vote_result.per_fold,
        "voting_n_parcels": vote_result.n_parcels,
        "voting_match_coverage": vote_result.match_coverage,
        "voting_crop_class_ids": list(vote_result.crop_class_ids),
        "member_dense_eval": member_evals,
        "member_summaries": member_summaries,
        **vote_dense_eval,
    }

    out_dir = _DEFAULT_CKPT_ROOT / "voting-italia" / args.run
    out_dir.mkdir(parents=True, exist_ok=True)
    report_path = out_dir / "report.json"
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.info(
        "us079_parcel_report_written",
        path=str(report_path),
        voting_oof_f1=report["voting_oof_f1_macro"],
        weights=vote_result.weight_map(),
        n_parcels=vote_result.n_parcels,
        coverage=vote_result.match_coverage,
    )

    if not args.no_mlflow:
        _log_mlflow(args, report, report_path)


def _run_pixel_vote(args: argparse.Namespace) -> None:
    """Run the SECONDARY dense pixel vote (the previous behaviour, dense-only).

    Args:
        args: The parsed CLI namespace.
    """
    from ml.ensemble.voting_italia import ItaliaPixelVotingEnsemble, load_member_softmax
    from ml.eval.transfer_italia_eval import (
        best_subset_over_threshold,
        discard_curve,
        evaluate_dense_predictions,
        probs_to_class_map,
        transfer_delta,
    )
    from ml.transfer.italia_label_space import build_italia_label_space

    members = _dense_members(args.members)
    member_summaries = {m: _member_finetune(m, args) for m in members}
    masks, folds = _load_test_masks_and_folds(
        args.italia_root, test_fold=args.test_fold, n_timesteps=args.n_timesteps
    )
    label_space = build_italia_label_space(italia_root=args.italia_root)
    member_preds = {
        m: load_member_softmax(m, Path(str(s["softmax_path"]))) for m, s in member_summaries.items()
    }
    vote = ItaliaPixelVotingEnsemble(
        members=tuple(members),
        num_classes=label_space.num_classes,
        ignore_index=label_space.background_id,
        random_state=args.seed,
    )
    vote_result = vote.fit_predict(member_preds, masks, folds)
    vote_preds = probs_to_class_map(vote_result.blended_probs_by_patch)
    vote_eval = evaluate_dense_predictions("voting-3", vote_preds, masks, label_space=label_space)
    curve = discard_curve(vote_eval)
    best_subset = best_subset_over_threshold(vote_eval, threshold=0.9)

    delta: dict[str, float] = {}
    if not args.no_zero_shot:
        from ml.transfer.finetune_italia import zero_shot_pastis_predict

        zs_member = "tsvit-pheno" if "tsvit-pheno" in members else members[0]
        zs_preds = zero_shot_pastis_predict(
            model_kind="tsvit-pheno" if zs_member == "tsvit-pheno-fullm" else zs_member,
            italia_root=args.italia_root,
            test_fold=args.test_fold,
            n_timesteps=args.n_timesteps,
            device=args.device,
        )
        zs_eval = evaluate_dense_predictions("zero-shot", zs_preds, masks, label_space=label_space)
        delta = transfer_delta(vote_eval, zs_eval)

    report = {
        "run": args.run,
        "vote_space": "pixel",
        "test_fold": args.test_fold,
        "members": list(members),
        "voting_weights": vote_result.weight_map(),
        "voting_oof_f1_macro": round(vote_result.oof_f1_macro, 4),
        "voting_oof_miou": round(vote_result.oof_miou, 4),
        "voting_per_fold": vote_result.per_fold,
        "voting_eval": vote_eval.summary(),
        "voting_per_class": vote_eval.per_class,
        "discard_curve": curve,
        "best_subset_f1_over_0.9": best_subset,
        "transfer_delta": delta,
        "member_summaries": member_summaries,
    }
    out_dir = _DEFAULT_CKPT_ROOT / "voting-italia" / args.run
    out_dir.mkdir(parents=True, exist_ok=True)
    report_path = out_dir / "report.json"
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    np.savez_compressed(
        out_dir / "voting_softmax.npz",
        **{str(pid): arr for pid, arr in vote_result.blended_probs_by_patch.items()},
    )
    logger.info(
        "us079_pixel_report_written",
        path=str(report_path),
        voting_fine_f1=report["voting_eval"]["fine_f1_macro"],
        best_subset_n=best_subset["n_classes"],
    )
    if not args.no_mlflow:
        _log_mlflow(args, report, report_path)


def _advise_vram(members: list[str]) -> None:
    """Log the VRAM budget so the operator can decide serial vs parallel launch."""
    total = sum(_VRAM_GB_PER_MEMBER.get(m, 8.0) for m in members)
    logger.info(
        "us079_vram_budget",
        members=members,
        per_member_gb={m: _VRAM_GB_PER_MEMBER.get(m, 8.0) for m in members},
        total_gb_if_parallel=round(total, 1),
        note="check nvidia-smi BEFORE launching; queue serially if the sum exceeds "
        "the free VRAM (a shared H100; never kill the other session).",
    )


def _log_mlflow(args: argparse.Namespace, report: dict, report_path: Path) -> None:
    """Log the US-079 params / metrics / artifacts to the MLflow server."""
    from ml.utils.mlflow_utils import track_experiment

    with track_experiment(
        "us079-transfer-italia",
        run_name=f"voting3-{args.run}-fold{args.test_fold}",
        dvc_path=str(args.italia_root),
    ) as run:
        import mlflow

        for member, weight in report["voting_weights"].items():
            mlflow.log_param(f"weight_{member}", weight)
        mlflow.log_param("members", ",".join(report["members"]))
        mlflow.log_param("test_fold", report["test_fold"])
        mlflow.log_param("vote_space", report.get("vote_space", "parcel"))
        oof_f1 = report.get("voting_oof_f1_macro")
        if oof_f1 is not None:
            mlflow.log_metric("voting_oof_f1_macro", float(oof_f1))
        # The parcel vote reports OOF accuracy + join coverage; the pixel vote a
        # full dense fine/coarse eval. Log whichever shape this report carries.
        if "voting_oof_accuracy" in report and report["voting_oof_accuracy"] is not None:
            mlflow.log_metric("voting_oof_accuracy", float(report["voting_oof_accuracy"]))
        # The pixel vote logs ``voting_eval``; the parcel vote logs the dense eval
        # of its projection (``voting_dense_eval``). Log whichever is present so the
        # champion always carries dense fine/coarse metrics for the rubric.
        dense_eval = report.get("voting_eval") or report.get("voting_dense_eval")
        if dense_eval:
            mlflow.log_metric("voting_fine_f1_macro", dense_eval["fine_f1_macro"])
            mlflow.log_metric("voting_fine_miou", dense_eval["fine_miou"])
            mlflow.log_metric("voting_coarse_f1_macro", dense_eval["coarse_f1_macro"])
            mlflow.log_metric("voting_coarse_miou", dense_eval["coarse_miou"])
        best_subset = report.get("best_subset_f1_over_0.9") or report.get(
            "voting_dense_best_subset_f1_over_0.9"
        )
        if best_subset:
            mlflow.log_metric("best_subset_n_classes", best_subset["n_classes"])
            mlflow.log_metric("best_subset_macro_f1", best_subset["macro_f1"])
        for key, value in report.get("transfer_delta", {}).items():
            mlflow.log_metric(key, value)
        mlflow.log_artifact(str(report_path))
        logger.info("us079_mlflow_logged", run_id=run.info.run_id)


if __name__ == "__main__":
    main()
